<template>
  <AppLayout>
    <section class="workspace-admin"><header class="workspace-admin__header"><div><p>{{ t('workspace.eyebrow') }}</p><h1>{{ t('workspace.adminTitle') }}</h1><span>{{ t('workspace.adminDescription') }}</span></div><button type="button" class="btn btn-secondary btn-sm" :disabled="loading" @click="load">{{ t('common.refresh') }}</button></header><div v-if="error" class="workspace-state" role="alert">{{ t('workspace.adminUnavailable') }}</div><div v-else-if="loading" class="workspace-state" role="status">{{ t('common.loading') }}</div><div v-else-if="workspaces.length" class="workspace-table-wrap"><table class="workspace-table"><thead><tr><th>{{ t('common.name') }}</th><th>{{ t('workspace.slug') }}</th><th>{{ t('common.status') }}</th><th>{{ t('common.actions') }}</th></tr></thead><tbody><tr v-for="workspace in workspaces" :key="workspace.id"><td><strong>{{ workspace.name }}</strong><small>#{{ workspace.id }}</small></td><td><code>{{ workspace.slug }}</code></td><td>{{ workspace.status }}</td><td><div class="workspace-actions"><button type="button" class="btn btn-secondary btn-sm" @click="inspect(workspace.id)">{{ t('workspace.inspect') }}</button><button type="button" class="btn btn-ghost btn-sm" @click="setStatus(workspace)">{{ workspace.status === 'suspended' ? t('workspace.activateWorkspace') : t('workspace.suspendWorkspace') }}</button></div></td></tr></tbody></table></div><div v-else class="workspace-state">{{ t('common.noData') }}</div><pre v-if="inspected" class="workspace-inspect">{{ JSON.stringify(inspected, null, 2) }}</pre></section>
  </AppLayout>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useI18n } from 'vue-i18n'; import AppLayout from '@/components/layout/AppLayout.vue'; import { workspaceAPI, type Workspace } from '@/api/workspace'; import { useAppStore } from '@/stores/app'
const { t } = useI18n(); const app = useAppStore(); const workspaces = ref<Workspace[]>([]); const loading = ref(false); const error = ref(false); const inspected = ref<Workspace | null>(null)
async function load() { loading.value = true; error.value = false; try { workspaces.value = (await workspaceAPI.adminList()).items || [] } catch { error.value = true } finally { loading.value = false } }
async function inspect(id: number) { try { inspected.value = await workspaceAPI.adminInspect(id) } catch (cause) { app.showError((cause as { message?: string })?.message || t('workspace.adminUnavailable')) } }
async function setStatus(workspace: Workspace) { const status = workspace.status === 'suspended' ? 'active' : 'suspended'; try { const result = await workspaceAPI.adminSetStatus(workspace.id, status); const index = workspaces.value.findIndex(item => item.id === workspace.id); if (index >= 0) workspaces.value[index] = result; app.showSuccess(t('common.saved')) } catch (cause) { app.showError((cause as { message?: string })?.message || t('workspace.statusError')) } }
onMounted(load)
</script>

<style scoped>
.workspace-admin { max-width: 1440px; margin: 0 auto; }.workspace-admin__header { display: flex; align-items: flex-end; justify-content: space-between; gap: 16px; padding: 8px 0 20px; }.workspace-admin__header p { margin: 0 0 6px; color: var(--color-text-muted); font-size: 12px; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; }.workspace-admin__header h1 { margin: 0; color: var(--color-text-primary); font-size: 24px; }.workspace-admin__header span { display: block; margin-top: 6px; color: var(--color-text-secondary); font-size: 14px; }.workspace-table-wrap { overflow-x: auto; border: 1px solid var(--color-border); border-radius: 12px; background: var(--color-surface); }.workspace-table { width: 100%; min-width: 700px; border-collapse: collapse; }.workspace-table th, .workspace-table td { border-bottom: 1px solid var(--color-border-subtle); padding: 13px 12px; text-align: left; }.workspace-table th { color: var(--color-text-muted); font-size: 12px; text-transform: uppercase; }.workspace-table td { color: var(--color-text-secondary); font-size: 13px; }.workspace-table td:first-child { color: var(--color-text-primary); }.workspace-table small { display: block; margin-top: 3px; color: var(--color-text-muted); }.workspace-actions { display: flex; flex-wrap: wrap; gap: 7px; }.workspace-state { padding: 40px 0; color: var(--color-text-muted); text-align: center; }.workspace-inspect { overflow: auto; margin-top: 18px; border: 1px solid var(--color-border); border-radius: 10px; background: var(--color-surface); padding: 16px; color: var(--color-text-secondary); font-size: 12px; }
@media (max-width: 640px) { .workspace-admin__header { align-items: stretch; flex-direction: column; } }
</style>
