export default {
  workspace: {
    lifecycle: {
      title: '数据生命周期', description: '管理当前工作空间的数据保留、导出、归档与业务关闭。', refresh: '刷新', signIn: '重新登录',
      retention: '数据保留策略', retentionHint: '财务与审计证据永久保留，其他类别遵循当前生效的保留策略。', category: '数据类别', effectiveRetention: '生效保留期限', minimum: '最短保留期限', actions: '操作', indefinite: '永久保留', days: '{days} 天', protected: '受当前策略保护', retentionFor: '{category}的保留天数', retentionFloorHint: '0 表示永久保留；有限天数不得低于该类别的最低要求。', readOnly: '只读',
      archiveRestore: '归档与恢复', archiveHint: '归档会停止新的工作空间业务操作并保留历史记录。恢复需通过服务端的安全检查。', archiveWorkspace: '归档工作空间', restoreWorkspace: '恢复工作空间', archiveConfirm: '确认归档此工作空间并停止新的业务操作？', restoreHint: '确认恢复此已归档资源？服务端会检查当前成员资格、计费与身份验证要求。', restoreProject: '恢复项目', projectLifecycle: '项目生命周期', projectArchiveHint: '归档会保留项目历史并停止新的业务操作，仅在所属工作空间处于正常状态时才能恢复项目。',
      exports: '导出记录', exportHint: '导出包含允许导出的数据快照，不包含凭证密钥。导出并非完整备份，也不能用于恢复工作空间。', createExport: '创建导出', exportDisabled: '平台配置未启用导出创建。', noExports: '暂无导出记录。', exportJob: '导出任务', progress: '处理进度', snapshot: '快照截止时间', artifact: '导出文件', processed: '已处理 {count} 条记录', attempts: '已尝试 {count} 次', bytes: '{count} 字节', created: '创建时间', updated: '更新时间', completed: '完成时间', expires: '到期时间', download: '下载 ZIP', cancelExport: '取消导出', exportPagination: '导出记录分页', previous: '上一页', next: '下一页', page: '第 {page} 页，共 {pages} 页', downloadExpired: '下载授权已过期，请重新发起下载。',
      deletion: '删除工作空间', deletionHint: '删除请求至少经过 7 天冷静期后关闭工作空间业务。受保护证据与租户标识仍会保留，此操作不承诺物理擦除。', retainedConfiguration: '业务关闭期间，当前保留策略尚不允许清理的配置仍会保留。', purgeDisabled: '平台配置未启用删除清理。', businessClosure: '业务关闭状态', businessClosed: '业务已关闭', businessNotClosed: '业务尚未关闭', protectedEvidence: '受保护证据', evidenceRetained: '受保护的财务与审计证据仍会保留', evidenceStatusUnknown: '请核对服务端返回的证据状态', phase: '当前阶段', earliestPurge: '最早清理时间', cancelDeletion: '取消删除', retryDeletion: '重试受阻或失败的删除', checkPreflight: '检查删除条件', requestDeletion: '申请删除', eligible: '符合删除申请条件', blocked: '删除条件尚未满足', cappedCounts: '部分计数已达到上限，仅表示下界；服务端会在处理前重新检查阻塞条件。', protectedResource: '受保护：{resource}', purgeScope: '预计清理范围', retainedScope: '保留范围', confirmDeletion: '确认删除工作空间', exactName: '输入当前工作空间完整名称：{name}', exactNameHint: '名称必须完全匹配，包括空格和大小写。', challengeExpired: '删除确认已过期，请生成新的确认后继续。', confirmationExpires: '确认到期时间', refreshChallenge: '生成新的确认', operationSuccess: '服务端已接受此操作。', requestError: '生命周期请求失败，请刷新后重试。', verificationCancelled: '身份验证已取消，尚未重试此操作。',
      categories: { financial: '财务证据', audit: '审计证据', operational: '运营数据', security: '安全数据', temporary: '临时文件' },
      states: { pending: '等待处理', running: '处理中', completed: '已完成', failed: '失败', cancelled: '已取消', expired: '已过期', blocked: '受阻' },
      phases: { credentials: '凭证', service_accounts: '服务账号', invitations: '邀请', access_grants: '访问授权', project_allocation_configuration: '项目成本分配配置', key_allocation_configuration: '密钥成本分配配置', machine_allocation_configuration: '服务账号成本分配配置', identity_credentials: '身份提供者凭证', scim_credentials: 'SCIM 凭证', scim_connectors: 'SCIM 连接器', webhook_credentials: 'Webhook 凭证', member_access: '成员访问权限', teams: '团队', projects: '项目', grants: '访问授权', allocation: '成本分配配置', members: '成员访问权限', descriptions: '业务说明', verify: '完成检查', completed: '已完成' },
      resources: { projects: '项目', members: '成员', service_accounts: '服务账号', credentials: '凭证', api_keys: 'API 密钥', invitations: '邀请', active_holds: '活跃保留项', usage_logs: '用量记录', reservations: '预留记录', running_exports: '运行中的导出', pending_budget_reservations: '待结算预算预留', reserved_budget_counters: '预留预算计数', pending_quota_reservations: '待结算配额预留', pending_billing_settlements: '待完成计费结算', pending_async_images: '待完成媒体任务', pending_exports: '待完成导出', pending_webhook_deliveries: '待完成 Webhook 投递', pending_outbox: '待投递域事件', budget_reservations: '预算预留记录', allocation_snapshots: '用量成本分配快照', reservation_allocation_snapshots: '预留成本分配快照', anomaly_evidence: '异常证据', audit_logs: '审计记录' },
      scopes: { credential_values: '凭证密钥值', credentials: '凭证', invitations: '邀请', project_access_grants: '项目访问授权', allocation_configuration: '可清理的成本分配配置', non_owner_membership_access: '除所有者外的成员访问权限', business_resource_descriptions: '可清理的业务资源说明', global_users_and_wallets: '全局用户与钱包', workspace_project_credential_identifiers: '工作空间、项目与凭证标识', usage_and_reservations: '用量与预留记录', settlement_refund_dedup: '结算、退款与去重证据', immutable_allocation_anomaly_evidence: '不可变成本分配与异常证据', audit_and_policy_protected_metadata: '审计与策略保护的元数据', policy_ineligible_business_configuration: '当前保留策略保护的业务配置', global_user_owned_canvas_media: '全局用户拥有的 Canvas 媒体', financial_evidence: '财务证据' },
    },
  },
}
