export default {
  workspace: {
    historicalUsageNote: '未记录工作区或项目的历史用量保留为未归属，可在原用量页面查看，不计入此处汇总。',
    dailySpend: '每日支出', date: '日期',
    archive: '归档', groupPolicy: '分组访问', modelPolicy: '模型访问', allowedGroupIds: '允许的分组 ID', allowedModels: '允许的模型', allowedPlatforms: '允许的平台', groupIdsHint: '每行填写一个正整数分组 ID', modelsHint: '每行填写一个完整模型 ID', platformsHint: '每行填写一个平台 ID', accessModes: { inherit: '继承访问范围', restricted: '只允许指定条目', deny: '全部拒绝' }, policyModes: { inherit: '继承', restricted: '只允许指定条目', deny: '全部拒绝' }, policyLayers: { group: '分组', workspace: '工作区', project: '项目', service_account: '服务账号', credential: '凭证' }, accessPolicyHint: '项目策略可以缩小计费主体的分组和模型访问范围。', invalidAccessPolicy: '指定条目策略需要有效的分组 ID 和至少一个模型。', policyDescription: '当前作用域只能继续收紧上级策略。留空值表示继承。', effectivePolicyDescription: '只读结果，展示所有适用策略层计算后的限制。', policyNoAdditionalRestrictions: '各层都未设置额外限制。', policyRevision: '版本 {revision}', policyProvenance: '策略版本', policyTriStateHint: '继承会保留 null；空列表表示明确拒绝所有条目。', policyLoadError: '策略加载失败。', policyUnavailable: '当前工作区不可读取策略。', policySaveError: '策略保存失败，请刷新后重试。', policyInvalidNumericLimit: '限额必须为正整数，也可以留空以继承。', policyAllowlistRequired: '请至少填写一项，或选择继承/全部拒绝。', policyRevisionConflict: '此策略已被其他管理员修改，请重新加载后再保存。', rpmLimit: '每分钟请求数', dailyRequestLimit: '每日请求配额', monthlyRequestLimit: '每月请求配额', dailyTokenLimit: '每日 Token 配额', monthlyTokenLimit: '每月 Token 配额',
    inaccessibleWorkspace: '此工作区不可用，或你的访问权限已失效。', acceptInvitation: '接受邀请', acceptInvitationDescription: '输入工作区管理员提供的邀请令牌。', acceptInvitationError: '接受邀请失败。', noInvitations: '暂无邀请。', roles: { owner: '所有者', admin: '管理员', developer: '开发者', billing: '财务', viewer: '查看者' },
    platforms: '平台', models: '模型', apiKeys: 'API 密钥', noUsage: '此时间段暂无用量。', projectBudgetDescription: '当前项目的预算预留和支出。', projectBudgetUnavailable: '项目预算数据暂不可用。', projectOverBudget: '此项目已超过配置的预算。', projectUsageUnavailable: '项目用量数据暂不可用。', usageDescription: '显示时间段内的请求数和支出。',
    eyebrow: '租户工作区', title: '工作区', description: '选择工作区和项目，管理访问权限、密钥和费用。', createWorkspace: '创建工作区', settings: '工作区设置', settingsDescription: '工作区信息与计费主体需要分别更新。', billingOwner: '计费主体',
    workspace: '工作区', project: '项目', sections: '工作区分区', overview: '概览', projects: '项目', members: '成员', invitations: '邀请', finops: '费用', audit: '审计', keys: '项目密钥', policySettings: '策略', policyNavigation: '策略导航', workspacePolicy: '工作区策略', projectPolicy: '项目策略', serviceAccountPolicy: '服务账号策略', effectivePolicy: '生效策略',
    projectsDescription: '项目在工作区内隔离路由策略、密钥和使用量。', createProject: '创建项目', editProject: '编辑项目', noProjects: '此工作区暂无项目。', default: '默认', slug: 'Slug', descriptionLabel: '描述', saveError: '工作区变更保存失败。', archiveConfirm: '归档此项目？', loadError: '工作区加载失败。',
    membersDescription: '根据服务端返回的权限查看、暂停或移除成员。', noMembers: '暂无成员。', member: '成员', role: '角色', roleFor: '成员角色', invite: '邀请成员', suspend: '暂停', activate: '启用', remove: '移除', removeConfirm: '移除此成员？', updateMemberError: '成员变更保存失败。',
    invitationDescription: '邀请会过期，也可以在接受前撤销。', email: '邮箱', expires: '过期时间', pending: '待处理', revoked: '已撤销', accepted: '已接受', createInvitation: '创建邀请', invitationToken: '邀请令牌', copyToken: '复制令牌', revoke: '撤销', revokeConfirm: '撤销此邀请？', invitationError: '邀请保存失败。',
    requests: '请求数', spend: '支出', budget: '预算', budgetDescription: '服务端返回的当前工作区预留和支出状态。', viewFinops: '查看费用', spent: '已支出', reserved: '已预留', remaining: '剩余', overBudget: '此工作区已超过配置的预算。', policy: '预算策略', amount: '月度金额', hardLimit: '硬限制', enabled: '启用', timezone: '时区', updateBudget: '更新预算', budgetUnavailable: '此工作区暂时没有预算数据。', usage: '使用量', usageUnavailable: '此工作区暂时没有使用量数据。', trend: '支出趋势', breakdown: '明细',
    anomalies: 'FinOps 异常', anomaliesDescription: '基于已完成小时用量桶生成的确定性发现，证据快照创建后不可修改。', anomalyOpen: '待处理', anomalyHighCritical: '高 / 严重', anomalyLastDetected: '最近发现', anomalyDetectorStatus: '检测器状态', anomalyStatusHealthy: '正常', anomalyStatusDegraded: '需要关注', anomalyStatusPending: '等待首次扫描', anomalyStatus: '状态', anomalySeverity: '严重度', anomalyDetector: '检测器', anomalyScope: '范围', anomalyObserved: '观测值', anomalyExpected: '预期值', anomalyDelta: '差值', anomalyWindow: '时间窗', anomalyDetected: '发现时间', anomalyDetails: '详情', anomalyEvidence: '证据快照', anomalyBaselineSamples: '基线样本', anomalyScore: '稳健分数', anomalyResolutionReason: '解决原因', anomalyAcknowledge: '确认', anomalyResolve: '解决', anomalyApplyFilters: '应用筛选', anomalyAllStatuses: '全部状态', anomalyAllSeverities: '全部严重度', anomalyAllDetectors: '全部检测器', anomalyLoadError: '异常加载失败。', anomalySaveError: '异常更新失败。', noAnomalies: '没有符合筛选条件的异常发现。', anomalyExplanation: '观测值 {observed}，预期值 {expected}，增加 {increase}；基线样本 {samples} 个；稳健分数 {score}。', anomalyStatuses: { open: '待处理', acknowledged: '已确认', resolved: '已解决' }, anomalySeverities: { low: '低', medium: '中', high: '高', critical: '严重' }, anomalyDetectors: { spend_spike: '支出突增', request_spike: '请求突增', unit_cost_spike: '单位成本突增' },
    auditDescription: '租户范围内的变更记录会显示在这里。', noAudit: '暂无审计事件。', action: '操作', actor: '操作者', target: '目标', created: '创建时间',
    keyDescription: '项目密钥继承项目限制。创建后只显示一次密钥明文。', createKey: '创建项目密钥', editKey: '编辑项目密钥', keyName: '密钥名称', keySecret: '密钥', copySecret: '复制密钥', maskedSecret: '读取时已遮罩', status: '状态', revokeKey: '撤销密钥', revokeKeyConfirm: '撤销此项目密钥？', keyError: '项目密钥保存失败。', noKeys: '暂无项目密钥。', group: '分组', noGroup: '不绑定分组', quotaUsage: '配额 / 用量', rateLimits: '限额窗口', rateLimit5h: '5 小时限额', rateLimit1d: '1 天限额', rateLimit7d: '7 天限额', ipWhitelist: 'IP 白名单', ipBlacklist: 'IP 黑名单', ipListHint: '每行填写一个地址或 CIDR', unlimited: '不限',
    adminTitle: '工作区管理', adminDescription: '使用全局管理员权限查看和暂停租户工作区。', adminUnavailable: '工作区管理暂不可用。', inspect: '查看', suspendWorkspace: '暂停工作区', activateWorkspace: '启用工作区', statusError: '工作区状态变更失败。',
    teams: '团队', teamsTitle: '工作区团队', teamsDescription: '将工作区成员分组，让项目访问可以按团队治理。', createTeam: '创建团队', editTeam: '编辑团队', teamFormDescription: '团队只包含已有工作区成员，不会创建用户。', noTeams: '暂无团队。', teamName: '团队名称', teamSlug: '团队 Slug', teamDescriptionLabel: '描述', archiveTeam: '归档', archiveTeamConfirm: '归档这个团队？', teamSaveError: '团队变更保存失败。', selectTeam: '管理成员', teamMembers: '团队成员', teamMembersDescription: '将活跃的工作区成员加入或移出这个团队。', addTeamMember: '添加成员', selectMember: '选择成员', noTeamMembers: '这个团队还没有成员。', removeTeamMemberConfirm: '将该成员移出团队？', teamMemberError: '团队成员变更保存失败。', projectAccess: '项目访问', projectAccessDescription: '将项目限制为明确授予访问权的工作区成员和团队。', projectAccessUnavailable: '项目访问暂不可用。', projectAccessMode: '项目访问模式', allProjects: '所有项目', assignedProjects: '仅已分配项目', allProjectsDescription: '所有活跃工作区成员继续按工作区角色访问。', assignedProjectsDescription: '只有获得授权的成员和团队可以访问此项目。', projectAccessReadOnly: '你拥有查看此设置的权限，但不能修改。', noAccessGrants: '暂无项目访问授权。', projectAccessGrants: '访问授权', projectAccessGrantDescription: '为工作区成员或团队授予内置项目角色。', subject: '主体', subjectType: '主体类型', teamSubject: '团队', memberSubject: '成员', selectSubject: '选择主体', grantRole: '项目角色', createGrant: '添加授权', deleteGrant: '移除', deleteGrantConfirm: '移除这个项目访问授权？', projectAccessError: '项目访问变更保存失败。', projectAccessModeError: '项目访问模式变更失败。'
  }
}
