// Code generated by ent, DO NOT EDIT.

package emailorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldID, id))
}

// PublicID applies equality check predicate on the "public_id" field. It's identical to PublicIDEQ.
func PublicID(v uuid.UUID) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldPublicID, v))
}

// OrderNo applies equality check predicate on the "order_no" field. It's identical to OrderNoEQ.
func OrderNo(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldOrderNo, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldUserID, v))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldChannelID, v))
}

// ProviderID applies equality check predicate on the "provider_id" field. It's identical to ProviderIDEQ.
func ProviderID(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldProviderID, v))
}

// ServiceID applies equality check predicate on the "service_id" field. It's identical to ServiceIDEQ.
func ServiceID(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldServiceID, v))
}

// ProviderInboxID applies equality check predicate on the "provider_inbox_id" field. It's identical to ProviderInboxIDEQ.
func ProviderInboxID(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldProviderInboxID, v))
}

// EmailAddress applies equality check predicate on the "email_address" field. It's identical to EmailAddressEQ.
func EmailAddress(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldEmailAddress, v))
}

// AddressType applies equality check predicate on the "address_type" field. It's identical to AddressTypeEQ.
func AddressType(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldAddressType, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldStatus, v))
}

// SalePriceSnapshot applies equality check predicate on the "sale_price_snapshot" field. It's identical to SalePriceSnapshotEQ.
func SalePriceSnapshot(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldSalePriceSnapshot, v))
}

// ProviderCostEstimateSnapshot applies equality check predicate on the "provider_cost_estimate_snapshot" field. It's identical to ProviderCostEstimateSnapshotEQ.
func ProviderCostEstimateSnapshot(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldProviderCostEstimateSnapshot, v))
}

// SuccessRateSnapshot applies equality check predicate on the "success_rate_snapshot" field. It's identical to SuccessRateSnapshotEQ.
func SuccessRateSnapshot(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldSuccessRateSnapshot, v))
}

// SuccessRateGradeSnapshot applies equality check predicate on the "success_rate_grade_snapshot" field. It's identical to SuccessRateGradeSnapshotEQ.
func SuccessRateGradeSnapshot(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldSuccessRateGradeSnapshot, v))
}

// RefundPolicySnapshot applies equality check predicate on the "refund_policy_snapshot" field. It's identical to RefundPolicySnapshotEQ.
func RefundPolicySnapshot(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldRefundPolicySnapshot, v))
}

// CapturePolicySnapshot applies equality check predicate on the "capture_policy_snapshot" field. It's identical to CapturePolicySnapshotEQ.
func CapturePolicySnapshot(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldCapturePolicySnapshot, v))
}

// ReservedAmount applies equality check predicate on the "reserved_amount" field. It's identical to ReservedAmountEQ.
func ReservedAmount(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldReservedAmount, v))
}

// CapturedAmount applies equality check predicate on the "captured_amount" field. It's identical to CapturedAmountEQ.
func CapturedAmount(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldCapturedAmount, v))
}

// ReleasedAmount applies equality check predicate on the "released_amount" field. It's identical to ReleasedAmountEQ.
func ReleasedAmount(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldReleasedAmount, v))
}

// RefundedAmount applies equality check predicate on the "refunded_amount" field. It's identical to RefundedAmountEQ.
func RefundedAmount(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldRefundedAmount, v))
}

// InboxCreatedAt applies equality check predicate on the "inbox_created_at" field. It's identical to InboxCreatedAtEQ.
func InboxCreatedAt(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldInboxCreatedAt, v))
}

// WaitingStartedAt applies equality check predicate on the "waiting_started_at" field. It's identical to WaitingStartedAtEQ.
func WaitingStartedAt(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldWaitingStartedAt, v))
}

// FirstMessageAt applies equality check predicate on the "first_message_at" field. It's identical to FirstMessageAtEQ.
func FirstMessageAt(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldFirstMessageAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldCompletedAt, v))
}

// CancelledAt applies equality check predicate on the "cancelled_at" field. It's identical to CancelledAtEQ.
func CancelledAt(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldCancelledAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldExpiresAt, v))
}

// PollCount applies equality check predicate on the "poll_count" field. It's identical to PollCountEQ.
func PollCount(v int) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldPollCount, v))
}

// NextPollAt applies equality check predicate on the "next_poll_at" field. It's identical to NextPollAtEQ.
func NextPollAt(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldNextPollAt, v))
}

// LastPolledAt applies equality check predicate on the "last_polled_at" field. It's identical to LastPolledAtEQ.
func LastPolledAt(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldLastPolledAt, v))
}

// ProviderRequestCount applies equality check predicate on the "provider_request_count" field. It's identical to ProviderRequestCountEQ.
func ProviderRequestCount(v int) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldProviderRequestCount, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorPublicMessage applies equality check predicate on the "error_public_message" field. It's identical to ErrorPublicMessageEQ.
func ErrorPublicMessage(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldErrorPublicMessage, v))
}

// ErrorAdminMessage applies equality check predicate on the "error_admin_message" field. It's identical to ErrorAdminMessageEQ.
func ErrorAdminMessage(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldErrorAdminMessage, v))
}

// RefundStatus applies equality check predicate on the "refund_status" field. It's identical to RefundStatusEQ.
func RefundStatus(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldRefundStatus, v))
}

// RefundReason applies equality check predicate on the "refund_reason" field. It's identical to RefundReasonEQ.
func RefundReason(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldRefundReason, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldIdempotencyKey, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// PublicIDEQ applies the EQ predicate on the "public_id" field.
func PublicIDEQ(v uuid.UUID) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldPublicID, v))
}

// PublicIDNEQ applies the NEQ predicate on the "public_id" field.
func PublicIDNEQ(v uuid.UUID) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldPublicID, v))
}

// PublicIDIn applies the In predicate on the "public_id" field.
func PublicIDIn(vs ...uuid.UUID) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldPublicID, vs...))
}

// PublicIDNotIn applies the NotIn predicate on the "public_id" field.
func PublicIDNotIn(vs ...uuid.UUID) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldPublicID, vs...))
}

// PublicIDGT applies the GT predicate on the "public_id" field.
func PublicIDGT(v uuid.UUID) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldPublicID, v))
}

// PublicIDGTE applies the GTE predicate on the "public_id" field.
func PublicIDGTE(v uuid.UUID) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldPublicID, v))
}

// PublicIDLT applies the LT predicate on the "public_id" field.
func PublicIDLT(v uuid.UUID) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldPublicID, v))
}

// PublicIDLTE applies the LTE predicate on the "public_id" field.
func PublicIDLTE(v uuid.UUID) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldPublicID, v))
}

// OrderNoEQ applies the EQ predicate on the "order_no" field.
func OrderNoEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldOrderNo, v))
}

// OrderNoNEQ applies the NEQ predicate on the "order_no" field.
func OrderNoNEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldOrderNo, v))
}

// OrderNoIn applies the In predicate on the "order_no" field.
func OrderNoIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldOrderNo, vs...))
}

// OrderNoNotIn applies the NotIn predicate on the "order_no" field.
func OrderNoNotIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldOrderNo, vs...))
}

// OrderNoGT applies the GT predicate on the "order_no" field.
func OrderNoGT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldOrderNo, v))
}

// OrderNoGTE applies the GTE predicate on the "order_no" field.
func OrderNoGTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldOrderNo, v))
}

// OrderNoLT applies the LT predicate on the "order_no" field.
func OrderNoLT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldOrderNo, v))
}

// OrderNoLTE applies the LTE predicate on the "order_no" field.
func OrderNoLTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldOrderNo, v))
}

// OrderNoContains applies the Contains predicate on the "order_no" field.
func OrderNoContains(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContains(FieldOrderNo, v))
}

// OrderNoHasPrefix applies the HasPrefix predicate on the "order_no" field.
func OrderNoHasPrefix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasPrefix(FieldOrderNo, v))
}

// OrderNoHasSuffix applies the HasSuffix predicate on the "order_no" field.
func OrderNoHasSuffix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasSuffix(FieldOrderNo, v))
}

// OrderNoEqualFold applies the EqualFold predicate on the "order_no" field.
func OrderNoEqualFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEqualFold(FieldOrderNo, v))
}

// OrderNoContainsFold applies the ContainsFold predicate on the "order_no" field.
func OrderNoContainsFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContainsFold(FieldOrderNo, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldUserID, v))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldChannelID, vs...))
}

// ChannelIDGT applies the GT predicate on the "channel_id" field.
func ChannelIDGT(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldChannelID, v))
}

// ChannelIDGTE applies the GTE predicate on the "channel_id" field.
func ChannelIDGTE(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldChannelID, v))
}

// ChannelIDLT applies the LT predicate on the "channel_id" field.
func ChannelIDLT(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldChannelID, v))
}

// ChannelIDLTE applies the LTE predicate on the "channel_id" field.
func ChannelIDLTE(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldChannelID, v))
}

// ProviderIDEQ applies the EQ predicate on the "provider_id" field.
func ProviderIDEQ(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldProviderID, v))
}

// ProviderIDNEQ applies the NEQ predicate on the "provider_id" field.
func ProviderIDNEQ(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldProviderID, v))
}

// ProviderIDIn applies the In predicate on the "provider_id" field.
func ProviderIDIn(vs ...int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldProviderID, vs...))
}

// ProviderIDNotIn applies the NotIn predicate on the "provider_id" field.
func ProviderIDNotIn(vs ...int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldProviderID, vs...))
}

// ProviderIDGT applies the GT predicate on the "provider_id" field.
func ProviderIDGT(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldProviderID, v))
}

// ProviderIDGTE applies the GTE predicate on the "provider_id" field.
func ProviderIDGTE(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldProviderID, v))
}

// ProviderIDLT applies the LT predicate on the "provider_id" field.
func ProviderIDLT(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldProviderID, v))
}

// ProviderIDLTE applies the LTE predicate on the "provider_id" field.
func ProviderIDLTE(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldProviderID, v))
}

// ServiceIDEQ applies the EQ predicate on the "service_id" field.
func ServiceIDEQ(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldServiceID, v))
}

// ServiceIDNEQ applies the NEQ predicate on the "service_id" field.
func ServiceIDNEQ(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldServiceID, v))
}

// ServiceIDIn applies the In predicate on the "service_id" field.
func ServiceIDIn(vs ...int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldServiceID, vs...))
}

// ServiceIDNotIn applies the NotIn predicate on the "service_id" field.
func ServiceIDNotIn(vs ...int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldServiceID, vs...))
}

// ServiceIDGT applies the GT predicate on the "service_id" field.
func ServiceIDGT(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldServiceID, v))
}

// ServiceIDGTE applies the GTE predicate on the "service_id" field.
func ServiceIDGTE(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldServiceID, v))
}

// ServiceIDLT applies the LT predicate on the "service_id" field.
func ServiceIDLT(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldServiceID, v))
}

// ServiceIDLTE applies the LTE predicate on the "service_id" field.
func ServiceIDLTE(v int64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldServiceID, v))
}

// ProviderInboxIDEQ applies the EQ predicate on the "provider_inbox_id" field.
func ProviderInboxIDEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldProviderInboxID, v))
}

// ProviderInboxIDNEQ applies the NEQ predicate on the "provider_inbox_id" field.
func ProviderInboxIDNEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldProviderInboxID, v))
}

// ProviderInboxIDIn applies the In predicate on the "provider_inbox_id" field.
func ProviderInboxIDIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldProviderInboxID, vs...))
}

// ProviderInboxIDNotIn applies the NotIn predicate on the "provider_inbox_id" field.
func ProviderInboxIDNotIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldProviderInboxID, vs...))
}

// ProviderInboxIDGT applies the GT predicate on the "provider_inbox_id" field.
func ProviderInboxIDGT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldProviderInboxID, v))
}

// ProviderInboxIDGTE applies the GTE predicate on the "provider_inbox_id" field.
func ProviderInboxIDGTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldProviderInboxID, v))
}

// ProviderInboxIDLT applies the LT predicate on the "provider_inbox_id" field.
func ProviderInboxIDLT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldProviderInboxID, v))
}

// ProviderInboxIDLTE applies the LTE predicate on the "provider_inbox_id" field.
func ProviderInboxIDLTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldProviderInboxID, v))
}

// ProviderInboxIDContains applies the Contains predicate on the "provider_inbox_id" field.
func ProviderInboxIDContains(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContains(FieldProviderInboxID, v))
}

// ProviderInboxIDHasPrefix applies the HasPrefix predicate on the "provider_inbox_id" field.
func ProviderInboxIDHasPrefix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasPrefix(FieldProviderInboxID, v))
}

// ProviderInboxIDHasSuffix applies the HasSuffix predicate on the "provider_inbox_id" field.
func ProviderInboxIDHasSuffix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasSuffix(FieldProviderInboxID, v))
}

// ProviderInboxIDEqualFold applies the EqualFold predicate on the "provider_inbox_id" field.
func ProviderInboxIDEqualFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEqualFold(FieldProviderInboxID, v))
}

// ProviderInboxIDContainsFold applies the ContainsFold predicate on the "provider_inbox_id" field.
func ProviderInboxIDContainsFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContainsFold(FieldProviderInboxID, v))
}

// EmailAddressEQ applies the EQ predicate on the "email_address" field.
func EmailAddressEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldEmailAddress, v))
}

// EmailAddressNEQ applies the NEQ predicate on the "email_address" field.
func EmailAddressNEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldEmailAddress, v))
}

// EmailAddressIn applies the In predicate on the "email_address" field.
func EmailAddressIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldEmailAddress, vs...))
}

// EmailAddressNotIn applies the NotIn predicate on the "email_address" field.
func EmailAddressNotIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldEmailAddress, vs...))
}

// EmailAddressGT applies the GT predicate on the "email_address" field.
func EmailAddressGT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldEmailAddress, v))
}

// EmailAddressGTE applies the GTE predicate on the "email_address" field.
func EmailAddressGTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldEmailAddress, v))
}

// EmailAddressLT applies the LT predicate on the "email_address" field.
func EmailAddressLT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldEmailAddress, v))
}

// EmailAddressLTE applies the LTE predicate on the "email_address" field.
func EmailAddressLTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldEmailAddress, v))
}

// EmailAddressContains applies the Contains predicate on the "email_address" field.
func EmailAddressContains(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContains(FieldEmailAddress, v))
}

// EmailAddressHasPrefix applies the HasPrefix predicate on the "email_address" field.
func EmailAddressHasPrefix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasPrefix(FieldEmailAddress, v))
}

// EmailAddressHasSuffix applies the HasSuffix predicate on the "email_address" field.
func EmailAddressHasSuffix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasSuffix(FieldEmailAddress, v))
}

// EmailAddressEqualFold applies the EqualFold predicate on the "email_address" field.
func EmailAddressEqualFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEqualFold(FieldEmailAddress, v))
}

// EmailAddressContainsFold applies the ContainsFold predicate on the "email_address" field.
func EmailAddressContainsFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContainsFold(FieldEmailAddress, v))
}

// AddressTypeEQ applies the EQ predicate on the "address_type" field.
func AddressTypeEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldAddressType, v))
}

// AddressTypeNEQ applies the NEQ predicate on the "address_type" field.
func AddressTypeNEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldAddressType, v))
}

// AddressTypeIn applies the In predicate on the "address_type" field.
func AddressTypeIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldAddressType, vs...))
}

// AddressTypeNotIn applies the NotIn predicate on the "address_type" field.
func AddressTypeNotIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldAddressType, vs...))
}

// AddressTypeGT applies the GT predicate on the "address_type" field.
func AddressTypeGT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldAddressType, v))
}

// AddressTypeGTE applies the GTE predicate on the "address_type" field.
func AddressTypeGTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldAddressType, v))
}

// AddressTypeLT applies the LT predicate on the "address_type" field.
func AddressTypeLT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldAddressType, v))
}

// AddressTypeLTE applies the LTE predicate on the "address_type" field.
func AddressTypeLTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldAddressType, v))
}

// AddressTypeContains applies the Contains predicate on the "address_type" field.
func AddressTypeContains(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContains(FieldAddressType, v))
}

// AddressTypeHasPrefix applies the HasPrefix predicate on the "address_type" field.
func AddressTypeHasPrefix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasPrefix(FieldAddressType, v))
}

// AddressTypeHasSuffix applies the HasSuffix predicate on the "address_type" field.
func AddressTypeHasSuffix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasSuffix(FieldAddressType, v))
}

// AddressTypeEqualFold applies the EqualFold predicate on the "address_type" field.
func AddressTypeEqualFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEqualFold(FieldAddressType, v))
}

// AddressTypeContainsFold applies the ContainsFold predicate on the "address_type" field.
func AddressTypeContainsFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContainsFold(FieldAddressType, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContainsFold(FieldStatus, v))
}

// SalePriceSnapshotEQ applies the EQ predicate on the "sale_price_snapshot" field.
func SalePriceSnapshotEQ(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldSalePriceSnapshot, v))
}

// SalePriceSnapshotNEQ applies the NEQ predicate on the "sale_price_snapshot" field.
func SalePriceSnapshotNEQ(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldSalePriceSnapshot, v))
}

// SalePriceSnapshotIn applies the In predicate on the "sale_price_snapshot" field.
func SalePriceSnapshotIn(vs ...float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldSalePriceSnapshot, vs...))
}

// SalePriceSnapshotNotIn applies the NotIn predicate on the "sale_price_snapshot" field.
func SalePriceSnapshotNotIn(vs ...float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldSalePriceSnapshot, vs...))
}

// SalePriceSnapshotGT applies the GT predicate on the "sale_price_snapshot" field.
func SalePriceSnapshotGT(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldSalePriceSnapshot, v))
}

// SalePriceSnapshotGTE applies the GTE predicate on the "sale_price_snapshot" field.
func SalePriceSnapshotGTE(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldSalePriceSnapshot, v))
}

// SalePriceSnapshotLT applies the LT predicate on the "sale_price_snapshot" field.
func SalePriceSnapshotLT(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldSalePriceSnapshot, v))
}

// SalePriceSnapshotLTE applies the LTE predicate on the "sale_price_snapshot" field.
func SalePriceSnapshotLTE(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldSalePriceSnapshot, v))
}

// ProviderCostEstimateSnapshotEQ applies the EQ predicate on the "provider_cost_estimate_snapshot" field.
func ProviderCostEstimateSnapshotEQ(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldProviderCostEstimateSnapshot, v))
}

// ProviderCostEstimateSnapshotNEQ applies the NEQ predicate on the "provider_cost_estimate_snapshot" field.
func ProviderCostEstimateSnapshotNEQ(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldProviderCostEstimateSnapshot, v))
}

// ProviderCostEstimateSnapshotIn applies the In predicate on the "provider_cost_estimate_snapshot" field.
func ProviderCostEstimateSnapshotIn(vs ...float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldProviderCostEstimateSnapshot, vs...))
}

// ProviderCostEstimateSnapshotNotIn applies the NotIn predicate on the "provider_cost_estimate_snapshot" field.
func ProviderCostEstimateSnapshotNotIn(vs ...float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldProviderCostEstimateSnapshot, vs...))
}

// ProviderCostEstimateSnapshotGT applies the GT predicate on the "provider_cost_estimate_snapshot" field.
func ProviderCostEstimateSnapshotGT(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldProviderCostEstimateSnapshot, v))
}

// ProviderCostEstimateSnapshotGTE applies the GTE predicate on the "provider_cost_estimate_snapshot" field.
func ProviderCostEstimateSnapshotGTE(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldProviderCostEstimateSnapshot, v))
}

// ProviderCostEstimateSnapshotLT applies the LT predicate on the "provider_cost_estimate_snapshot" field.
func ProviderCostEstimateSnapshotLT(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldProviderCostEstimateSnapshot, v))
}

// ProviderCostEstimateSnapshotLTE applies the LTE predicate on the "provider_cost_estimate_snapshot" field.
func ProviderCostEstimateSnapshotLTE(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldProviderCostEstimateSnapshot, v))
}

// SuccessRateSnapshotEQ applies the EQ predicate on the "success_rate_snapshot" field.
func SuccessRateSnapshotEQ(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldSuccessRateSnapshot, v))
}

// SuccessRateSnapshotNEQ applies the NEQ predicate on the "success_rate_snapshot" field.
func SuccessRateSnapshotNEQ(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldSuccessRateSnapshot, v))
}

// SuccessRateSnapshotIn applies the In predicate on the "success_rate_snapshot" field.
func SuccessRateSnapshotIn(vs ...float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldSuccessRateSnapshot, vs...))
}

// SuccessRateSnapshotNotIn applies the NotIn predicate on the "success_rate_snapshot" field.
func SuccessRateSnapshotNotIn(vs ...float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldSuccessRateSnapshot, vs...))
}

// SuccessRateSnapshotGT applies the GT predicate on the "success_rate_snapshot" field.
func SuccessRateSnapshotGT(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldSuccessRateSnapshot, v))
}

// SuccessRateSnapshotGTE applies the GTE predicate on the "success_rate_snapshot" field.
func SuccessRateSnapshotGTE(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldSuccessRateSnapshot, v))
}

// SuccessRateSnapshotLT applies the LT predicate on the "success_rate_snapshot" field.
func SuccessRateSnapshotLT(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldSuccessRateSnapshot, v))
}

// SuccessRateSnapshotLTE applies the LTE predicate on the "success_rate_snapshot" field.
func SuccessRateSnapshotLTE(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldSuccessRateSnapshot, v))
}

// SuccessRateSnapshotIsNil applies the IsNil predicate on the "success_rate_snapshot" field.
func SuccessRateSnapshotIsNil() predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIsNull(FieldSuccessRateSnapshot))
}

// SuccessRateSnapshotNotNil applies the NotNil predicate on the "success_rate_snapshot" field.
func SuccessRateSnapshotNotNil() predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotNull(FieldSuccessRateSnapshot))
}

// SuccessRateGradeSnapshotEQ applies the EQ predicate on the "success_rate_grade_snapshot" field.
func SuccessRateGradeSnapshotEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldSuccessRateGradeSnapshot, v))
}

// SuccessRateGradeSnapshotNEQ applies the NEQ predicate on the "success_rate_grade_snapshot" field.
func SuccessRateGradeSnapshotNEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldSuccessRateGradeSnapshot, v))
}

// SuccessRateGradeSnapshotIn applies the In predicate on the "success_rate_grade_snapshot" field.
func SuccessRateGradeSnapshotIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldSuccessRateGradeSnapshot, vs...))
}

// SuccessRateGradeSnapshotNotIn applies the NotIn predicate on the "success_rate_grade_snapshot" field.
func SuccessRateGradeSnapshotNotIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldSuccessRateGradeSnapshot, vs...))
}

// SuccessRateGradeSnapshotGT applies the GT predicate on the "success_rate_grade_snapshot" field.
func SuccessRateGradeSnapshotGT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldSuccessRateGradeSnapshot, v))
}

// SuccessRateGradeSnapshotGTE applies the GTE predicate on the "success_rate_grade_snapshot" field.
func SuccessRateGradeSnapshotGTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldSuccessRateGradeSnapshot, v))
}

// SuccessRateGradeSnapshotLT applies the LT predicate on the "success_rate_grade_snapshot" field.
func SuccessRateGradeSnapshotLT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldSuccessRateGradeSnapshot, v))
}

// SuccessRateGradeSnapshotLTE applies the LTE predicate on the "success_rate_grade_snapshot" field.
func SuccessRateGradeSnapshotLTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldSuccessRateGradeSnapshot, v))
}

// SuccessRateGradeSnapshotContains applies the Contains predicate on the "success_rate_grade_snapshot" field.
func SuccessRateGradeSnapshotContains(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContains(FieldSuccessRateGradeSnapshot, v))
}

// SuccessRateGradeSnapshotHasPrefix applies the HasPrefix predicate on the "success_rate_grade_snapshot" field.
func SuccessRateGradeSnapshotHasPrefix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasPrefix(FieldSuccessRateGradeSnapshot, v))
}

// SuccessRateGradeSnapshotHasSuffix applies the HasSuffix predicate on the "success_rate_grade_snapshot" field.
func SuccessRateGradeSnapshotHasSuffix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasSuffix(FieldSuccessRateGradeSnapshot, v))
}

// SuccessRateGradeSnapshotEqualFold applies the EqualFold predicate on the "success_rate_grade_snapshot" field.
func SuccessRateGradeSnapshotEqualFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEqualFold(FieldSuccessRateGradeSnapshot, v))
}

// SuccessRateGradeSnapshotContainsFold applies the ContainsFold predicate on the "success_rate_grade_snapshot" field.
func SuccessRateGradeSnapshotContainsFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContainsFold(FieldSuccessRateGradeSnapshot, v))
}

// RefundPolicySnapshotEQ applies the EQ predicate on the "refund_policy_snapshot" field.
func RefundPolicySnapshotEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldRefundPolicySnapshot, v))
}

// RefundPolicySnapshotNEQ applies the NEQ predicate on the "refund_policy_snapshot" field.
func RefundPolicySnapshotNEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldRefundPolicySnapshot, v))
}

// RefundPolicySnapshotIn applies the In predicate on the "refund_policy_snapshot" field.
func RefundPolicySnapshotIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldRefundPolicySnapshot, vs...))
}

// RefundPolicySnapshotNotIn applies the NotIn predicate on the "refund_policy_snapshot" field.
func RefundPolicySnapshotNotIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldRefundPolicySnapshot, vs...))
}

// RefundPolicySnapshotGT applies the GT predicate on the "refund_policy_snapshot" field.
func RefundPolicySnapshotGT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldRefundPolicySnapshot, v))
}

// RefundPolicySnapshotGTE applies the GTE predicate on the "refund_policy_snapshot" field.
func RefundPolicySnapshotGTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldRefundPolicySnapshot, v))
}

// RefundPolicySnapshotLT applies the LT predicate on the "refund_policy_snapshot" field.
func RefundPolicySnapshotLT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldRefundPolicySnapshot, v))
}

// RefundPolicySnapshotLTE applies the LTE predicate on the "refund_policy_snapshot" field.
func RefundPolicySnapshotLTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldRefundPolicySnapshot, v))
}

// RefundPolicySnapshotContains applies the Contains predicate on the "refund_policy_snapshot" field.
func RefundPolicySnapshotContains(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContains(FieldRefundPolicySnapshot, v))
}

// RefundPolicySnapshotHasPrefix applies the HasPrefix predicate on the "refund_policy_snapshot" field.
func RefundPolicySnapshotHasPrefix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasPrefix(FieldRefundPolicySnapshot, v))
}

// RefundPolicySnapshotHasSuffix applies the HasSuffix predicate on the "refund_policy_snapshot" field.
func RefundPolicySnapshotHasSuffix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasSuffix(FieldRefundPolicySnapshot, v))
}

// RefundPolicySnapshotEqualFold applies the EqualFold predicate on the "refund_policy_snapshot" field.
func RefundPolicySnapshotEqualFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEqualFold(FieldRefundPolicySnapshot, v))
}

// RefundPolicySnapshotContainsFold applies the ContainsFold predicate on the "refund_policy_snapshot" field.
func RefundPolicySnapshotContainsFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContainsFold(FieldRefundPolicySnapshot, v))
}

// CapturePolicySnapshotEQ applies the EQ predicate on the "capture_policy_snapshot" field.
func CapturePolicySnapshotEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldCapturePolicySnapshot, v))
}

// CapturePolicySnapshotNEQ applies the NEQ predicate on the "capture_policy_snapshot" field.
func CapturePolicySnapshotNEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldCapturePolicySnapshot, v))
}

// CapturePolicySnapshotIn applies the In predicate on the "capture_policy_snapshot" field.
func CapturePolicySnapshotIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldCapturePolicySnapshot, vs...))
}

// CapturePolicySnapshotNotIn applies the NotIn predicate on the "capture_policy_snapshot" field.
func CapturePolicySnapshotNotIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldCapturePolicySnapshot, vs...))
}

// CapturePolicySnapshotGT applies the GT predicate on the "capture_policy_snapshot" field.
func CapturePolicySnapshotGT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldCapturePolicySnapshot, v))
}

// CapturePolicySnapshotGTE applies the GTE predicate on the "capture_policy_snapshot" field.
func CapturePolicySnapshotGTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldCapturePolicySnapshot, v))
}

// CapturePolicySnapshotLT applies the LT predicate on the "capture_policy_snapshot" field.
func CapturePolicySnapshotLT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldCapturePolicySnapshot, v))
}

// CapturePolicySnapshotLTE applies the LTE predicate on the "capture_policy_snapshot" field.
func CapturePolicySnapshotLTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldCapturePolicySnapshot, v))
}

// CapturePolicySnapshotContains applies the Contains predicate on the "capture_policy_snapshot" field.
func CapturePolicySnapshotContains(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContains(FieldCapturePolicySnapshot, v))
}

// CapturePolicySnapshotHasPrefix applies the HasPrefix predicate on the "capture_policy_snapshot" field.
func CapturePolicySnapshotHasPrefix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasPrefix(FieldCapturePolicySnapshot, v))
}

// CapturePolicySnapshotHasSuffix applies the HasSuffix predicate on the "capture_policy_snapshot" field.
func CapturePolicySnapshotHasSuffix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasSuffix(FieldCapturePolicySnapshot, v))
}

// CapturePolicySnapshotEqualFold applies the EqualFold predicate on the "capture_policy_snapshot" field.
func CapturePolicySnapshotEqualFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEqualFold(FieldCapturePolicySnapshot, v))
}

// CapturePolicySnapshotContainsFold applies the ContainsFold predicate on the "capture_policy_snapshot" field.
func CapturePolicySnapshotContainsFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContainsFold(FieldCapturePolicySnapshot, v))
}

// ReservedAmountEQ applies the EQ predicate on the "reserved_amount" field.
func ReservedAmountEQ(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldReservedAmount, v))
}

// ReservedAmountNEQ applies the NEQ predicate on the "reserved_amount" field.
func ReservedAmountNEQ(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldReservedAmount, v))
}

// ReservedAmountIn applies the In predicate on the "reserved_amount" field.
func ReservedAmountIn(vs ...float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldReservedAmount, vs...))
}

// ReservedAmountNotIn applies the NotIn predicate on the "reserved_amount" field.
func ReservedAmountNotIn(vs ...float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldReservedAmount, vs...))
}

// ReservedAmountGT applies the GT predicate on the "reserved_amount" field.
func ReservedAmountGT(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldReservedAmount, v))
}

// ReservedAmountGTE applies the GTE predicate on the "reserved_amount" field.
func ReservedAmountGTE(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldReservedAmount, v))
}

// ReservedAmountLT applies the LT predicate on the "reserved_amount" field.
func ReservedAmountLT(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldReservedAmount, v))
}

// ReservedAmountLTE applies the LTE predicate on the "reserved_amount" field.
func ReservedAmountLTE(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldReservedAmount, v))
}

// CapturedAmountEQ applies the EQ predicate on the "captured_amount" field.
func CapturedAmountEQ(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldCapturedAmount, v))
}

// CapturedAmountNEQ applies the NEQ predicate on the "captured_amount" field.
func CapturedAmountNEQ(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldCapturedAmount, v))
}

// CapturedAmountIn applies the In predicate on the "captured_amount" field.
func CapturedAmountIn(vs ...float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldCapturedAmount, vs...))
}

// CapturedAmountNotIn applies the NotIn predicate on the "captured_amount" field.
func CapturedAmountNotIn(vs ...float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldCapturedAmount, vs...))
}

// CapturedAmountGT applies the GT predicate on the "captured_amount" field.
func CapturedAmountGT(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldCapturedAmount, v))
}

// CapturedAmountGTE applies the GTE predicate on the "captured_amount" field.
func CapturedAmountGTE(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldCapturedAmount, v))
}

// CapturedAmountLT applies the LT predicate on the "captured_amount" field.
func CapturedAmountLT(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldCapturedAmount, v))
}

// CapturedAmountLTE applies the LTE predicate on the "captured_amount" field.
func CapturedAmountLTE(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldCapturedAmount, v))
}

// ReleasedAmountEQ applies the EQ predicate on the "released_amount" field.
func ReleasedAmountEQ(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldReleasedAmount, v))
}

// ReleasedAmountNEQ applies the NEQ predicate on the "released_amount" field.
func ReleasedAmountNEQ(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldReleasedAmount, v))
}

// ReleasedAmountIn applies the In predicate on the "released_amount" field.
func ReleasedAmountIn(vs ...float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldReleasedAmount, vs...))
}

// ReleasedAmountNotIn applies the NotIn predicate on the "released_amount" field.
func ReleasedAmountNotIn(vs ...float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldReleasedAmount, vs...))
}

// ReleasedAmountGT applies the GT predicate on the "released_amount" field.
func ReleasedAmountGT(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldReleasedAmount, v))
}

// ReleasedAmountGTE applies the GTE predicate on the "released_amount" field.
func ReleasedAmountGTE(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldReleasedAmount, v))
}

// ReleasedAmountLT applies the LT predicate on the "released_amount" field.
func ReleasedAmountLT(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldReleasedAmount, v))
}

// ReleasedAmountLTE applies the LTE predicate on the "released_amount" field.
func ReleasedAmountLTE(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldReleasedAmount, v))
}

// RefundedAmountEQ applies the EQ predicate on the "refunded_amount" field.
func RefundedAmountEQ(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldRefundedAmount, v))
}

// RefundedAmountNEQ applies the NEQ predicate on the "refunded_amount" field.
func RefundedAmountNEQ(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldRefundedAmount, v))
}

// RefundedAmountIn applies the In predicate on the "refunded_amount" field.
func RefundedAmountIn(vs ...float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldRefundedAmount, vs...))
}

// RefundedAmountNotIn applies the NotIn predicate on the "refunded_amount" field.
func RefundedAmountNotIn(vs ...float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldRefundedAmount, vs...))
}

// RefundedAmountGT applies the GT predicate on the "refunded_amount" field.
func RefundedAmountGT(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldRefundedAmount, v))
}

// RefundedAmountGTE applies the GTE predicate on the "refunded_amount" field.
func RefundedAmountGTE(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldRefundedAmount, v))
}

// RefundedAmountLT applies the LT predicate on the "refunded_amount" field.
func RefundedAmountLT(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldRefundedAmount, v))
}

// RefundedAmountLTE applies the LTE predicate on the "refunded_amount" field.
func RefundedAmountLTE(v float64) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldRefundedAmount, v))
}

// InboxCreatedAtEQ applies the EQ predicate on the "inbox_created_at" field.
func InboxCreatedAtEQ(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldInboxCreatedAt, v))
}

// InboxCreatedAtNEQ applies the NEQ predicate on the "inbox_created_at" field.
func InboxCreatedAtNEQ(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldInboxCreatedAt, v))
}

// InboxCreatedAtIn applies the In predicate on the "inbox_created_at" field.
func InboxCreatedAtIn(vs ...time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldInboxCreatedAt, vs...))
}

// InboxCreatedAtNotIn applies the NotIn predicate on the "inbox_created_at" field.
func InboxCreatedAtNotIn(vs ...time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldInboxCreatedAt, vs...))
}

// InboxCreatedAtGT applies the GT predicate on the "inbox_created_at" field.
func InboxCreatedAtGT(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldInboxCreatedAt, v))
}

// InboxCreatedAtGTE applies the GTE predicate on the "inbox_created_at" field.
func InboxCreatedAtGTE(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldInboxCreatedAt, v))
}

// InboxCreatedAtLT applies the LT predicate on the "inbox_created_at" field.
func InboxCreatedAtLT(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldInboxCreatedAt, v))
}

// InboxCreatedAtLTE applies the LTE predicate on the "inbox_created_at" field.
func InboxCreatedAtLTE(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldInboxCreatedAt, v))
}

// InboxCreatedAtIsNil applies the IsNil predicate on the "inbox_created_at" field.
func InboxCreatedAtIsNil() predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIsNull(FieldInboxCreatedAt))
}

// InboxCreatedAtNotNil applies the NotNil predicate on the "inbox_created_at" field.
func InboxCreatedAtNotNil() predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotNull(FieldInboxCreatedAt))
}

// WaitingStartedAtEQ applies the EQ predicate on the "waiting_started_at" field.
func WaitingStartedAtEQ(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldWaitingStartedAt, v))
}

// WaitingStartedAtNEQ applies the NEQ predicate on the "waiting_started_at" field.
func WaitingStartedAtNEQ(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldWaitingStartedAt, v))
}

// WaitingStartedAtIn applies the In predicate on the "waiting_started_at" field.
func WaitingStartedAtIn(vs ...time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldWaitingStartedAt, vs...))
}

// WaitingStartedAtNotIn applies the NotIn predicate on the "waiting_started_at" field.
func WaitingStartedAtNotIn(vs ...time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldWaitingStartedAt, vs...))
}

// WaitingStartedAtGT applies the GT predicate on the "waiting_started_at" field.
func WaitingStartedAtGT(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldWaitingStartedAt, v))
}

// WaitingStartedAtGTE applies the GTE predicate on the "waiting_started_at" field.
func WaitingStartedAtGTE(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldWaitingStartedAt, v))
}

// WaitingStartedAtLT applies the LT predicate on the "waiting_started_at" field.
func WaitingStartedAtLT(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldWaitingStartedAt, v))
}

// WaitingStartedAtLTE applies the LTE predicate on the "waiting_started_at" field.
func WaitingStartedAtLTE(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldWaitingStartedAt, v))
}

// WaitingStartedAtIsNil applies the IsNil predicate on the "waiting_started_at" field.
func WaitingStartedAtIsNil() predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIsNull(FieldWaitingStartedAt))
}

// WaitingStartedAtNotNil applies the NotNil predicate on the "waiting_started_at" field.
func WaitingStartedAtNotNil() predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotNull(FieldWaitingStartedAt))
}

// FirstMessageAtEQ applies the EQ predicate on the "first_message_at" field.
func FirstMessageAtEQ(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldFirstMessageAt, v))
}

// FirstMessageAtNEQ applies the NEQ predicate on the "first_message_at" field.
func FirstMessageAtNEQ(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldFirstMessageAt, v))
}

// FirstMessageAtIn applies the In predicate on the "first_message_at" field.
func FirstMessageAtIn(vs ...time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldFirstMessageAt, vs...))
}

// FirstMessageAtNotIn applies the NotIn predicate on the "first_message_at" field.
func FirstMessageAtNotIn(vs ...time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldFirstMessageAt, vs...))
}

// FirstMessageAtGT applies the GT predicate on the "first_message_at" field.
func FirstMessageAtGT(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldFirstMessageAt, v))
}

// FirstMessageAtGTE applies the GTE predicate on the "first_message_at" field.
func FirstMessageAtGTE(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldFirstMessageAt, v))
}

// FirstMessageAtLT applies the LT predicate on the "first_message_at" field.
func FirstMessageAtLT(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldFirstMessageAt, v))
}

// FirstMessageAtLTE applies the LTE predicate on the "first_message_at" field.
func FirstMessageAtLTE(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldFirstMessageAt, v))
}

// FirstMessageAtIsNil applies the IsNil predicate on the "first_message_at" field.
func FirstMessageAtIsNil() predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIsNull(FieldFirstMessageAt))
}

// FirstMessageAtNotNil applies the NotNil predicate on the "first_message_at" field.
func FirstMessageAtNotNil() predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotNull(FieldFirstMessageAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotNull(FieldCompletedAt))
}

// CancelledAtEQ applies the EQ predicate on the "cancelled_at" field.
func CancelledAtEQ(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldCancelledAt, v))
}

// CancelledAtNEQ applies the NEQ predicate on the "cancelled_at" field.
func CancelledAtNEQ(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldCancelledAt, v))
}

// CancelledAtIn applies the In predicate on the "cancelled_at" field.
func CancelledAtIn(vs ...time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldCancelledAt, vs...))
}

// CancelledAtNotIn applies the NotIn predicate on the "cancelled_at" field.
func CancelledAtNotIn(vs ...time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldCancelledAt, vs...))
}

// CancelledAtGT applies the GT predicate on the "cancelled_at" field.
func CancelledAtGT(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldCancelledAt, v))
}

// CancelledAtGTE applies the GTE predicate on the "cancelled_at" field.
func CancelledAtGTE(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldCancelledAt, v))
}

// CancelledAtLT applies the LT predicate on the "cancelled_at" field.
func CancelledAtLT(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldCancelledAt, v))
}

// CancelledAtLTE applies the LTE predicate on the "cancelled_at" field.
func CancelledAtLTE(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldCancelledAt, v))
}

// CancelledAtIsNil applies the IsNil predicate on the "cancelled_at" field.
func CancelledAtIsNil() predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIsNull(FieldCancelledAt))
}

// CancelledAtNotNil applies the NotNil predicate on the "cancelled_at" field.
func CancelledAtNotNil() predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotNull(FieldCancelledAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotNull(FieldExpiresAt))
}

// PollCountEQ applies the EQ predicate on the "poll_count" field.
func PollCountEQ(v int) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldPollCount, v))
}

// PollCountNEQ applies the NEQ predicate on the "poll_count" field.
func PollCountNEQ(v int) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldPollCount, v))
}

// PollCountIn applies the In predicate on the "poll_count" field.
func PollCountIn(vs ...int) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldPollCount, vs...))
}

// PollCountNotIn applies the NotIn predicate on the "poll_count" field.
func PollCountNotIn(vs ...int) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldPollCount, vs...))
}

// PollCountGT applies the GT predicate on the "poll_count" field.
func PollCountGT(v int) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldPollCount, v))
}

// PollCountGTE applies the GTE predicate on the "poll_count" field.
func PollCountGTE(v int) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldPollCount, v))
}

// PollCountLT applies the LT predicate on the "poll_count" field.
func PollCountLT(v int) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldPollCount, v))
}

// PollCountLTE applies the LTE predicate on the "poll_count" field.
func PollCountLTE(v int) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldPollCount, v))
}

// NextPollAtEQ applies the EQ predicate on the "next_poll_at" field.
func NextPollAtEQ(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldNextPollAt, v))
}

// NextPollAtNEQ applies the NEQ predicate on the "next_poll_at" field.
func NextPollAtNEQ(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldNextPollAt, v))
}

// NextPollAtIn applies the In predicate on the "next_poll_at" field.
func NextPollAtIn(vs ...time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldNextPollAt, vs...))
}

// NextPollAtNotIn applies the NotIn predicate on the "next_poll_at" field.
func NextPollAtNotIn(vs ...time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldNextPollAt, vs...))
}

// NextPollAtGT applies the GT predicate on the "next_poll_at" field.
func NextPollAtGT(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldNextPollAt, v))
}

// NextPollAtGTE applies the GTE predicate on the "next_poll_at" field.
func NextPollAtGTE(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldNextPollAt, v))
}

// NextPollAtLT applies the LT predicate on the "next_poll_at" field.
func NextPollAtLT(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldNextPollAt, v))
}

// NextPollAtLTE applies the LTE predicate on the "next_poll_at" field.
func NextPollAtLTE(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldNextPollAt, v))
}

// NextPollAtIsNil applies the IsNil predicate on the "next_poll_at" field.
func NextPollAtIsNil() predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIsNull(FieldNextPollAt))
}

// NextPollAtNotNil applies the NotNil predicate on the "next_poll_at" field.
func NextPollAtNotNil() predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotNull(FieldNextPollAt))
}

// LastPolledAtEQ applies the EQ predicate on the "last_polled_at" field.
func LastPolledAtEQ(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldLastPolledAt, v))
}

// LastPolledAtNEQ applies the NEQ predicate on the "last_polled_at" field.
func LastPolledAtNEQ(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldLastPolledAt, v))
}

// LastPolledAtIn applies the In predicate on the "last_polled_at" field.
func LastPolledAtIn(vs ...time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldLastPolledAt, vs...))
}

// LastPolledAtNotIn applies the NotIn predicate on the "last_polled_at" field.
func LastPolledAtNotIn(vs ...time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldLastPolledAt, vs...))
}

// LastPolledAtGT applies the GT predicate on the "last_polled_at" field.
func LastPolledAtGT(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldLastPolledAt, v))
}

// LastPolledAtGTE applies the GTE predicate on the "last_polled_at" field.
func LastPolledAtGTE(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldLastPolledAt, v))
}

// LastPolledAtLT applies the LT predicate on the "last_polled_at" field.
func LastPolledAtLT(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldLastPolledAt, v))
}

// LastPolledAtLTE applies the LTE predicate on the "last_polled_at" field.
func LastPolledAtLTE(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldLastPolledAt, v))
}

// LastPolledAtIsNil applies the IsNil predicate on the "last_polled_at" field.
func LastPolledAtIsNil() predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIsNull(FieldLastPolledAt))
}

// LastPolledAtNotNil applies the NotNil predicate on the "last_polled_at" field.
func LastPolledAtNotNil() predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotNull(FieldLastPolledAt))
}

// ProviderRequestCountEQ applies the EQ predicate on the "provider_request_count" field.
func ProviderRequestCountEQ(v int) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldProviderRequestCount, v))
}

// ProviderRequestCountNEQ applies the NEQ predicate on the "provider_request_count" field.
func ProviderRequestCountNEQ(v int) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldProviderRequestCount, v))
}

// ProviderRequestCountIn applies the In predicate on the "provider_request_count" field.
func ProviderRequestCountIn(vs ...int) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldProviderRequestCount, vs...))
}

// ProviderRequestCountNotIn applies the NotIn predicate on the "provider_request_count" field.
func ProviderRequestCountNotIn(vs ...int) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldProviderRequestCount, vs...))
}

// ProviderRequestCountGT applies the GT predicate on the "provider_request_count" field.
func ProviderRequestCountGT(v int) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldProviderRequestCount, v))
}

// ProviderRequestCountGTE applies the GTE predicate on the "provider_request_count" field.
func ProviderRequestCountGTE(v int) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldProviderRequestCount, v))
}

// ProviderRequestCountLT applies the LT predicate on the "provider_request_count" field.
func ProviderRequestCountLT(v int) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldProviderRequestCount, v))
}

// ProviderRequestCountLTE applies the LTE predicate on the "provider_request_count" field.
func ProviderRequestCountLTE(v int) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldProviderRequestCount, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContainsFold(FieldErrorCode, v))
}

// ErrorPublicMessageEQ applies the EQ predicate on the "error_public_message" field.
func ErrorPublicMessageEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldErrorPublicMessage, v))
}

// ErrorPublicMessageNEQ applies the NEQ predicate on the "error_public_message" field.
func ErrorPublicMessageNEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldErrorPublicMessage, v))
}

// ErrorPublicMessageIn applies the In predicate on the "error_public_message" field.
func ErrorPublicMessageIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldErrorPublicMessage, vs...))
}

// ErrorPublicMessageNotIn applies the NotIn predicate on the "error_public_message" field.
func ErrorPublicMessageNotIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldErrorPublicMessage, vs...))
}

// ErrorPublicMessageGT applies the GT predicate on the "error_public_message" field.
func ErrorPublicMessageGT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldErrorPublicMessage, v))
}

// ErrorPublicMessageGTE applies the GTE predicate on the "error_public_message" field.
func ErrorPublicMessageGTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldErrorPublicMessage, v))
}

// ErrorPublicMessageLT applies the LT predicate on the "error_public_message" field.
func ErrorPublicMessageLT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldErrorPublicMessage, v))
}

// ErrorPublicMessageLTE applies the LTE predicate on the "error_public_message" field.
func ErrorPublicMessageLTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldErrorPublicMessage, v))
}

// ErrorPublicMessageContains applies the Contains predicate on the "error_public_message" field.
func ErrorPublicMessageContains(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContains(FieldErrorPublicMessage, v))
}

// ErrorPublicMessageHasPrefix applies the HasPrefix predicate on the "error_public_message" field.
func ErrorPublicMessageHasPrefix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasPrefix(FieldErrorPublicMessage, v))
}

// ErrorPublicMessageHasSuffix applies the HasSuffix predicate on the "error_public_message" field.
func ErrorPublicMessageHasSuffix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasSuffix(FieldErrorPublicMessage, v))
}

// ErrorPublicMessageEqualFold applies the EqualFold predicate on the "error_public_message" field.
func ErrorPublicMessageEqualFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEqualFold(FieldErrorPublicMessage, v))
}

// ErrorPublicMessageContainsFold applies the ContainsFold predicate on the "error_public_message" field.
func ErrorPublicMessageContainsFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContainsFold(FieldErrorPublicMessage, v))
}

// ErrorAdminMessageEQ applies the EQ predicate on the "error_admin_message" field.
func ErrorAdminMessageEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldErrorAdminMessage, v))
}

// ErrorAdminMessageNEQ applies the NEQ predicate on the "error_admin_message" field.
func ErrorAdminMessageNEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldErrorAdminMessage, v))
}

// ErrorAdminMessageIn applies the In predicate on the "error_admin_message" field.
func ErrorAdminMessageIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldErrorAdminMessage, vs...))
}

// ErrorAdminMessageNotIn applies the NotIn predicate on the "error_admin_message" field.
func ErrorAdminMessageNotIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldErrorAdminMessage, vs...))
}

// ErrorAdminMessageGT applies the GT predicate on the "error_admin_message" field.
func ErrorAdminMessageGT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldErrorAdminMessage, v))
}

// ErrorAdminMessageGTE applies the GTE predicate on the "error_admin_message" field.
func ErrorAdminMessageGTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldErrorAdminMessage, v))
}

// ErrorAdminMessageLT applies the LT predicate on the "error_admin_message" field.
func ErrorAdminMessageLT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldErrorAdminMessage, v))
}

// ErrorAdminMessageLTE applies the LTE predicate on the "error_admin_message" field.
func ErrorAdminMessageLTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldErrorAdminMessage, v))
}

// ErrorAdminMessageContains applies the Contains predicate on the "error_admin_message" field.
func ErrorAdminMessageContains(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContains(FieldErrorAdminMessage, v))
}

// ErrorAdminMessageHasPrefix applies the HasPrefix predicate on the "error_admin_message" field.
func ErrorAdminMessageHasPrefix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasPrefix(FieldErrorAdminMessage, v))
}

// ErrorAdminMessageHasSuffix applies the HasSuffix predicate on the "error_admin_message" field.
func ErrorAdminMessageHasSuffix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasSuffix(FieldErrorAdminMessage, v))
}

// ErrorAdminMessageEqualFold applies the EqualFold predicate on the "error_admin_message" field.
func ErrorAdminMessageEqualFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEqualFold(FieldErrorAdminMessage, v))
}

// ErrorAdminMessageContainsFold applies the ContainsFold predicate on the "error_admin_message" field.
func ErrorAdminMessageContainsFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContainsFold(FieldErrorAdminMessage, v))
}

// RefundStatusEQ applies the EQ predicate on the "refund_status" field.
func RefundStatusEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldRefundStatus, v))
}

// RefundStatusNEQ applies the NEQ predicate on the "refund_status" field.
func RefundStatusNEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldRefundStatus, v))
}

// RefundStatusIn applies the In predicate on the "refund_status" field.
func RefundStatusIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldRefundStatus, vs...))
}

// RefundStatusNotIn applies the NotIn predicate on the "refund_status" field.
func RefundStatusNotIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldRefundStatus, vs...))
}

// RefundStatusGT applies the GT predicate on the "refund_status" field.
func RefundStatusGT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldRefundStatus, v))
}

// RefundStatusGTE applies the GTE predicate on the "refund_status" field.
func RefundStatusGTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldRefundStatus, v))
}

// RefundStatusLT applies the LT predicate on the "refund_status" field.
func RefundStatusLT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldRefundStatus, v))
}

// RefundStatusLTE applies the LTE predicate on the "refund_status" field.
func RefundStatusLTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldRefundStatus, v))
}

// RefundStatusContains applies the Contains predicate on the "refund_status" field.
func RefundStatusContains(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContains(FieldRefundStatus, v))
}

// RefundStatusHasPrefix applies the HasPrefix predicate on the "refund_status" field.
func RefundStatusHasPrefix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasPrefix(FieldRefundStatus, v))
}

// RefundStatusHasSuffix applies the HasSuffix predicate on the "refund_status" field.
func RefundStatusHasSuffix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasSuffix(FieldRefundStatus, v))
}

// RefundStatusEqualFold applies the EqualFold predicate on the "refund_status" field.
func RefundStatusEqualFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEqualFold(FieldRefundStatus, v))
}

// RefundStatusContainsFold applies the ContainsFold predicate on the "refund_status" field.
func RefundStatusContainsFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContainsFold(FieldRefundStatus, v))
}

// RefundReasonEQ applies the EQ predicate on the "refund_reason" field.
func RefundReasonEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldRefundReason, v))
}

// RefundReasonNEQ applies the NEQ predicate on the "refund_reason" field.
func RefundReasonNEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldRefundReason, v))
}

// RefundReasonIn applies the In predicate on the "refund_reason" field.
func RefundReasonIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldRefundReason, vs...))
}

// RefundReasonNotIn applies the NotIn predicate on the "refund_reason" field.
func RefundReasonNotIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldRefundReason, vs...))
}

// RefundReasonGT applies the GT predicate on the "refund_reason" field.
func RefundReasonGT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldRefundReason, v))
}

// RefundReasonGTE applies the GTE predicate on the "refund_reason" field.
func RefundReasonGTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldRefundReason, v))
}

// RefundReasonLT applies the LT predicate on the "refund_reason" field.
func RefundReasonLT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldRefundReason, v))
}

// RefundReasonLTE applies the LTE predicate on the "refund_reason" field.
func RefundReasonLTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldRefundReason, v))
}

// RefundReasonContains applies the Contains predicate on the "refund_reason" field.
func RefundReasonContains(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContains(FieldRefundReason, v))
}

// RefundReasonHasPrefix applies the HasPrefix predicate on the "refund_reason" field.
func RefundReasonHasPrefix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasPrefix(FieldRefundReason, v))
}

// RefundReasonHasSuffix applies the HasSuffix predicate on the "refund_reason" field.
func RefundReasonHasSuffix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasSuffix(FieldRefundReason, v))
}

// RefundReasonEqualFold applies the EqualFold predicate on the "refund_reason" field.
func RefundReasonEqualFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEqualFold(FieldRefundReason, v))
}

// RefundReasonContainsFold applies the ContainsFold predicate on the "refund_reason" field.
func RefundReasonContainsFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContainsFold(FieldRefundReason, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EmailOrder {
	return predicate.EmailOrder(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EmailOrder) predicate.EmailOrder {
	return predicate.EmailOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EmailOrder) predicate.EmailOrder {
	return predicate.EmailOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EmailOrder) predicate.EmailOrder {
	return predicate.EmailOrder(sql.NotPredicates(p))
}
