-- Additive bounded reads only. Reuse existing due, finished, scope and status
-- indexes. The runner executes concurrent statements outside a transaction.
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_workspace_name_prefix ON workspaces(lower(name) text_pattern_ops,id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_workspace_slug_prefix ON workspaces(lower(slug) text_pattern_ops,id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_workspace_name_order ON workspaces(name,id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_workspace_status ON workspaces(status,id DESC);
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_workspace_type ON workspaces(type,id DESC);
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_workspace_owner ON workspaces(owner_user_id,id DESC);
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_workspace_created ON workspaces(created_at,id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_workspace_updated ON workspaces(updated_at,id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_export_state_created ON workspace_export_jobs(state,created_at DESC,id DESC);
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_export_attention ON workspace_export_jobs(created_at DESC,id DESC) WHERE state IN ('pending','running','failed');
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_export_success ON workspace_export_jobs(completed_at DESC,id) WHERE state IN ('completed','expired') AND completed_at IS NOT NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_purge_state_created ON workspace_deletion_jobs(state,created_at DESC,id DESC);
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_purge_attention ON workspace_deletion_jobs(created_at DESC,id DESC) WHERE state IN ('pending','running','failed','blocked');
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_purge_success ON workspace_deletion_jobs(completed_at DESC,id) WHERE state='completed' AND completed_at IS NOT NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_webhook_scope_created ON workspace_webhook_deliveries(workspace_id,created_at DESC,id DESC);
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_scim_expiry ON workspace_scim_tokens(expires_at,id) WHERE status='active' AND expires_at IS NOT NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_billing_recovered ON billing_settlement_alerts(recovered_at DESC,reservation_id) WHERE state='recovered' AND recovered_at IS NOT NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_objects_scope ON workspace_export_objects(workspace_id,created_at,object_key);
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_active_holds ON workspace_lifecycle_holds(workspace_id,code) WHERE active;
-- Sparse operational populations must not scan historical terminal records.
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_image_attention_global ON batch_image_jobs(created_at,id) WHERE status NOT IN ('completed','failed','cancelled','output_deleted') OR last_error_code='SUBMIT_OUTCOME_UNKNOWN';
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_image_attention_scope ON batch_image_jobs(workspace_id,created_at,id) WHERE status NOT IN ('completed','failed','cancelled','output_deleted') OR last_error_code='SUBMIT_OUTCOME_UNKNOWN';
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_image_errors_global ON batch_image_jobs(updated_at DESC,id) WHERE COALESCE(last_error_code,'')<>'';
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_outbox_claims ON domain_event_outbox(locked_until,event_id) WHERE delivered_at IS NULL AND locked_until IS NOT NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_outbox_retry ON domain_event_outbox(available_at DESC,event_id) WHERE delivered_at IS NULL AND last_error IS NOT NULL AND last_error<>'';
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_outbox_pending_created ON domain_event_outbox(created_at,event_id) WHERE delivered_at IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_webhook_claims ON workspace_webhook_deliveries(locked_at,workspace_id,id) WHERE status='delivering';
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_webhook_pending_created ON workspace_webhook_deliveries(created_at,workspace_id,id) INCLUDE(status,webhook_id) WHERE status IN ('pending','retrying','delivering');
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_webhook_dead_scope ON workspace_webhook_deliveries(workspace_id,finished_at DESC,id DESC) WHERE status='dead' AND finished_at IS NOT NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_finops_pending_scope ON finops_anomaly_detection_leases(workspace_id,bucket_start,claimed_until) WHERE completed_at IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_finops_errors_global ON finops_anomaly_detection_leases(updated_at DESC,workspace_id) WHERE completed_at IS NULL AND COALESCE(last_error_code,'')<>'';
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_export_claims ON workspace_export_jobs(lease_expires_at,workspace_id,id) WHERE state='running';
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_export_pending_created ON workspace_export_jobs(created_at,workspace_id,id) WHERE state IN ('pending','running');
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_export_errors_global ON workspace_export_jobs(updated_at DESC,id) WHERE failure_code<>'';
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_purge_claims ON workspace_deletion_jobs(lease_expires_at,workspace_id,id) WHERE state='running';
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_purge_pending_created ON workspace_deletion_jobs(created_at,workspace_id,id) WHERE state IN ('pending','running','blocked');
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_purge_errors_global ON workspace_deletion_jobs(updated_at DESC,id) WHERE failure_code<>'';
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_scim_errors_global ON workspace_scim_connectors(updated_at DESC,id) WHERE failure_count>0;
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_members_scope_state ON workspace_members(workspace_id,status,id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_members_state ON workspace_members(status,id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_projects_scope_state ON projects(workspace_id,status,id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_projects_state ON projects(status,id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_service_accounts_scope_state ON service_accounts(workspace_id,status,id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_service_accounts_state ON service_accounts(status,id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_identity_state ON workspace_identity_providers(status,id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_scim_state ON workspace_scim_connectors(status,id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_scim_scope_state ON workspace_scim_connectors(workspace_id,status,id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_budget_pending_scope ON budget_reservations(workspace_id,id) WHERE status='pending';
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_webhook_scope_due ON workspace_webhook_deliveries(workspace_id,next_attempt_at,created_at,id) WHERE status IN ('pending','retrying','delivering');
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_webhook_success_scope ON workspace_webhook_deliveries(workspace_id,finished_at DESC,id DESC) WHERE status='succeeded' AND finished_at IS NOT NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_purge_eligibility ON workspace_deletion_jobs(GREATEST(available_at,earliest_purge_at),workspace_id,id) WHERE state IN ('pending','running','blocked');
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_purge_cooling ON workspace_deletion_jobs(GREATEST(earliest_purge_at,available_at),workspace_id,id) WHERE state='pending';
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_billing_state ON billing_settlement_alerts(state,pending_at,reservation_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_image_success_global ON batch_image_jobs(finished_at DESC,id) WHERE status='completed' AND finished_at IS NOT NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_budget_reserved ON budget_counters(scope_type,scope_id,period_start) WHERE reserved<>0;
CREATE INDEX CONCURRENTLY IF NOT EXISTS enterprise_admin_findings_scope_state ON finops_anomaly_findings(workspace_id,status,id);
