// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/emailmessage"
)

// EmailMessageCreate is the builder for creating a EmailMessage entity.
type EmailMessageCreate struct {
	config
	mutation *EmailMessageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetEmailOrderID sets the "email_order_id" field.
func (_c *EmailMessageCreate) SetEmailOrderID(v int64) *EmailMessageCreate {
	_c.mutation.SetEmailOrderID(v)
	return _c
}

// SetProviderMessageID sets the "provider_message_id" field.
func (_c *EmailMessageCreate) SetProviderMessageID(v string) *EmailMessageCreate {
	_c.mutation.SetProviderMessageID(v)
	return _c
}

// SetNillableProviderMessageID sets the "provider_message_id" field if the given value is not nil.
func (_c *EmailMessageCreate) SetNillableProviderMessageID(v *string) *EmailMessageCreate {
	if v != nil {
		_c.SetProviderMessageID(*v)
	}
	return _c
}

// SetFromAddress sets the "from_address" field.
func (_c *EmailMessageCreate) SetFromAddress(v string) *EmailMessageCreate {
	_c.mutation.SetFromAddress(v)
	return _c
}

// SetNillableFromAddress sets the "from_address" field if the given value is not nil.
func (_c *EmailMessageCreate) SetNillableFromAddress(v *string) *EmailMessageCreate {
	if v != nil {
		_c.SetFromAddress(*v)
	}
	return _c
}

// SetFromName sets the "from_name" field.
func (_c *EmailMessageCreate) SetFromName(v string) *EmailMessageCreate {
	_c.mutation.SetFromName(v)
	return _c
}

// SetNillableFromName sets the "from_name" field if the given value is not nil.
func (_c *EmailMessageCreate) SetNillableFromName(v *string) *EmailMessageCreate {
	if v != nil {
		_c.SetFromName(*v)
	}
	return _c
}

// SetToAddress sets the "to_address" field.
func (_c *EmailMessageCreate) SetToAddress(v string) *EmailMessageCreate {
	_c.mutation.SetToAddress(v)
	return _c
}

// SetNillableToAddress sets the "to_address" field if the given value is not nil.
func (_c *EmailMessageCreate) SetNillableToAddress(v *string) *EmailMessageCreate {
	if v != nil {
		_c.SetToAddress(*v)
	}
	return _c
}

// SetSubject sets the "subject" field.
func (_c *EmailMessageCreate) SetSubject(v string) *EmailMessageCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_c *EmailMessageCreate) SetNillableSubject(v *string) *EmailMessageCreate {
	if v != nil {
		_c.SetSubject(*v)
	}
	return _c
}

// SetTextBody sets the "text_body" field.
func (_c *EmailMessageCreate) SetTextBody(v string) *EmailMessageCreate {
	_c.mutation.SetTextBody(v)
	return _c
}

// SetNillableTextBody sets the "text_body" field if the given value is not nil.
func (_c *EmailMessageCreate) SetNillableTextBody(v *string) *EmailMessageCreate {
	if v != nil {
		_c.SetTextBody(*v)
	}
	return _c
}

// SetHTMLBody sets the "html_body" field.
func (_c *EmailMessageCreate) SetHTMLBody(v string) *EmailMessageCreate {
	_c.mutation.SetHTMLBody(v)
	return _c
}

// SetNillableHTMLBody sets the "html_body" field if the given value is not nil.
func (_c *EmailMessageCreate) SetNillableHTMLBody(v *string) *EmailMessageCreate {
	if v != nil {
		_c.SetHTMLBody(*v)
	}
	return _c
}

// SetVerificationCode sets the "verification_code" field.
func (_c *EmailMessageCreate) SetVerificationCode(v string) *EmailMessageCreate {
	_c.mutation.SetVerificationCode(v)
	return _c
}

// SetNillableVerificationCode sets the "verification_code" field if the given value is not nil.
func (_c *EmailMessageCreate) SetNillableVerificationCode(v *string) *EmailMessageCreate {
	if v != nil {
		_c.SetVerificationCode(*v)
	}
	return _c
}

// SetVerificationURL sets the "verification_url" field.
func (_c *EmailMessageCreate) SetVerificationURL(v string) *EmailMessageCreate {
	_c.mutation.SetVerificationURL(v)
	return _c
}

// SetNillableVerificationURL sets the "verification_url" field if the given value is not nil.
func (_c *EmailMessageCreate) SetNillableVerificationURL(v *string) *EmailMessageCreate {
	if v != nil {
		_c.SetVerificationURL(*v)
	}
	return _c
}

// SetVerificationConfidence sets the "verification_confidence" field.
func (_c *EmailMessageCreate) SetVerificationConfidence(v float64) *EmailMessageCreate {
	_c.mutation.SetVerificationConfidence(v)
	return _c
}

// SetNillableVerificationConfidence sets the "verification_confidence" field if the given value is not nil.
func (_c *EmailMessageCreate) SetNillableVerificationConfidence(v *float64) *EmailMessageCreate {
	if v != nil {
		_c.SetVerificationConfidence(*v)
	}
	return _c
}

// SetVerificationMethod sets the "verification_method" field.
func (_c *EmailMessageCreate) SetVerificationMethod(v string) *EmailMessageCreate {
	_c.mutation.SetVerificationMethod(v)
	return _c
}

// SetNillableVerificationMethod sets the "verification_method" field if the given value is not nil.
func (_c *EmailMessageCreate) SetNillableVerificationMethod(v *string) *EmailMessageCreate {
	if v != nil {
		_c.SetVerificationMethod(*v)
	}
	return _c
}

// SetReceivedAt sets the "received_at" field.
func (_c *EmailMessageCreate) SetReceivedAt(v time.Time) *EmailMessageCreate {
	_c.mutation.SetReceivedAt(v)
	return _c
}

// SetDedupeHash sets the "dedupe_hash" field.
func (_c *EmailMessageCreate) SetDedupeHash(v string) *EmailMessageCreate {
	_c.mutation.SetDedupeHash(v)
	return _c
}

// SetRawPayload sets the "raw_payload" field.
func (_c *EmailMessageCreate) SetRawPayload(v map[string]interface{}) *EmailMessageCreate {
	_c.mutation.SetRawPayload(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EmailMessageCreate) SetCreatedAt(v time.Time) *EmailMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EmailMessageCreate) SetUpdatedAt(v time.Time) *EmailMessageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// Mutation returns the EmailMessageMutation object of the builder.
func (_c *EmailMessageCreate) Mutation() *EmailMessageMutation {
	return _c.mutation
}

// Save creates the EmailMessage in the database.
func (_c *EmailMessageCreate) Save(ctx context.Context) (*EmailMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EmailMessageCreate) SaveX(ctx context.Context) *EmailMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EmailMessageCreate) defaults() {
	if _, ok := _c.mutation.ProviderMessageID(); !ok {
		v := emailmessage.DefaultProviderMessageID
		_c.mutation.SetProviderMessageID(v)
	}
	if _, ok := _c.mutation.FromAddress(); !ok {
		v := emailmessage.DefaultFromAddress
		_c.mutation.SetFromAddress(v)
	}
	if _, ok := _c.mutation.FromName(); !ok {
		v := emailmessage.DefaultFromName
		_c.mutation.SetFromName(v)
	}
	if _, ok := _c.mutation.ToAddress(); !ok {
		v := emailmessage.DefaultToAddress
		_c.mutation.SetToAddress(v)
	}
	if _, ok := _c.mutation.Subject(); !ok {
		v := emailmessage.DefaultSubject
		_c.mutation.SetSubject(v)
	}
	if _, ok := _c.mutation.TextBody(); !ok {
		v := emailmessage.DefaultTextBody
		_c.mutation.SetTextBody(v)
	}
	if _, ok := _c.mutation.HTMLBody(); !ok {
		v := emailmessage.DefaultHTMLBody
		_c.mutation.SetHTMLBody(v)
	}
	if _, ok := _c.mutation.VerificationCode(); !ok {
		v := emailmessage.DefaultVerificationCode
		_c.mutation.SetVerificationCode(v)
	}
	if _, ok := _c.mutation.VerificationURL(); !ok {
		v := emailmessage.DefaultVerificationURL
		_c.mutation.SetVerificationURL(v)
	}
	if _, ok := _c.mutation.VerificationConfidence(); !ok {
		v := emailmessage.DefaultVerificationConfidence
		_c.mutation.SetVerificationConfidence(v)
	}
	if _, ok := _c.mutation.VerificationMethod(); !ok {
		v := emailmessage.DefaultVerificationMethod
		_c.mutation.SetVerificationMethod(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EmailMessageCreate) check() error {
	if _, ok := _c.mutation.EmailOrderID(); !ok {
		return &ValidationError{Name: "email_order_id", err: errors.New(`ent: missing required field "EmailMessage.email_order_id"`)}
	}
	if _, ok := _c.mutation.ProviderMessageID(); !ok {
		return &ValidationError{Name: "provider_message_id", err: errors.New(`ent: missing required field "EmailMessage.provider_message_id"`)}
	}
	if v, ok := _c.mutation.ProviderMessageID(); ok {
		if err := emailmessage.ProviderMessageIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_message_id", err: fmt.Errorf(`ent: validator failed for field "EmailMessage.provider_message_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FromAddress(); !ok {
		return &ValidationError{Name: "from_address", err: errors.New(`ent: missing required field "EmailMessage.from_address"`)}
	}
	if v, ok := _c.mutation.FromAddress(); ok {
		if err := emailmessage.FromAddressValidator(v); err != nil {
			return &ValidationError{Name: "from_address", err: fmt.Errorf(`ent: validator failed for field "EmailMessage.from_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FromName(); !ok {
		return &ValidationError{Name: "from_name", err: errors.New(`ent: missing required field "EmailMessage.from_name"`)}
	}
	if v, ok := _c.mutation.FromName(); ok {
		if err := emailmessage.FromNameValidator(v); err != nil {
			return &ValidationError{Name: "from_name", err: fmt.Errorf(`ent: validator failed for field "EmailMessage.from_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ToAddress(); !ok {
		return &ValidationError{Name: "to_address", err: errors.New(`ent: missing required field "EmailMessage.to_address"`)}
	}
	if v, ok := _c.mutation.ToAddress(); ok {
		if err := emailmessage.ToAddressValidator(v); err != nil {
			return &ValidationError{Name: "to_address", err: fmt.Errorf(`ent: validator failed for field "EmailMessage.to_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "EmailMessage.subject"`)}
	}
	if _, ok := _c.mutation.TextBody(); !ok {
		return &ValidationError{Name: "text_body", err: errors.New(`ent: missing required field "EmailMessage.text_body"`)}
	}
	if _, ok := _c.mutation.HTMLBody(); !ok {
		return &ValidationError{Name: "html_body", err: errors.New(`ent: missing required field "EmailMessage.html_body"`)}
	}
	if _, ok := _c.mutation.VerificationCode(); !ok {
		return &ValidationError{Name: "verification_code", err: errors.New(`ent: missing required field "EmailMessage.verification_code"`)}
	}
	if v, ok := _c.mutation.VerificationCode(); ok {
		if err := emailmessage.VerificationCodeValidator(v); err != nil {
			return &ValidationError{Name: "verification_code", err: fmt.Errorf(`ent: validator failed for field "EmailMessage.verification_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VerificationURL(); !ok {
		return &ValidationError{Name: "verification_url", err: errors.New(`ent: missing required field "EmailMessage.verification_url"`)}
	}
	if v, ok := _c.mutation.VerificationURL(); ok {
		if err := emailmessage.VerificationURLValidator(v); err != nil {
			return &ValidationError{Name: "verification_url", err: fmt.Errorf(`ent: validator failed for field "EmailMessage.verification_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VerificationConfidence(); !ok {
		return &ValidationError{Name: "verification_confidence", err: errors.New(`ent: missing required field "EmailMessage.verification_confidence"`)}
	}
	if _, ok := _c.mutation.VerificationMethod(); !ok {
		return &ValidationError{Name: "verification_method", err: errors.New(`ent: missing required field "EmailMessage.verification_method"`)}
	}
	if v, ok := _c.mutation.VerificationMethod(); ok {
		if err := emailmessage.VerificationMethodValidator(v); err != nil {
			return &ValidationError{Name: "verification_method", err: fmt.Errorf(`ent: validator failed for field "EmailMessage.verification_method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReceivedAt(); !ok {
		return &ValidationError{Name: "received_at", err: errors.New(`ent: missing required field "EmailMessage.received_at"`)}
	}
	if _, ok := _c.mutation.DedupeHash(); !ok {
		return &ValidationError{Name: "dedupe_hash", err: errors.New(`ent: missing required field "EmailMessage.dedupe_hash"`)}
	}
	if v, ok := _c.mutation.DedupeHash(); ok {
		if err := emailmessage.DedupeHashValidator(v); err != nil {
			return &ValidationError{Name: "dedupe_hash", err: fmt.Errorf(`ent: validator failed for field "EmailMessage.dedupe_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RawPayload(); !ok {
		return &ValidationError{Name: "raw_payload", err: errors.New(`ent: missing required field "EmailMessage.raw_payload"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EmailMessage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EmailMessage.updated_at"`)}
	}
	return nil
}

func (_c *EmailMessageCreate) sqlSave(ctx context.Context) (*EmailMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EmailMessageCreate) createSpec() (*EmailMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &EmailMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(emailmessage.Table, sqlgraph.NewFieldSpec(emailmessage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.EmailOrderID(); ok {
		_spec.SetField(emailmessage.FieldEmailOrderID, field.TypeInt64, value)
		_node.EmailOrderID = value
	}
	if value, ok := _c.mutation.ProviderMessageID(); ok {
		_spec.SetField(emailmessage.FieldProviderMessageID, field.TypeString, value)
		_node.ProviderMessageID = value
	}
	if value, ok := _c.mutation.FromAddress(); ok {
		_spec.SetField(emailmessage.FieldFromAddress, field.TypeString, value)
		_node.FromAddress = value
	}
	if value, ok := _c.mutation.FromName(); ok {
		_spec.SetField(emailmessage.FieldFromName, field.TypeString, value)
		_node.FromName = value
	}
	if value, ok := _c.mutation.ToAddress(); ok {
		_spec.SetField(emailmessage.FieldToAddress, field.TypeString, value)
		_node.ToAddress = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(emailmessage.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.TextBody(); ok {
		_spec.SetField(emailmessage.FieldTextBody, field.TypeString, value)
		_node.TextBody = value
	}
	if value, ok := _c.mutation.HTMLBody(); ok {
		_spec.SetField(emailmessage.FieldHTMLBody, field.TypeString, value)
		_node.HTMLBody = value
	}
	if value, ok := _c.mutation.VerificationCode(); ok {
		_spec.SetField(emailmessage.FieldVerificationCode, field.TypeString, value)
		_node.VerificationCode = value
	}
	if value, ok := _c.mutation.VerificationURL(); ok {
		_spec.SetField(emailmessage.FieldVerificationURL, field.TypeString, value)
		_node.VerificationURL = value
	}
	if value, ok := _c.mutation.VerificationConfidence(); ok {
		_spec.SetField(emailmessage.FieldVerificationConfidence, field.TypeFloat64, value)
		_node.VerificationConfidence = value
	}
	if value, ok := _c.mutation.VerificationMethod(); ok {
		_spec.SetField(emailmessage.FieldVerificationMethod, field.TypeString, value)
		_node.VerificationMethod = value
	}
	if value, ok := _c.mutation.ReceivedAt(); ok {
		_spec.SetField(emailmessage.FieldReceivedAt, field.TypeTime, value)
		_node.ReceivedAt = value
	}
	if value, ok := _c.mutation.DedupeHash(); ok {
		_spec.SetField(emailmessage.FieldDedupeHash, field.TypeString, value)
		_node.DedupeHash = value
	}
	if value, ok := _c.mutation.RawPayload(); ok {
		_spec.SetField(emailmessage.FieldRawPayload, field.TypeJSON, value)
		_node.RawPayload = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(emailmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(emailmessage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EmailMessage.Create().
//		SetEmailOrderID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EmailMessageUpsert) {
//			SetEmailOrderID(v+v).
//		}).
//		Exec(ctx)
func (_c *EmailMessageCreate) OnConflict(opts ...sql.ConflictOption) *EmailMessageUpsertOne {
	_c.conflict = opts
	return &EmailMessageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EmailMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EmailMessageCreate) OnConflictColumns(columns ...string) *EmailMessageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EmailMessageUpsertOne{
		create: _c,
	}
}

type (
	// EmailMessageUpsertOne is the builder for "upsert"-ing
	//  one EmailMessage node.
	EmailMessageUpsertOne struct {
		create *EmailMessageCreate
	}

	// EmailMessageUpsert is the "OnConflict" setter.
	EmailMessageUpsert struct {
		*sql.UpdateSet
	}
)

// SetEmailOrderID sets the "email_order_id" field.
func (u *EmailMessageUpsert) SetEmailOrderID(v int64) *EmailMessageUpsert {
	u.Set(emailmessage.FieldEmailOrderID, v)
	return u
}

// UpdateEmailOrderID sets the "email_order_id" field to the value that was provided on create.
func (u *EmailMessageUpsert) UpdateEmailOrderID() *EmailMessageUpsert {
	u.SetExcluded(emailmessage.FieldEmailOrderID)
	return u
}

// AddEmailOrderID adds v to the "email_order_id" field.
func (u *EmailMessageUpsert) AddEmailOrderID(v int64) *EmailMessageUpsert {
	u.Add(emailmessage.FieldEmailOrderID, v)
	return u
}

// SetProviderMessageID sets the "provider_message_id" field.
func (u *EmailMessageUpsert) SetProviderMessageID(v string) *EmailMessageUpsert {
	u.Set(emailmessage.FieldProviderMessageID, v)
	return u
}

// UpdateProviderMessageID sets the "provider_message_id" field to the value that was provided on create.
func (u *EmailMessageUpsert) UpdateProviderMessageID() *EmailMessageUpsert {
	u.SetExcluded(emailmessage.FieldProviderMessageID)
	return u
}

// SetFromAddress sets the "from_address" field.
func (u *EmailMessageUpsert) SetFromAddress(v string) *EmailMessageUpsert {
	u.Set(emailmessage.FieldFromAddress, v)
	return u
}

// UpdateFromAddress sets the "from_address" field to the value that was provided on create.
func (u *EmailMessageUpsert) UpdateFromAddress() *EmailMessageUpsert {
	u.SetExcluded(emailmessage.FieldFromAddress)
	return u
}

// SetFromName sets the "from_name" field.
func (u *EmailMessageUpsert) SetFromName(v string) *EmailMessageUpsert {
	u.Set(emailmessage.FieldFromName, v)
	return u
}

// UpdateFromName sets the "from_name" field to the value that was provided on create.
func (u *EmailMessageUpsert) UpdateFromName() *EmailMessageUpsert {
	u.SetExcluded(emailmessage.FieldFromName)
	return u
}

// SetToAddress sets the "to_address" field.
func (u *EmailMessageUpsert) SetToAddress(v string) *EmailMessageUpsert {
	u.Set(emailmessage.FieldToAddress, v)
	return u
}

// UpdateToAddress sets the "to_address" field to the value that was provided on create.
func (u *EmailMessageUpsert) UpdateToAddress() *EmailMessageUpsert {
	u.SetExcluded(emailmessage.FieldToAddress)
	return u
}

// SetSubject sets the "subject" field.
func (u *EmailMessageUpsert) SetSubject(v string) *EmailMessageUpsert {
	u.Set(emailmessage.FieldSubject, v)
	return u
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *EmailMessageUpsert) UpdateSubject() *EmailMessageUpsert {
	u.SetExcluded(emailmessage.FieldSubject)
	return u
}

// SetTextBody sets the "text_body" field.
func (u *EmailMessageUpsert) SetTextBody(v string) *EmailMessageUpsert {
	u.Set(emailmessage.FieldTextBody, v)
	return u
}

// UpdateTextBody sets the "text_body" field to the value that was provided on create.
func (u *EmailMessageUpsert) UpdateTextBody() *EmailMessageUpsert {
	u.SetExcluded(emailmessage.FieldTextBody)
	return u
}

// SetHTMLBody sets the "html_body" field.
func (u *EmailMessageUpsert) SetHTMLBody(v string) *EmailMessageUpsert {
	u.Set(emailmessage.FieldHTMLBody, v)
	return u
}

// UpdateHTMLBody sets the "html_body" field to the value that was provided on create.
func (u *EmailMessageUpsert) UpdateHTMLBody() *EmailMessageUpsert {
	u.SetExcluded(emailmessage.FieldHTMLBody)
	return u
}

// SetVerificationCode sets the "verification_code" field.
func (u *EmailMessageUpsert) SetVerificationCode(v string) *EmailMessageUpsert {
	u.Set(emailmessage.FieldVerificationCode, v)
	return u
}

// UpdateVerificationCode sets the "verification_code" field to the value that was provided on create.
func (u *EmailMessageUpsert) UpdateVerificationCode() *EmailMessageUpsert {
	u.SetExcluded(emailmessage.FieldVerificationCode)
	return u
}

// SetVerificationURL sets the "verification_url" field.
func (u *EmailMessageUpsert) SetVerificationURL(v string) *EmailMessageUpsert {
	u.Set(emailmessage.FieldVerificationURL, v)
	return u
}

// UpdateVerificationURL sets the "verification_url" field to the value that was provided on create.
func (u *EmailMessageUpsert) UpdateVerificationURL() *EmailMessageUpsert {
	u.SetExcluded(emailmessage.FieldVerificationURL)
	return u
}

// SetVerificationConfidence sets the "verification_confidence" field.
func (u *EmailMessageUpsert) SetVerificationConfidence(v float64) *EmailMessageUpsert {
	u.Set(emailmessage.FieldVerificationConfidence, v)
	return u
}

// UpdateVerificationConfidence sets the "verification_confidence" field to the value that was provided on create.
func (u *EmailMessageUpsert) UpdateVerificationConfidence() *EmailMessageUpsert {
	u.SetExcluded(emailmessage.FieldVerificationConfidence)
	return u
}

// AddVerificationConfidence adds v to the "verification_confidence" field.
func (u *EmailMessageUpsert) AddVerificationConfidence(v float64) *EmailMessageUpsert {
	u.Add(emailmessage.FieldVerificationConfidence, v)
	return u
}

// SetVerificationMethod sets the "verification_method" field.
func (u *EmailMessageUpsert) SetVerificationMethod(v string) *EmailMessageUpsert {
	u.Set(emailmessage.FieldVerificationMethod, v)
	return u
}

// UpdateVerificationMethod sets the "verification_method" field to the value that was provided on create.
func (u *EmailMessageUpsert) UpdateVerificationMethod() *EmailMessageUpsert {
	u.SetExcluded(emailmessage.FieldVerificationMethod)
	return u
}

// SetReceivedAt sets the "received_at" field.
func (u *EmailMessageUpsert) SetReceivedAt(v time.Time) *EmailMessageUpsert {
	u.Set(emailmessage.FieldReceivedAt, v)
	return u
}

// UpdateReceivedAt sets the "received_at" field to the value that was provided on create.
func (u *EmailMessageUpsert) UpdateReceivedAt() *EmailMessageUpsert {
	u.SetExcluded(emailmessage.FieldReceivedAt)
	return u
}

// SetDedupeHash sets the "dedupe_hash" field.
func (u *EmailMessageUpsert) SetDedupeHash(v string) *EmailMessageUpsert {
	u.Set(emailmessage.FieldDedupeHash, v)
	return u
}

// UpdateDedupeHash sets the "dedupe_hash" field to the value that was provided on create.
func (u *EmailMessageUpsert) UpdateDedupeHash() *EmailMessageUpsert {
	u.SetExcluded(emailmessage.FieldDedupeHash)
	return u
}

// SetRawPayload sets the "raw_payload" field.
func (u *EmailMessageUpsert) SetRawPayload(v map[string]interface{}) *EmailMessageUpsert {
	u.Set(emailmessage.FieldRawPayload, v)
	return u
}

// UpdateRawPayload sets the "raw_payload" field to the value that was provided on create.
func (u *EmailMessageUpsert) UpdateRawPayload() *EmailMessageUpsert {
	u.SetExcluded(emailmessage.FieldRawPayload)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *EmailMessageUpsert) SetCreatedAt(v time.Time) *EmailMessageUpsert {
	u.Set(emailmessage.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *EmailMessageUpsert) UpdateCreatedAt() *EmailMessageUpsert {
	u.SetExcluded(emailmessage.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EmailMessageUpsert) SetUpdatedAt(v time.Time) *EmailMessageUpsert {
	u.Set(emailmessage.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EmailMessageUpsert) UpdateUpdatedAt() *EmailMessageUpsert {
	u.SetExcluded(emailmessage.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.EmailMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EmailMessageUpsertOne) UpdateNewValues() *EmailMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EmailMessage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EmailMessageUpsertOne) Ignore() *EmailMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EmailMessageUpsertOne) DoNothing() *EmailMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EmailMessageCreate.OnConflict
// documentation for more info.
func (u *EmailMessageUpsertOne) Update(set func(*EmailMessageUpsert)) *EmailMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EmailMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetEmailOrderID sets the "email_order_id" field.
func (u *EmailMessageUpsertOne) SetEmailOrderID(v int64) *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetEmailOrderID(v)
	})
}

// AddEmailOrderID adds v to the "email_order_id" field.
func (u *EmailMessageUpsertOne) AddEmailOrderID(v int64) *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.AddEmailOrderID(v)
	})
}

// UpdateEmailOrderID sets the "email_order_id" field to the value that was provided on create.
func (u *EmailMessageUpsertOne) UpdateEmailOrderID() *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateEmailOrderID()
	})
}

// SetProviderMessageID sets the "provider_message_id" field.
func (u *EmailMessageUpsertOne) SetProviderMessageID(v string) *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetProviderMessageID(v)
	})
}

// UpdateProviderMessageID sets the "provider_message_id" field to the value that was provided on create.
func (u *EmailMessageUpsertOne) UpdateProviderMessageID() *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateProviderMessageID()
	})
}

// SetFromAddress sets the "from_address" field.
func (u *EmailMessageUpsertOne) SetFromAddress(v string) *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetFromAddress(v)
	})
}

// UpdateFromAddress sets the "from_address" field to the value that was provided on create.
func (u *EmailMessageUpsertOne) UpdateFromAddress() *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateFromAddress()
	})
}

// SetFromName sets the "from_name" field.
func (u *EmailMessageUpsertOne) SetFromName(v string) *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetFromName(v)
	})
}

// UpdateFromName sets the "from_name" field to the value that was provided on create.
func (u *EmailMessageUpsertOne) UpdateFromName() *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateFromName()
	})
}

// SetToAddress sets the "to_address" field.
func (u *EmailMessageUpsertOne) SetToAddress(v string) *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetToAddress(v)
	})
}

// UpdateToAddress sets the "to_address" field to the value that was provided on create.
func (u *EmailMessageUpsertOne) UpdateToAddress() *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateToAddress()
	})
}

// SetSubject sets the "subject" field.
func (u *EmailMessageUpsertOne) SetSubject(v string) *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *EmailMessageUpsertOne) UpdateSubject() *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateSubject()
	})
}

// SetTextBody sets the "text_body" field.
func (u *EmailMessageUpsertOne) SetTextBody(v string) *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetTextBody(v)
	})
}

// UpdateTextBody sets the "text_body" field to the value that was provided on create.
func (u *EmailMessageUpsertOne) UpdateTextBody() *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateTextBody()
	})
}

// SetHTMLBody sets the "html_body" field.
func (u *EmailMessageUpsertOne) SetHTMLBody(v string) *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetHTMLBody(v)
	})
}

// UpdateHTMLBody sets the "html_body" field to the value that was provided on create.
func (u *EmailMessageUpsertOne) UpdateHTMLBody() *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateHTMLBody()
	})
}

// SetVerificationCode sets the "verification_code" field.
func (u *EmailMessageUpsertOne) SetVerificationCode(v string) *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetVerificationCode(v)
	})
}

// UpdateVerificationCode sets the "verification_code" field to the value that was provided on create.
func (u *EmailMessageUpsertOne) UpdateVerificationCode() *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateVerificationCode()
	})
}

// SetVerificationURL sets the "verification_url" field.
func (u *EmailMessageUpsertOne) SetVerificationURL(v string) *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetVerificationURL(v)
	})
}

// UpdateVerificationURL sets the "verification_url" field to the value that was provided on create.
func (u *EmailMessageUpsertOne) UpdateVerificationURL() *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateVerificationURL()
	})
}

// SetVerificationConfidence sets the "verification_confidence" field.
func (u *EmailMessageUpsertOne) SetVerificationConfidence(v float64) *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetVerificationConfidence(v)
	})
}

// AddVerificationConfidence adds v to the "verification_confidence" field.
func (u *EmailMessageUpsertOne) AddVerificationConfidence(v float64) *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.AddVerificationConfidence(v)
	})
}

// UpdateVerificationConfidence sets the "verification_confidence" field to the value that was provided on create.
func (u *EmailMessageUpsertOne) UpdateVerificationConfidence() *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateVerificationConfidence()
	})
}

// SetVerificationMethod sets the "verification_method" field.
func (u *EmailMessageUpsertOne) SetVerificationMethod(v string) *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetVerificationMethod(v)
	})
}

// UpdateVerificationMethod sets the "verification_method" field to the value that was provided on create.
func (u *EmailMessageUpsertOne) UpdateVerificationMethod() *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateVerificationMethod()
	})
}

// SetReceivedAt sets the "received_at" field.
func (u *EmailMessageUpsertOne) SetReceivedAt(v time.Time) *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetReceivedAt(v)
	})
}

// UpdateReceivedAt sets the "received_at" field to the value that was provided on create.
func (u *EmailMessageUpsertOne) UpdateReceivedAt() *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateReceivedAt()
	})
}

// SetDedupeHash sets the "dedupe_hash" field.
func (u *EmailMessageUpsertOne) SetDedupeHash(v string) *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetDedupeHash(v)
	})
}

// UpdateDedupeHash sets the "dedupe_hash" field to the value that was provided on create.
func (u *EmailMessageUpsertOne) UpdateDedupeHash() *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateDedupeHash()
	})
}

// SetRawPayload sets the "raw_payload" field.
func (u *EmailMessageUpsertOne) SetRawPayload(v map[string]interface{}) *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetRawPayload(v)
	})
}

// UpdateRawPayload sets the "raw_payload" field to the value that was provided on create.
func (u *EmailMessageUpsertOne) UpdateRawPayload() *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateRawPayload()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *EmailMessageUpsertOne) SetCreatedAt(v time.Time) *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *EmailMessageUpsertOne) UpdateCreatedAt() *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EmailMessageUpsertOne) SetUpdatedAt(v time.Time) *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EmailMessageUpsertOne) UpdateUpdatedAt() *EmailMessageUpsertOne {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *EmailMessageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EmailMessageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EmailMessageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EmailMessageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EmailMessageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EmailMessageCreateBulk is the builder for creating many EmailMessage entities in bulk.
type EmailMessageCreateBulk struct {
	config
	err      error
	builders []*EmailMessageCreate
	conflict []sql.ConflictOption
}

// Save creates the EmailMessage entities in the database.
func (_c *EmailMessageCreateBulk) Save(ctx context.Context) ([]*EmailMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EmailMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmailMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EmailMessageCreateBulk) SaveX(ctx context.Context) []*EmailMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EmailMessage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EmailMessageUpsert) {
//			SetEmailOrderID(v+v).
//		}).
//		Exec(ctx)
func (_c *EmailMessageCreateBulk) OnConflict(opts ...sql.ConflictOption) *EmailMessageUpsertBulk {
	_c.conflict = opts
	return &EmailMessageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EmailMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EmailMessageCreateBulk) OnConflictColumns(columns ...string) *EmailMessageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EmailMessageUpsertBulk{
		create: _c,
	}
}

// EmailMessageUpsertBulk is the builder for "upsert"-ing
// a bulk of EmailMessage nodes.
type EmailMessageUpsertBulk struct {
	create *EmailMessageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EmailMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EmailMessageUpsertBulk) UpdateNewValues() *EmailMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EmailMessage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EmailMessageUpsertBulk) Ignore() *EmailMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EmailMessageUpsertBulk) DoNothing() *EmailMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EmailMessageCreateBulk.OnConflict
// documentation for more info.
func (u *EmailMessageUpsertBulk) Update(set func(*EmailMessageUpsert)) *EmailMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EmailMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetEmailOrderID sets the "email_order_id" field.
func (u *EmailMessageUpsertBulk) SetEmailOrderID(v int64) *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetEmailOrderID(v)
	})
}

// AddEmailOrderID adds v to the "email_order_id" field.
func (u *EmailMessageUpsertBulk) AddEmailOrderID(v int64) *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.AddEmailOrderID(v)
	})
}

// UpdateEmailOrderID sets the "email_order_id" field to the value that was provided on create.
func (u *EmailMessageUpsertBulk) UpdateEmailOrderID() *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateEmailOrderID()
	})
}

// SetProviderMessageID sets the "provider_message_id" field.
func (u *EmailMessageUpsertBulk) SetProviderMessageID(v string) *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetProviderMessageID(v)
	})
}

// UpdateProviderMessageID sets the "provider_message_id" field to the value that was provided on create.
func (u *EmailMessageUpsertBulk) UpdateProviderMessageID() *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateProviderMessageID()
	})
}

// SetFromAddress sets the "from_address" field.
func (u *EmailMessageUpsertBulk) SetFromAddress(v string) *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetFromAddress(v)
	})
}

// UpdateFromAddress sets the "from_address" field to the value that was provided on create.
func (u *EmailMessageUpsertBulk) UpdateFromAddress() *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateFromAddress()
	})
}

// SetFromName sets the "from_name" field.
func (u *EmailMessageUpsertBulk) SetFromName(v string) *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetFromName(v)
	})
}

// UpdateFromName sets the "from_name" field to the value that was provided on create.
func (u *EmailMessageUpsertBulk) UpdateFromName() *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateFromName()
	})
}

// SetToAddress sets the "to_address" field.
func (u *EmailMessageUpsertBulk) SetToAddress(v string) *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetToAddress(v)
	})
}

// UpdateToAddress sets the "to_address" field to the value that was provided on create.
func (u *EmailMessageUpsertBulk) UpdateToAddress() *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateToAddress()
	})
}

// SetSubject sets the "subject" field.
func (u *EmailMessageUpsertBulk) SetSubject(v string) *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *EmailMessageUpsertBulk) UpdateSubject() *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateSubject()
	})
}

// SetTextBody sets the "text_body" field.
func (u *EmailMessageUpsertBulk) SetTextBody(v string) *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetTextBody(v)
	})
}

// UpdateTextBody sets the "text_body" field to the value that was provided on create.
func (u *EmailMessageUpsertBulk) UpdateTextBody() *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateTextBody()
	})
}

// SetHTMLBody sets the "html_body" field.
func (u *EmailMessageUpsertBulk) SetHTMLBody(v string) *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetHTMLBody(v)
	})
}

// UpdateHTMLBody sets the "html_body" field to the value that was provided on create.
func (u *EmailMessageUpsertBulk) UpdateHTMLBody() *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateHTMLBody()
	})
}

// SetVerificationCode sets the "verification_code" field.
func (u *EmailMessageUpsertBulk) SetVerificationCode(v string) *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetVerificationCode(v)
	})
}

// UpdateVerificationCode sets the "verification_code" field to the value that was provided on create.
func (u *EmailMessageUpsertBulk) UpdateVerificationCode() *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateVerificationCode()
	})
}

// SetVerificationURL sets the "verification_url" field.
func (u *EmailMessageUpsertBulk) SetVerificationURL(v string) *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetVerificationURL(v)
	})
}

// UpdateVerificationURL sets the "verification_url" field to the value that was provided on create.
func (u *EmailMessageUpsertBulk) UpdateVerificationURL() *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateVerificationURL()
	})
}

// SetVerificationConfidence sets the "verification_confidence" field.
func (u *EmailMessageUpsertBulk) SetVerificationConfidence(v float64) *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetVerificationConfidence(v)
	})
}

// AddVerificationConfidence adds v to the "verification_confidence" field.
func (u *EmailMessageUpsertBulk) AddVerificationConfidence(v float64) *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.AddVerificationConfidence(v)
	})
}

// UpdateVerificationConfidence sets the "verification_confidence" field to the value that was provided on create.
func (u *EmailMessageUpsertBulk) UpdateVerificationConfidence() *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateVerificationConfidence()
	})
}

// SetVerificationMethod sets the "verification_method" field.
func (u *EmailMessageUpsertBulk) SetVerificationMethod(v string) *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetVerificationMethod(v)
	})
}

// UpdateVerificationMethod sets the "verification_method" field to the value that was provided on create.
func (u *EmailMessageUpsertBulk) UpdateVerificationMethod() *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateVerificationMethod()
	})
}

// SetReceivedAt sets the "received_at" field.
func (u *EmailMessageUpsertBulk) SetReceivedAt(v time.Time) *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetReceivedAt(v)
	})
}

// UpdateReceivedAt sets the "received_at" field to the value that was provided on create.
func (u *EmailMessageUpsertBulk) UpdateReceivedAt() *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateReceivedAt()
	})
}

// SetDedupeHash sets the "dedupe_hash" field.
func (u *EmailMessageUpsertBulk) SetDedupeHash(v string) *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetDedupeHash(v)
	})
}

// UpdateDedupeHash sets the "dedupe_hash" field to the value that was provided on create.
func (u *EmailMessageUpsertBulk) UpdateDedupeHash() *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateDedupeHash()
	})
}

// SetRawPayload sets the "raw_payload" field.
func (u *EmailMessageUpsertBulk) SetRawPayload(v map[string]interface{}) *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetRawPayload(v)
	})
}

// UpdateRawPayload sets the "raw_payload" field to the value that was provided on create.
func (u *EmailMessageUpsertBulk) UpdateRawPayload() *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateRawPayload()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *EmailMessageUpsertBulk) SetCreatedAt(v time.Time) *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *EmailMessageUpsertBulk) UpdateCreatedAt() *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EmailMessageUpsertBulk) SetUpdatedAt(v time.Time) *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EmailMessageUpsertBulk) UpdateUpdatedAt() *EmailMessageUpsertBulk {
	return u.Update(func(s *EmailMessageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *EmailMessageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EmailMessageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EmailMessageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EmailMessageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
