// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/emailprovider"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// EmailProviderUpdate is the builder for updating EmailProvider entities.
type EmailProviderUpdate struct {
	config
	hooks    []Hook
	mutation *EmailProviderMutation
}

// Where appends a list predicates to the EmailProviderUpdate builder.
func (_u *EmailProviderUpdate) Where(ps ...predicate.EmailProvider) *EmailProviderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *EmailProviderUpdate) SetCode(v string) *EmailProviderUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *EmailProviderUpdate) SetNillableCode(v *string) *EmailProviderUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *EmailProviderUpdate) SetName(v string) *EmailProviderUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EmailProviderUpdate) SetNillableName(v *string) *EmailProviderUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *EmailProviderUpdate) SetBaseURL(v string) *EmailProviderUpdate {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *EmailProviderUpdate) SetNillableBaseURL(v *string) *EmailProviderUpdate {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetCredentialRef sets the "credential_ref" field.
func (_u *EmailProviderUpdate) SetCredentialRef(v string) *EmailProviderUpdate {
	_u.mutation.SetCredentialRef(v)
	return _u
}

// SetNillableCredentialRef sets the "credential_ref" field if the given value is not nil.
func (_u *EmailProviderUpdate) SetNillableCredentialRef(v *string) *EmailProviderUpdate {
	if v != nil {
		_u.SetCredentialRef(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *EmailProviderUpdate) SetEnabled(v bool) *EmailProviderUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *EmailProviderUpdate) SetNillableEnabled(v *bool) *EmailProviderUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetHealthStatus sets the "health_status" field.
func (_u *EmailProviderUpdate) SetHealthStatus(v string) *EmailProviderUpdate {
	_u.mutation.SetHealthStatus(v)
	return _u
}

// SetNillableHealthStatus sets the "health_status" field if the given value is not nil.
func (_u *EmailProviderUpdate) SetNillableHealthStatus(v *string) *EmailProviderUpdate {
	if v != nil {
		_u.SetHealthStatus(*v)
	}
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *EmailProviderUpdate) SetCapabilities(v map[string]interface{}) *EmailProviderUpdate {
	_u.mutation.SetCapabilities(v)
	return _u
}

// SetBilling sets the "billing" field.
func (_u *EmailProviderUpdate) SetBilling(v map[string]interface{}) *EmailProviderUpdate {
	_u.mutation.SetBilling(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *EmailProviderUpdate) SetMetadata(v map[string]interface{}) *EmailProviderUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *EmailProviderUpdate) SetCreatedAt(v time.Time) *EmailProviderUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *EmailProviderUpdate) SetNillableCreatedAt(v *time.Time) *EmailProviderUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EmailProviderUpdate) SetUpdatedAt(v time.Time) *EmailProviderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *EmailProviderUpdate) SetNillableUpdatedAt(v *time.Time) *EmailProviderUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the EmailProviderMutation object of the builder.
func (_u *EmailProviderUpdate) Mutation() *EmailProviderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EmailProviderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EmailProviderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailProviderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailProviderUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := emailprovider.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "EmailProvider.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := emailprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "EmailProvider.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := emailprovider.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "EmailProvider.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CredentialRef(); ok {
		if err := emailprovider.CredentialRefValidator(v); err != nil {
			return &ValidationError{Name: "credential_ref", err: fmt.Errorf(`ent: validator failed for field "EmailProvider.credential_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HealthStatus(); ok {
		if err := emailprovider.HealthStatusValidator(v); err != nil {
			return &ValidationError{Name: "health_status", err: fmt.Errorf(`ent: validator failed for field "EmailProvider.health_status": %w`, err)}
		}
	}
	return nil
}

func (_u *EmailProviderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailprovider.Table, emailprovider.Columns, sqlgraph.NewFieldSpec(emailprovider.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(emailprovider.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(emailprovider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(emailprovider.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialRef(); ok {
		_spec.SetField(emailprovider.FieldCredentialRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(emailprovider.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HealthStatus(); ok {
		_spec.SetField(emailprovider.FieldHealthStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(emailprovider.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Billing(); ok {
		_spec.SetField(emailprovider.FieldBilling, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(emailprovider.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(emailprovider.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(emailprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EmailProviderUpdateOne is the builder for updating a single EmailProvider entity.
type EmailProviderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmailProviderMutation
}

// SetCode sets the "code" field.
func (_u *EmailProviderUpdateOne) SetCode(v string) *EmailProviderUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *EmailProviderUpdateOne) SetNillableCode(v *string) *EmailProviderUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *EmailProviderUpdateOne) SetName(v string) *EmailProviderUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EmailProviderUpdateOne) SetNillableName(v *string) *EmailProviderUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *EmailProviderUpdateOne) SetBaseURL(v string) *EmailProviderUpdateOne {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *EmailProviderUpdateOne) SetNillableBaseURL(v *string) *EmailProviderUpdateOne {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetCredentialRef sets the "credential_ref" field.
func (_u *EmailProviderUpdateOne) SetCredentialRef(v string) *EmailProviderUpdateOne {
	_u.mutation.SetCredentialRef(v)
	return _u
}

// SetNillableCredentialRef sets the "credential_ref" field if the given value is not nil.
func (_u *EmailProviderUpdateOne) SetNillableCredentialRef(v *string) *EmailProviderUpdateOne {
	if v != nil {
		_u.SetCredentialRef(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *EmailProviderUpdateOne) SetEnabled(v bool) *EmailProviderUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *EmailProviderUpdateOne) SetNillableEnabled(v *bool) *EmailProviderUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetHealthStatus sets the "health_status" field.
func (_u *EmailProviderUpdateOne) SetHealthStatus(v string) *EmailProviderUpdateOne {
	_u.mutation.SetHealthStatus(v)
	return _u
}

// SetNillableHealthStatus sets the "health_status" field if the given value is not nil.
func (_u *EmailProviderUpdateOne) SetNillableHealthStatus(v *string) *EmailProviderUpdateOne {
	if v != nil {
		_u.SetHealthStatus(*v)
	}
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *EmailProviderUpdateOne) SetCapabilities(v map[string]interface{}) *EmailProviderUpdateOne {
	_u.mutation.SetCapabilities(v)
	return _u
}

// SetBilling sets the "billing" field.
func (_u *EmailProviderUpdateOne) SetBilling(v map[string]interface{}) *EmailProviderUpdateOne {
	_u.mutation.SetBilling(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *EmailProviderUpdateOne) SetMetadata(v map[string]interface{}) *EmailProviderUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *EmailProviderUpdateOne) SetCreatedAt(v time.Time) *EmailProviderUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *EmailProviderUpdateOne) SetNillableCreatedAt(v *time.Time) *EmailProviderUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EmailProviderUpdateOne) SetUpdatedAt(v time.Time) *EmailProviderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *EmailProviderUpdateOne) SetNillableUpdatedAt(v *time.Time) *EmailProviderUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the EmailProviderMutation object of the builder.
func (_u *EmailProviderUpdateOne) Mutation() *EmailProviderMutation {
	return _u.mutation
}

// Where appends a list predicates to the EmailProviderUpdate builder.
func (_u *EmailProviderUpdateOne) Where(ps ...predicate.EmailProvider) *EmailProviderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EmailProviderUpdateOne) Select(field string, fields ...string) *EmailProviderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EmailProvider entity.
func (_u *EmailProviderUpdateOne) Save(ctx context.Context) (*EmailProvider, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailProviderUpdateOne) SaveX(ctx context.Context) *EmailProvider {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EmailProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailProviderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailProviderUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := emailprovider.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "EmailProvider.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := emailprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "EmailProvider.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := emailprovider.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "EmailProvider.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CredentialRef(); ok {
		if err := emailprovider.CredentialRefValidator(v); err != nil {
			return &ValidationError{Name: "credential_ref", err: fmt.Errorf(`ent: validator failed for field "EmailProvider.credential_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HealthStatus(); ok {
		if err := emailprovider.HealthStatusValidator(v); err != nil {
			return &ValidationError{Name: "health_status", err: fmt.Errorf(`ent: validator failed for field "EmailProvider.health_status": %w`, err)}
		}
	}
	return nil
}

func (_u *EmailProviderUpdateOne) sqlSave(ctx context.Context) (_node *EmailProvider, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailprovider.Table, emailprovider.Columns, sqlgraph.NewFieldSpec(emailprovider.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EmailProvider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, emailprovider.FieldID)
		for _, f := range fields {
			if !emailprovider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != emailprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(emailprovider.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(emailprovider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(emailprovider.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialRef(); ok {
		_spec.SetField(emailprovider.FieldCredentialRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(emailprovider.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HealthStatus(); ok {
		_spec.SetField(emailprovider.FieldHealthStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(emailprovider.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Billing(); ok {
		_spec.SetField(emailprovider.FieldBilling, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(emailprovider.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(emailprovider.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(emailprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &EmailProvider{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
