// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/emailchannel"
)

// EmailChannelCreate is the builder for creating a EmailChannel entity.
type EmailChannelCreate struct {
	config
	mutation *EmailChannelMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCode sets the "code" field.
func (_c *EmailChannelCreate) SetCode(v string) *EmailChannelCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetPublicName sets the "public_name" field.
func (_c *EmailChannelCreate) SetPublicName(v string) *EmailChannelCreate {
	_c.mutation.SetPublicName(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *EmailChannelCreate) SetRole(v string) *EmailChannelCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *EmailChannelCreate) SetNillableRole(v *string) *EmailChannelCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetProviderID sets the "provider_id" field.
func (_c *EmailChannelCreate) SetProviderID(v int64) *EmailChannelCreate {
	_c.mutation.SetProviderID(v)
	return _c
}

// SetEmailType sets the "email_type" field.
func (_c *EmailChannelCreate) SetEmailType(v string) *EmailChannelCreate {
	_c.mutation.SetEmailType(v)
	return _c
}

// SetNillableEmailType sets the "email_type" field if the given value is not nil.
func (_c *EmailChannelCreate) SetNillableEmailType(v *string) *EmailChannelCreate {
	if v != nil {
		_c.SetEmailType(*v)
	}
	return _c
}

// SetPrivacyLevel sets the "privacy_level" field.
func (_c *EmailChannelCreate) SetPrivacyLevel(v string) *EmailChannelCreate {
	_c.mutation.SetPrivacyLevel(v)
	return _c
}

// SetNillablePrivacyLevel sets the "privacy_level" field if the given value is not nil.
func (_c *EmailChannelCreate) SetNillablePrivacyLevel(v *string) *EmailChannelCreate {
	if v != nil {
		_c.SetPrivacyLevel(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *EmailChannelCreate) SetEnabled(v bool) *EmailChannelCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *EmailChannelCreate) SetNillableEnabled(v *bool) *EmailChannelCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetVisible sets the "visible" field.
func (_c *EmailChannelCreate) SetVisible(v bool) *EmailChannelCreate {
	_c.mutation.SetVisible(v)
	return _c
}

// SetNillableVisible sets the "visible" field if the given value is not nil.
func (_c *EmailChannelCreate) SetNillableVisible(v *bool) *EmailChannelCreate {
	if v != nil {
		_c.SetVisible(*v)
	}
	return _c
}

// SetHealthy sets the "healthy" field.
func (_c *EmailChannelCreate) SetHealthy(v bool) *EmailChannelCreate {
	_c.mutation.SetHealthy(v)
	return _c
}

// SetNillableHealthy sets the "healthy" field if the given value is not nil.
func (_c *EmailChannelCreate) SetNillableHealthy(v *bool) *EmailChannelCreate {
	if v != nil {
		_c.SetHealthy(*v)
	}
	return _c
}

// SetSalePrice sets the "sale_price" field.
func (_c *EmailChannelCreate) SetSalePrice(v float64) *EmailChannelCreate {
	_c.mutation.SetSalePrice(v)
	return _c
}

// SetNillableSalePrice sets the "sale_price" field if the given value is not nil.
func (_c *EmailChannelCreate) SetNillableSalePrice(v *float64) *EmailChannelCreate {
	if v != nil {
		_c.SetSalePrice(*v)
	}
	return _c
}

// SetOrderTTLSeconds sets the "order_ttl_seconds" field.
func (_c *EmailChannelCreate) SetOrderTTLSeconds(v int) *EmailChannelCreate {
	_c.mutation.SetOrderTTLSeconds(v)
	return _c
}

// SetNillableOrderTTLSeconds sets the "order_ttl_seconds" field if the given value is not nil.
func (_c *EmailChannelCreate) SetNillableOrderTTLSeconds(v *int) *EmailChannelCreate {
	if v != nil {
		_c.SetOrderTTLSeconds(*v)
	}
	return _c
}

// SetCapturePolicy sets the "capture_policy" field.
func (_c *EmailChannelCreate) SetCapturePolicy(v string) *EmailChannelCreate {
	_c.mutation.SetCapturePolicy(v)
	return _c
}

// SetNillableCapturePolicy sets the "capture_policy" field if the given value is not nil.
func (_c *EmailChannelCreate) SetNillableCapturePolicy(v *string) *EmailChannelCreate {
	if v != nil {
		_c.SetCapturePolicy(*v)
	}
	return _c
}

// SetRefundPolicy sets the "refund_policy" field.
func (_c *EmailChannelCreate) SetRefundPolicy(v string) *EmailChannelCreate {
	_c.mutation.SetRefundPolicy(v)
	return _c
}

// SetNillableRefundPolicy sets the "refund_policy" field if the given value is not nil.
func (_c *EmailChannelCreate) SetNillableRefundPolicy(v *string) *EmailChannelCreate {
	if v != nil {
		_c.SetRefundPolicy(*v)
	}
	return _c
}

// SetPollingBackoff sets the "polling_backoff" field.
func (_c *EmailChannelCreate) SetPollingBackoff(v []int) *EmailChannelCreate {
	_c.mutation.SetPollingBackoff(v)
	return _c
}

// SetMaxProviderRequestsPerOrder sets the "max_provider_requests_per_order" field.
func (_c *EmailChannelCreate) SetMaxProviderRequestsPerOrder(v int) *EmailChannelCreate {
	_c.mutation.SetMaxProviderRequestsPerOrder(v)
	return _c
}

// SetNillableMaxProviderRequestsPerOrder sets the "max_provider_requests_per_order" field if the given value is not nil.
func (_c *EmailChannelCreate) SetNillableMaxProviderRequestsPerOrder(v *int) *EmailChannelCreate {
	if v != nil {
		_c.SetMaxProviderRequestsPerOrder(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *EmailChannelCreate) SetSortOrder(v int) *EmailChannelCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *EmailChannelCreate) SetNillableSortOrder(v *int) *EmailChannelCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *EmailChannelCreate) SetMetadata(v map[string]interface{}) *EmailChannelCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EmailChannelCreate) SetCreatedAt(v time.Time) *EmailChannelCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EmailChannelCreate) SetUpdatedAt(v time.Time) *EmailChannelCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// Mutation returns the EmailChannelMutation object of the builder.
func (_c *EmailChannelCreate) Mutation() *EmailChannelMutation {
	return _c.mutation
}

// Save creates the EmailChannel in the database.
func (_c *EmailChannelCreate) Save(ctx context.Context) (*EmailChannel, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EmailChannelCreate) SaveX(ctx context.Context) *EmailChannel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailChannelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailChannelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EmailChannelCreate) defaults() {
	if _, ok := _c.mutation.Role(); !ok {
		v := emailchannel.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.EmailType(); !ok {
		v := emailchannel.DefaultEmailType
		_c.mutation.SetEmailType(v)
	}
	if _, ok := _c.mutation.PrivacyLevel(); !ok {
		v := emailchannel.DefaultPrivacyLevel
		_c.mutation.SetPrivacyLevel(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := emailchannel.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Visible(); !ok {
		v := emailchannel.DefaultVisible
		_c.mutation.SetVisible(v)
	}
	if _, ok := _c.mutation.Healthy(); !ok {
		v := emailchannel.DefaultHealthy
		_c.mutation.SetHealthy(v)
	}
	if _, ok := _c.mutation.SalePrice(); !ok {
		v := emailchannel.DefaultSalePrice
		_c.mutation.SetSalePrice(v)
	}
	if _, ok := _c.mutation.OrderTTLSeconds(); !ok {
		v := emailchannel.DefaultOrderTTLSeconds
		_c.mutation.SetOrderTTLSeconds(v)
	}
	if _, ok := _c.mutation.CapturePolicy(); !ok {
		v := emailchannel.DefaultCapturePolicy
		_c.mutation.SetCapturePolicy(v)
	}
	if _, ok := _c.mutation.RefundPolicy(); !ok {
		v := emailchannel.DefaultRefundPolicy
		_c.mutation.SetRefundPolicy(v)
	}
	if _, ok := _c.mutation.MaxProviderRequestsPerOrder(); !ok {
		v := emailchannel.DefaultMaxProviderRequestsPerOrder
		_c.mutation.SetMaxProviderRequestsPerOrder(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := emailchannel.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EmailChannelCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "EmailChannel.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := emailchannel.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "EmailChannel.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PublicName(); !ok {
		return &ValidationError{Name: "public_name", err: errors.New(`ent: missing required field "EmailChannel.public_name"`)}
	}
	if v, ok := _c.mutation.PublicName(); ok {
		if err := emailchannel.PublicNameValidator(v); err != nil {
			return &ValidationError{Name: "public_name", err: fmt.Errorf(`ent: validator failed for field "EmailChannel.public_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "EmailChannel.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := emailchannel.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "EmailChannel.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderID(); !ok {
		return &ValidationError{Name: "provider_id", err: errors.New(`ent: missing required field "EmailChannel.provider_id"`)}
	}
	if _, ok := _c.mutation.EmailType(); !ok {
		return &ValidationError{Name: "email_type", err: errors.New(`ent: missing required field "EmailChannel.email_type"`)}
	}
	if v, ok := _c.mutation.EmailType(); ok {
		if err := emailchannel.EmailTypeValidator(v); err != nil {
			return &ValidationError{Name: "email_type", err: fmt.Errorf(`ent: validator failed for field "EmailChannel.email_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PrivacyLevel(); !ok {
		return &ValidationError{Name: "privacy_level", err: errors.New(`ent: missing required field "EmailChannel.privacy_level"`)}
	}
	if v, ok := _c.mutation.PrivacyLevel(); ok {
		if err := emailchannel.PrivacyLevelValidator(v); err != nil {
			return &ValidationError{Name: "privacy_level", err: fmt.Errorf(`ent: validator failed for field "EmailChannel.privacy_level": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "EmailChannel.enabled"`)}
	}
	if _, ok := _c.mutation.Visible(); !ok {
		return &ValidationError{Name: "visible", err: errors.New(`ent: missing required field "EmailChannel.visible"`)}
	}
	if _, ok := _c.mutation.Healthy(); !ok {
		return &ValidationError{Name: "healthy", err: errors.New(`ent: missing required field "EmailChannel.healthy"`)}
	}
	if _, ok := _c.mutation.SalePrice(); !ok {
		return &ValidationError{Name: "sale_price", err: errors.New(`ent: missing required field "EmailChannel.sale_price"`)}
	}
	if _, ok := _c.mutation.OrderTTLSeconds(); !ok {
		return &ValidationError{Name: "order_ttl_seconds", err: errors.New(`ent: missing required field "EmailChannel.order_ttl_seconds"`)}
	}
	if _, ok := _c.mutation.CapturePolicy(); !ok {
		return &ValidationError{Name: "capture_policy", err: errors.New(`ent: missing required field "EmailChannel.capture_policy"`)}
	}
	if v, ok := _c.mutation.CapturePolicy(); ok {
		if err := emailchannel.CapturePolicyValidator(v); err != nil {
			return &ValidationError{Name: "capture_policy", err: fmt.Errorf(`ent: validator failed for field "EmailChannel.capture_policy": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RefundPolicy(); !ok {
		return &ValidationError{Name: "refund_policy", err: errors.New(`ent: missing required field "EmailChannel.refund_policy"`)}
	}
	if v, ok := _c.mutation.RefundPolicy(); ok {
		if err := emailchannel.RefundPolicyValidator(v); err != nil {
			return &ValidationError{Name: "refund_policy", err: fmt.Errorf(`ent: validator failed for field "EmailChannel.refund_policy": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PollingBackoff(); !ok {
		return &ValidationError{Name: "polling_backoff", err: errors.New(`ent: missing required field "EmailChannel.polling_backoff"`)}
	}
	if _, ok := _c.mutation.MaxProviderRequestsPerOrder(); !ok {
		return &ValidationError{Name: "max_provider_requests_per_order", err: errors.New(`ent: missing required field "EmailChannel.max_provider_requests_per_order"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "EmailChannel.sort_order"`)}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "EmailChannel.metadata"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EmailChannel.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EmailChannel.updated_at"`)}
	}
	return nil
}

func (_c *EmailChannelCreate) sqlSave(ctx context.Context) (*EmailChannel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EmailChannelCreate) createSpec() (*EmailChannel, *sqlgraph.CreateSpec) {
	var (
		_node = &EmailChannel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(emailchannel.Table, sqlgraph.NewFieldSpec(emailchannel.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(emailchannel.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.PublicName(); ok {
		_spec.SetField(emailchannel.FieldPublicName, field.TypeString, value)
		_node.PublicName = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(emailchannel.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.ProviderID(); ok {
		_spec.SetField(emailchannel.FieldProviderID, field.TypeInt64, value)
		_node.ProviderID = value
	}
	if value, ok := _c.mutation.EmailType(); ok {
		_spec.SetField(emailchannel.FieldEmailType, field.TypeString, value)
		_node.EmailType = value
	}
	if value, ok := _c.mutation.PrivacyLevel(); ok {
		_spec.SetField(emailchannel.FieldPrivacyLevel, field.TypeString, value)
		_node.PrivacyLevel = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(emailchannel.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Visible(); ok {
		_spec.SetField(emailchannel.FieldVisible, field.TypeBool, value)
		_node.Visible = value
	}
	if value, ok := _c.mutation.Healthy(); ok {
		_spec.SetField(emailchannel.FieldHealthy, field.TypeBool, value)
		_node.Healthy = value
	}
	if value, ok := _c.mutation.SalePrice(); ok {
		_spec.SetField(emailchannel.FieldSalePrice, field.TypeFloat64, value)
		_node.SalePrice = value
	}
	if value, ok := _c.mutation.OrderTTLSeconds(); ok {
		_spec.SetField(emailchannel.FieldOrderTTLSeconds, field.TypeInt, value)
		_node.OrderTTLSeconds = value
	}
	if value, ok := _c.mutation.CapturePolicy(); ok {
		_spec.SetField(emailchannel.FieldCapturePolicy, field.TypeString, value)
		_node.CapturePolicy = value
	}
	if value, ok := _c.mutation.RefundPolicy(); ok {
		_spec.SetField(emailchannel.FieldRefundPolicy, field.TypeString, value)
		_node.RefundPolicy = value
	}
	if value, ok := _c.mutation.PollingBackoff(); ok {
		_spec.SetField(emailchannel.FieldPollingBackoff, field.TypeJSON, value)
		_node.PollingBackoff = value
	}
	if value, ok := _c.mutation.MaxProviderRequestsPerOrder(); ok {
		_spec.SetField(emailchannel.FieldMaxProviderRequestsPerOrder, field.TypeInt, value)
		_node.MaxProviderRequestsPerOrder = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(emailchannel.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(emailchannel.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(emailchannel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(emailchannel.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EmailChannel.Create().
//		SetCode(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EmailChannelUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *EmailChannelCreate) OnConflict(opts ...sql.ConflictOption) *EmailChannelUpsertOne {
	_c.conflict = opts
	return &EmailChannelUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EmailChannel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EmailChannelCreate) OnConflictColumns(columns ...string) *EmailChannelUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EmailChannelUpsertOne{
		create: _c,
	}
}

type (
	// EmailChannelUpsertOne is the builder for "upsert"-ing
	//  one EmailChannel node.
	EmailChannelUpsertOne struct {
		create *EmailChannelCreate
	}

	// EmailChannelUpsert is the "OnConflict" setter.
	EmailChannelUpsert struct {
		*sql.UpdateSet
	}
)

// SetCode sets the "code" field.
func (u *EmailChannelUpsert) SetCode(v string) *EmailChannelUpsert {
	u.Set(emailchannel.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *EmailChannelUpsert) UpdateCode() *EmailChannelUpsert {
	u.SetExcluded(emailchannel.FieldCode)
	return u
}

// SetPublicName sets the "public_name" field.
func (u *EmailChannelUpsert) SetPublicName(v string) *EmailChannelUpsert {
	u.Set(emailchannel.FieldPublicName, v)
	return u
}

// UpdatePublicName sets the "public_name" field to the value that was provided on create.
func (u *EmailChannelUpsert) UpdatePublicName() *EmailChannelUpsert {
	u.SetExcluded(emailchannel.FieldPublicName)
	return u
}

// SetRole sets the "role" field.
func (u *EmailChannelUpsert) SetRole(v string) *EmailChannelUpsert {
	u.Set(emailchannel.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *EmailChannelUpsert) UpdateRole() *EmailChannelUpsert {
	u.SetExcluded(emailchannel.FieldRole)
	return u
}

// SetProviderID sets the "provider_id" field.
func (u *EmailChannelUpsert) SetProviderID(v int64) *EmailChannelUpsert {
	u.Set(emailchannel.FieldProviderID, v)
	return u
}

// UpdateProviderID sets the "provider_id" field to the value that was provided on create.
func (u *EmailChannelUpsert) UpdateProviderID() *EmailChannelUpsert {
	u.SetExcluded(emailchannel.FieldProviderID)
	return u
}

// AddProviderID adds v to the "provider_id" field.
func (u *EmailChannelUpsert) AddProviderID(v int64) *EmailChannelUpsert {
	u.Add(emailchannel.FieldProviderID, v)
	return u
}

// SetEmailType sets the "email_type" field.
func (u *EmailChannelUpsert) SetEmailType(v string) *EmailChannelUpsert {
	u.Set(emailchannel.FieldEmailType, v)
	return u
}

// UpdateEmailType sets the "email_type" field to the value that was provided on create.
func (u *EmailChannelUpsert) UpdateEmailType() *EmailChannelUpsert {
	u.SetExcluded(emailchannel.FieldEmailType)
	return u
}

// SetPrivacyLevel sets the "privacy_level" field.
func (u *EmailChannelUpsert) SetPrivacyLevel(v string) *EmailChannelUpsert {
	u.Set(emailchannel.FieldPrivacyLevel, v)
	return u
}

// UpdatePrivacyLevel sets the "privacy_level" field to the value that was provided on create.
func (u *EmailChannelUpsert) UpdatePrivacyLevel() *EmailChannelUpsert {
	u.SetExcluded(emailchannel.FieldPrivacyLevel)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *EmailChannelUpsert) SetEnabled(v bool) *EmailChannelUpsert {
	u.Set(emailchannel.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *EmailChannelUpsert) UpdateEnabled() *EmailChannelUpsert {
	u.SetExcluded(emailchannel.FieldEnabled)
	return u
}

// SetVisible sets the "visible" field.
func (u *EmailChannelUpsert) SetVisible(v bool) *EmailChannelUpsert {
	u.Set(emailchannel.FieldVisible, v)
	return u
}

// UpdateVisible sets the "visible" field to the value that was provided on create.
func (u *EmailChannelUpsert) UpdateVisible() *EmailChannelUpsert {
	u.SetExcluded(emailchannel.FieldVisible)
	return u
}

// SetHealthy sets the "healthy" field.
func (u *EmailChannelUpsert) SetHealthy(v bool) *EmailChannelUpsert {
	u.Set(emailchannel.FieldHealthy, v)
	return u
}

// UpdateHealthy sets the "healthy" field to the value that was provided on create.
func (u *EmailChannelUpsert) UpdateHealthy() *EmailChannelUpsert {
	u.SetExcluded(emailchannel.FieldHealthy)
	return u
}

// SetSalePrice sets the "sale_price" field.
func (u *EmailChannelUpsert) SetSalePrice(v float64) *EmailChannelUpsert {
	u.Set(emailchannel.FieldSalePrice, v)
	return u
}

// UpdateSalePrice sets the "sale_price" field to the value that was provided on create.
func (u *EmailChannelUpsert) UpdateSalePrice() *EmailChannelUpsert {
	u.SetExcluded(emailchannel.FieldSalePrice)
	return u
}

// AddSalePrice adds v to the "sale_price" field.
func (u *EmailChannelUpsert) AddSalePrice(v float64) *EmailChannelUpsert {
	u.Add(emailchannel.FieldSalePrice, v)
	return u
}

// SetOrderTTLSeconds sets the "order_ttl_seconds" field.
func (u *EmailChannelUpsert) SetOrderTTLSeconds(v int) *EmailChannelUpsert {
	u.Set(emailchannel.FieldOrderTTLSeconds, v)
	return u
}

// UpdateOrderTTLSeconds sets the "order_ttl_seconds" field to the value that was provided on create.
func (u *EmailChannelUpsert) UpdateOrderTTLSeconds() *EmailChannelUpsert {
	u.SetExcluded(emailchannel.FieldOrderTTLSeconds)
	return u
}

// AddOrderTTLSeconds adds v to the "order_ttl_seconds" field.
func (u *EmailChannelUpsert) AddOrderTTLSeconds(v int) *EmailChannelUpsert {
	u.Add(emailchannel.FieldOrderTTLSeconds, v)
	return u
}

// SetCapturePolicy sets the "capture_policy" field.
func (u *EmailChannelUpsert) SetCapturePolicy(v string) *EmailChannelUpsert {
	u.Set(emailchannel.FieldCapturePolicy, v)
	return u
}

// UpdateCapturePolicy sets the "capture_policy" field to the value that was provided on create.
func (u *EmailChannelUpsert) UpdateCapturePolicy() *EmailChannelUpsert {
	u.SetExcluded(emailchannel.FieldCapturePolicy)
	return u
}

// SetRefundPolicy sets the "refund_policy" field.
func (u *EmailChannelUpsert) SetRefundPolicy(v string) *EmailChannelUpsert {
	u.Set(emailchannel.FieldRefundPolicy, v)
	return u
}

// UpdateRefundPolicy sets the "refund_policy" field to the value that was provided on create.
func (u *EmailChannelUpsert) UpdateRefundPolicy() *EmailChannelUpsert {
	u.SetExcluded(emailchannel.FieldRefundPolicy)
	return u
}

// SetPollingBackoff sets the "polling_backoff" field.
func (u *EmailChannelUpsert) SetPollingBackoff(v []int) *EmailChannelUpsert {
	u.Set(emailchannel.FieldPollingBackoff, v)
	return u
}

// UpdatePollingBackoff sets the "polling_backoff" field to the value that was provided on create.
func (u *EmailChannelUpsert) UpdatePollingBackoff() *EmailChannelUpsert {
	u.SetExcluded(emailchannel.FieldPollingBackoff)
	return u
}

// SetMaxProviderRequestsPerOrder sets the "max_provider_requests_per_order" field.
func (u *EmailChannelUpsert) SetMaxProviderRequestsPerOrder(v int) *EmailChannelUpsert {
	u.Set(emailchannel.FieldMaxProviderRequestsPerOrder, v)
	return u
}

// UpdateMaxProviderRequestsPerOrder sets the "max_provider_requests_per_order" field to the value that was provided on create.
func (u *EmailChannelUpsert) UpdateMaxProviderRequestsPerOrder() *EmailChannelUpsert {
	u.SetExcluded(emailchannel.FieldMaxProviderRequestsPerOrder)
	return u
}

// AddMaxProviderRequestsPerOrder adds v to the "max_provider_requests_per_order" field.
func (u *EmailChannelUpsert) AddMaxProviderRequestsPerOrder(v int) *EmailChannelUpsert {
	u.Add(emailchannel.FieldMaxProviderRequestsPerOrder, v)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *EmailChannelUpsert) SetSortOrder(v int) *EmailChannelUpsert {
	u.Set(emailchannel.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *EmailChannelUpsert) UpdateSortOrder() *EmailChannelUpsert {
	u.SetExcluded(emailchannel.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *EmailChannelUpsert) AddSortOrder(v int) *EmailChannelUpsert {
	u.Add(emailchannel.FieldSortOrder, v)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *EmailChannelUpsert) SetMetadata(v map[string]interface{}) *EmailChannelUpsert {
	u.Set(emailchannel.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *EmailChannelUpsert) UpdateMetadata() *EmailChannelUpsert {
	u.SetExcluded(emailchannel.FieldMetadata)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *EmailChannelUpsert) SetCreatedAt(v time.Time) *EmailChannelUpsert {
	u.Set(emailchannel.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *EmailChannelUpsert) UpdateCreatedAt() *EmailChannelUpsert {
	u.SetExcluded(emailchannel.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EmailChannelUpsert) SetUpdatedAt(v time.Time) *EmailChannelUpsert {
	u.Set(emailchannel.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EmailChannelUpsert) UpdateUpdatedAt() *EmailChannelUpsert {
	u.SetExcluded(emailchannel.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.EmailChannel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EmailChannelUpsertOne) UpdateNewValues() *EmailChannelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EmailChannel.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EmailChannelUpsertOne) Ignore() *EmailChannelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EmailChannelUpsertOne) DoNothing() *EmailChannelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EmailChannelCreate.OnConflict
// documentation for more info.
func (u *EmailChannelUpsertOne) Update(set func(*EmailChannelUpsert)) *EmailChannelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EmailChannelUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *EmailChannelUpsertOne) SetCode(v string) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *EmailChannelUpsertOne) UpdateCode() *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateCode()
	})
}

// SetPublicName sets the "public_name" field.
func (u *EmailChannelUpsertOne) SetPublicName(v string) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetPublicName(v)
	})
}

// UpdatePublicName sets the "public_name" field to the value that was provided on create.
func (u *EmailChannelUpsertOne) UpdatePublicName() *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdatePublicName()
	})
}

// SetRole sets the "role" field.
func (u *EmailChannelUpsertOne) SetRole(v string) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *EmailChannelUpsertOne) UpdateRole() *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateRole()
	})
}

// SetProviderID sets the "provider_id" field.
func (u *EmailChannelUpsertOne) SetProviderID(v int64) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetProviderID(v)
	})
}

// AddProviderID adds v to the "provider_id" field.
func (u *EmailChannelUpsertOne) AddProviderID(v int64) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.AddProviderID(v)
	})
}

// UpdateProviderID sets the "provider_id" field to the value that was provided on create.
func (u *EmailChannelUpsertOne) UpdateProviderID() *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateProviderID()
	})
}

// SetEmailType sets the "email_type" field.
func (u *EmailChannelUpsertOne) SetEmailType(v string) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetEmailType(v)
	})
}

// UpdateEmailType sets the "email_type" field to the value that was provided on create.
func (u *EmailChannelUpsertOne) UpdateEmailType() *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateEmailType()
	})
}

// SetPrivacyLevel sets the "privacy_level" field.
func (u *EmailChannelUpsertOne) SetPrivacyLevel(v string) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetPrivacyLevel(v)
	})
}

// UpdatePrivacyLevel sets the "privacy_level" field to the value that was provided on create.
func (u *EmailChannelUpsertOne) UpdatePrivacyLevel() *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdatePrivacyLevel()
	})
}

// SetEnabled sets the "enabled" field.
func (u *EmailChannelUpsertOne) SetEnabled(v bool) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *EmailChannelUpsertOne) UpdateEnabled() *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateEnabled()
	})
}

// SetVisible sets the "visible" field.
func (u *EmailChannelUpsertOne) SetVisible(v bool) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetVisible(v)
	})
}

// UpdateVisible sets the "visible" field to the value that was provided on create.
func (u *EmailChannelUpsertOne) UpdateVisible() *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateVisible()
	})
}

// SetHealthy sets the "healthy" field.
func (u *EmailChannelUpsertOne) SetHealthy(v bool) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetHealthy(v)
	})
}

// UpdateHealthy sets the "healthy" field to the value that was provided on create.
func (u *EmailChannelUpsertOne) UpdateHealthy() *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateHealthy()
	})
}

// SetSalePrice sets the "sale_price" field.
func (u *EmailChannelUpsertOne) SetSalePrice(v float64) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetSalePrice(v)
	})
}

// AddSalePrice adds v to the "sale_price" field.
func (u *EmailChannelUpsertOne) AddSalePrice(v float64) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.AddSalePrice(v)
	})
}

// UpdateSalePrice sets the "sale_price" field to the value that was provided on create.
func (u *EmailChannelUpsertOne) UpdateSalePrice() *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateSalePrice()
	})
}

// SetOrderTTLSeconds sets the "order_ttl_seconds" field.
func (u *EmailChannelUpsertOne) SetOrderTTLSeconds(v int) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetOrderTTLSeconds(v)
	})
}

// AddOrderTTLSeconds adds v to the "order_ttl_seconds" field.
func (u *EmailChannelUpsertOne) AddOrderTTLSeconds(v int) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.AddOrderTTLSeconds(v)
	})
}

// UpdateOrderTTLSeconds sets the "order_ttl_seconds" field to the value that was provided on create.
func (u *EmailChannelUpsertOne) UpdateOrderTTLSeconds() *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateOrderTTLSeconds()
	})
}

// SetCapturePolicy sets the "capture_policy" field.
func (u *EmailChannelUpsertOne) SetCapturePolicy(v string) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetCapturePolicy(v)
	})
}

// UpdateCapturePolicy sets the "capture_policy" field to the value that was provided on create.
func (u *EmailChannelUpsertOne) UpdateCapturePolicy() *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateCapturePolicy()
	})
}

// SetRefundPolicy sets the "refund_policy" field.
func (u *EmailChannelUpsertOne) SetRefundPolicy(v string) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetRefundPolicy(v)
	})
}

// UpdateRefundPolicy sets the "refund_policy" field to the value that was provided on create.
func (u *EmailChannelUpsertOne) UpdateRefundPolicy() *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateRefundPolicy()
	})
}

// SetPollingBackoff sets the "polling_backoff" field.
func (u *EmailChannelUpsertOne) SetPollingBackoff(v []int) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetPollingBackoff(v)
	})
}

// UpdatePollingBackoff sets the "polling_backoff" field to the value that was provided on create.
func (u *EmailChannelUpsertOne) UpdatePollingBackoff() *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdatePollingBackoff()
	})
}

// SetMaxProviderRequestsPerOrder sets the "max_provider_requests_per_order" field.
func (u *EmailChannelUpsertOne) SetMaxProviderRequestsPerOrder(v int) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetMaxProviderRequestsPerOrder(v)
	})
}

// AddMaxProviderRequestsPerOrder adds v to the "max_provider_requests_per_order" field.
func (u *EmailChannelUpsertOne) AddMaxProviderRequestsPerOrder(v int) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.AddMaxProviderRequestsPerOrder(v)
	})
}

// UpdateMaxProviderRequestsPerOrder sets the "max_provider_requests_per_order" field to the value that was provided on create.
func (u *EmailChannelUpsertOne) UpdateMaxProviderRequestsPerOrder() *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateMaxProviderRequestsPerOrder()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *EmailChannelUpsertOne) SetSortOrder(v int) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *EmailChannelUpsertOne) AddSortOrder(v int) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *EmailChannelUpsertOne) UpdateSortOrder() *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateSortOrder()
	})
}

// SetMetadata sets the "metadata" field.
func (u *EmailChannelUpsertOne) SetMetadata(v map[string]interface{}) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *EmailChannelUpsertOne) UpdateMetadata() *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateMetadata()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *EmailChannelUpsertOne) SetCreatedAt(v time.Time) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *EmailChannelUpsertOne) UpdateCreatedAt() *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EmailChannelUpsertOne) SetUpdatedAt(v time.Time) *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EmailChannelUpsertOne) UpdateUpdatedAt() *EmailChannelUpsertOne {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *EmailChannelUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EmailChannelCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EmailChannelUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EmailChannelUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EmailChannelUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EmailChannelCreateBulk is the builder for creating many EmailChannel entities in bulk.
type EmailChannelCreateBulk struct {
	config
	err      error
	builders []*EmailChannelCreate
	conflict []sql.ConflictOption
}

// Save creates the EmailChannel entities in the database.
func (_c *EmailChannelCreateBulk) Save(ctx context.Context) ([]*EmailChannel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EmailChannel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmailChannelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EmailChannelCreateBulk) SaveX(ctx context.Context) []*EmailChannel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailChannelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailChannelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EmailChannel.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EmailChannelUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *EmailChannelCreateBulk) OnConflict(opts ...sql.ConflictOption) *EmailChannelUpsertBulk {
	_c.conflict = opts
	return &EmailChannelUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EmailChannel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EmailChannelCreateBulk) OnConflictColumns(columns ...string) *EmailChannelUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EmailChannelUpsertBulk{
		create: _c,
	}
}

// EmailChannelUpsertBulk is the builder for "upsert"-ing
// a bulk of EmailChannel nodes.
type EmailChannelUpsertBulk struct {
	create *EmailChannelCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EmailChannel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EmailChannelUpsertBulk) UpdateNewValues() *EmailChannelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EmailChannel.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EmailChannelUpsertBulk) Ignore() *EmailChannelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EmailChannelUpsertBulk) DoNothing() *EmailChannelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EmailChannelCreateBulk.OnConflict
// documentation for more info.
func (u *EmailChannelUpsertBulk) Update(set func(*EmailChannelUpsert)) *EmailChannelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EmailChannelUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *EmailChannelUpsertBulk) SetCode(v string) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *EmailChannelUpsertBulk) UpdateCode() *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateCode()
	})
}

// SetPublicName sets the "public_name" field.
func (u *EmailChannelUpsertBulk) SetPublicName(v string) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetPublicName(v)
	})
}

// UpdatePublicName sets the "public_name" field to the value that was provided on create.
func (u *EmailChannelUpsertBulk) UpdatePublicName() *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdatePublicName()
	})
}

// SetRole sets the "role" field.
func (u *EmailChannelUpsertBulk) SetRole(v string) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *EmailChannelUpsertBulk) UpdateRole() *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateRole()
	})
}

// SetProviderID sets the "provider_id" field.
func (u *EmailChannelUpsertBulk) SetProviderID(v int64) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetProviderID(v)
	})
}

// AddProviderID adds v to the "provider_id" field.
func (u *EmailChannelUpsertBulk) AddProviderID(v int64) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.AddProviderID(v)
	})
}

// UpdateProviderID sets the "provider_id" field to the value that was provided on create.
func (u *EmailChannelUpsertBulk) UpdateProviderID() *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateProviderID()
	})
}

// SetEmailType sets the "email_type" field.
func (u *EmailChannelUpsertBulk) SetEmailType(v string) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetEmailType(v)
	})
}

// UpdateEmailType sets the "email_type" field to the value that was provided on create.
func (u *EmailChannelUpsertBulk) UpdateEmailType() *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateEmailType()
	})
}

// SetPrivacyLevel sets the "privacy_level" field.
func (u *EmailChannelUpsertBulk) SetPrivacyLevel(v string) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetPrivacyLevel(v)
	})
}

// UpdatePrivacyLevel sets the "privacy_level" field to the value that was provided on create.
func (u *EmailChannelUpsertBulk) UpdatePrivacyLevel() *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdatePrivacyLevel()
	})
}

// SetEnabled sets the "enabled" field.
func (u *EmailChannelUpsertBulk) SetEnabled(v bool) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *EmailChannelUpsertBulk) UpdateEnabled() *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateEnabled()
	})
}

// SetVisible sets the "visible" field.
func (u *EmailChannelUpsertBulk) SetVisible(v bool) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetVisible(v)
	})
}

// UpdateVisible sets the "visible" field to the value that was provided on create.
func (u *EmailChannelUpsertBulk) UpdateVisible() *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateVisible()
	})
}

// SetHealthy sets the "healthy" field.
func (u *EmailChannelUpsertBulk) SetHealthy(v bool) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetHealthy(v)
	})
}

// UpdateHealthy sets the "healthy" field to the value that was provided on create.
func (u *EmailChannelUpsertBulk) UpdateHealthy() *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateHealthy()
	})
}

// SetSalePrice sets the "sale_price" field.
func (u *EmailChannelUpsertBulk) SetSalePrice(v float64) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetSalePrice(v)
	})
}

// AddSalePrice adds v to the "sale_price" field.
func (u *EmailChannelUpsertBulk) AddSalePrice(v float64) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.AddSalePrice(v)
	})
}

// UpdateSalePrice sets the "sale_price" field to the value that was provided on create.
func (u *EmailChannelUpsertBulk) UpdateSalePrice() *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateSalePrice()
	})
}

// SetOrderTTLSeconds sets the "order_ttl_seconds" field.
func (u *EmailChannelUpsertBulk) SetOrderTTLSeconds(v int) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetOrderTTLSeconds(v)
	})
}

// AddOrderTTLSeconds adds v to the "order_ttl_seconds" field.
func (u *EmailChannelUpsertBulk) AddOrderTTLSeconds(v int) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.AddOrderTTLSeconds(v)
	})
}

// UpdateOrderTTLSeconds sets the "order_ttl_seconds" field to the value that was provided on create.
func (u *EmailChannelUpsertBulk) UpdateOrderTTLSeconds() *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateOrderTTLSeconds()
	})
}

// SetCapturePolicy sets the "capture_policy" field.
func (u *EmailChannelUpsertBulk) SetCapturePolicy(v string) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetCapturePolicy(v)
	})
}

// UpdateCapturePolicy sets the "capture_policy" field to the value that was provided on create.
func (u *EmailChannelUpsertBulk) UpdateCapturePolicy() *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateCapturePolicy()
	})
}

// SetRefundPolicy sets the "refund_policy" field.
func (u *EmailChannelUpsertBulk) SetRefundPolicy(v string) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetRefundPolicy(v)
	})
}

// UpdateRefundPolicy sets the "refund_policy" field to the value that was provided on create.
func (u *EmailChannelUpsertBulk) UpdateRefundPolicy() *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateRefundPolicy()
	})
}

// SetPollingBackoff sets the "polling_backoff" field.
func (u *EmailChannelUpsertBulk) SetPollingBackoff(v []int) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetPollingBackoff(v)
	})
}

// UpdatePollingBackoff sets the "polling_backoff" field to the value that was provided on create.
func (u *EmailChannelUpsertBulk) UpdatePollingBackoff() *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdatePollingBackoff()
	})
}

// SetMaxProviderRequestsPerOrder sets the "max_provider_requests_per_order" field.
func (u *EmailChannelUpsertBulk) SetMaxProviderRequestsPerOrder(v int) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetMaxProviderRequestsPerOrder(v)
	})
}

// AddMaxProviderRequestsPerOrder adds v to the "max_provider_requests_per_order" field.
func (u *EmailChannelUpsertBulk) AddMaxProviderRequestsPerOrder(v int) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.AddMaxProviderRequestsPerOrder(v)
	})
}

// UpdateMaxProviderRequestsPerOrder sets the "max_provider_requests_per_order" field to the value that was provided on create.
func (u *EmailChannelUpsertBulk) UpdateMaxProviderRequestsPerOrder() *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateMaxProviderRequestsPerOrder()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *EmailChannelUpsertBulk) SetSortOrder(v int) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *EmailChannelUpsertBulk) AddSortOrder(v int) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *EmailChannelUpsertBulk) UpdateSortOrder() *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateSortOrder()
	})
}

// SetMetadata sets the "metadata" field.
func (u *EmailChannelUpsertBulk) SetMetadata(v map[string]interface{}) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *EmailChannelUpsertBulk) UpdateMetadata() *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateMetadata()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *EmailChannelUpsertBulk) SetCreatedAt(v time.Time) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *EmailChannelUpsertBulk) UpdateCreatedAt() *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EmailChannelUpsertBulk) SetUpdatedAt(v time.Time) *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EmailChannelUpsertBulk) UpdateUpdatedAt() *EmailChannelUpsertBulk {
	return u.Update(func(s *EmailChannelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *EmailChannelUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EmailChannelCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EmailChannelCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EmailChannelUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
