// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/resourcenotification"
)

// ResourceNotificationUpdate is the builder for updating ResourceNotification entities.
type ResourceNotificationUpdate struct {
	config
	hooks    []Hook
	mutation *ResourceNotificationMutation
}

// Where appends a list predicates to the ResourceNotificationUpdate builder.
func (_u *ResourceNotificationUpdate) Where(ps ...predicate.ResourceNotification) *ResourceNotificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ResourceNotificationUpdate) SetUserID(v int64) *ResourceNotificationUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ResourceNotificationUpdate) SetNillableUserID(v *int64) *ResourceNotificationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ResourceNotificationUpdate) AddUserID(v int64) *ResourceNotificationUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *ResourceNotificationUpdate) SetActorID(v int64) *ResourceNotificationUpdate {
	_u.mutation.ResetActorID()
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *ResourceNotificationUpdate) SetNillableActorID(v *int64) *ResourceNotificationUpdate {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// AddActorID adds value to the "actor_id" field.
func (_u *ResourceNotificationUpdate) AddActorID(v int64) *ResourceNotificationUpdate {
	_u.mutation.AddActorID(v)
	return _u
}

// SetActorUsername sets the "actor_username" field.
func (_u *ResourceNotificationUpdate) SetActorUsername(v string) *ResourceNotificationUpdate {
	_u.mutation.SetActorUsername(v)
	return _u
}

// SetNillableActorUsername sets the "actor_username" field if the given value is not nil.
func (_u *ResourceNotificationUpdate) SetNillableActorUsername(v *string) *ResourceNotificationUpdate {
	if v != nil {
		_u.SetActorUsername(*v)
	}
	return _u
}

// SetActorRole sets the "actor_role" field.
func (_u *ResourceNotificationUpdate) SetActorRole(v string) *ResourceNotificationUpdate {
	_u.mutation.SetActorRole(v)
	return _u
}

// SetNillableActorRole sets the "actor_role" field if the given value is not nil.
func (_u *ResourceNotificationUpdate) SetNillableActorRole(v *string) *ResourceNotificationUpdate {
	if v != nil {
		_u.SetActorRole(*v)
	}
	return _u
}

// SetPostID sets the "post_id" field.
func (_u *ResourceNotificationUpdate) SetPostID(v int64) *ResourceNotificationUpdate {
	_u.mutation.ResetPostID()
	_u.mutation.SetPostID(v)
	return _u
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (_u *ResourceNotificationUpdate) SetNillablePostID(v *int64) *ResourceNotificationUpdate {
	if v != nil {
		_u.SetPostID(*v)
	}
	return _u
}

// AddPostID adds value to the "post_id" field.
func (_u *ResourceNotificationUpdate) AddPostID(v int64) *ResourceNotificationUpdate {
	_u.mutation.AddPostID(v)
	return _u
}

// SetCommentID sets the "comment_id" field.
func (_u *ResourceNotificationUpdate) SetCommentID(v int64) *ResourceNotificationUpdate {
	_u.mutation.ResetCommentID()
	_u.mutation.SetCommentID(v)
	return _u
}

// SetNillableCommentID sets the "comment_id" field if the given value is not nil.
func (_u *ResourceNotificationUpdate) SetNillableCommentID(v *int64) *ResourceNotificationUpdate {
	if v != nil {
		_u.SetCommentID(*v)
	}
	return _u
}

// AddCommentID adds value to the "comment_id" field.
func (_u *ResourceNotificationUpdate) AddCommentID(v int64) *ResourceNotificationUpdate {
	_u.mutation.AddCommentID(v)
	return _u
}

// ClearCommentID clears the value of the "comment_id" field.
func (_u *ResourceNotificationUpdate) ClearCommentID() *ResourceNotificationUpdate {
	_u.mutation.ClearCommentID()
	return _u
}

// SetKind sets the "kind" field.
func (_u *ResourceNotificationUpdate) SetKind(v string) *ResourceNotificationUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ResourceNotificationUpdate) SetNillableKind(v *string) *ResourceNotificationUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetRead sets the "read" field.
func (_u *ResourceNotificationUpdate) SetRead(v bool) *ResourceNotificationUpdate {
	_u.mutation.SetRead(v)
	return _u
}

// SetNillableRead sets the "read" field if the given value is not nil.
func (_u *ResourceNotificationUpdate) SetNillableRead(v *bool) *ResourceNotificationUpdate {
	if v != nil {
		_u.SetRead(*v)
	}
	return _u
}

// Mutation returns the ResourceNotificationMutation object of the builder.
func (_u *ResourceNotificationUpdate) Mutation() *ResourceNotificationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResourceNotificationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceNotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResourceNotificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceNotificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourceNotificationUpdate) check() error {
	if v, ok := _u.mutation.ActorUsername(); ok {
		if err := resourcenotification.ActorUsernameValidator(v); err != nil {
			return &ValidationError{Name: "actor_username", err: fmt.Errorf(`ent: validator failed for field "ResourceNotification.actor_username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActorRole(); ok {
		if err := resourcenotification.ActorRoleValidator(v); err != nil {
			return &ValidationError{Name: "actor_role", err: fmt.Errorf(`ent: validator failed for field "ResourceNotification.actor_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := resourcenotification.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "ResourceNotification.kind": %w`, err)}
		}
	}
	return nil
}

func (_u *ResourceNotificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resourcenotification.Table, resourcenotification.Columns, sqlgraph.NewFieldSpec(resourcenotification.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(resourcenotification.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(resourcenotification.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(resourcenotification.FieldActorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActorID(); ok {
		_spec.AddField(resourcenotification.FieldActorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ActorUsername(); ok {
		_spec.SetField(resourcenotification.FieldActorUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorRole(); ok {
		_spec.SetField(resourcenotification.FieldActorRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.PostID(); ok {
		_spec.SetField(resourcenotification.FieldPostID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPostID(); ok {
		_spec.AddField(resourcenotification.FieldPostID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CommentID(); ok {
		_spec.SetField(resourcenotification.FieldCommentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCommentID(); ok {
		_spec.AddField(resourcenotification.FieldCommentID, field.TypeInt64, value)
	}
	if _u.mutation.CommentIDCleared() {
		_spec.ClearField(resourcenotification.FieldCommentID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(resourcenotification.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Read(); ok {
		_spec.SetField(resourcenotification.FieldRead, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourcenotification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResourceNotificationUpdateOne is the builder for updating a single ResourceNotification entity.
type ResourceNotificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ResourceNotificationMutation
}

// SetUserID sets the "user_id" field.
func (_u *ResourceNotificationUpdateOne) SetUserID(v int64) *ResourceNotificationUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ResourceNotificationUpdateOne) SetNillableUserID(v *int64) *ResourceNotificationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ResourceNotificationUpdateOne) AddUserID(v int64) *ResourceNotificationUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *ResourceNotificationUpdateOne) SetActorID(v int64) *ResourceNotificationUpdateOne {
	_u.mutation.ResetActorID()
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *ResourceNotificationUpdateOne) SetNillableActorID(v *int64) *ResourceNotificationUpdateOne {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// AddActorID adds value to the "actor_id" field.
func (_u *ResourceNotificationUpdateOne) AddActorID(v int64) *ResourceNotificationUpdateOne {
	_u.mutation.AddActorID(v)
	return _u
}

// SetActorUsername sets the "actor_username" field.
func (_u *ResourceNotificationUpdateOne) SetActorUsername(v string) *ResourceNotificationUpdateOne {
	_u.mutation.SetActorUsername(v)
	return _u
}

// SetNillableActorUsername sets the "actor_username" field if the given value is not nil.
func (_u *ResourceNotificationUpdateOne) SetNillableActorUsername(v *string) *ResourceNotificationUpdateOne {
	if v != nil {
		_u.SetActorUsername(*v)
	}
	return _u
}

// SetActorRole sets the "actor_role" field.
func (_u *ResourceNotificationUpdateOne) SetActorRole(v string) *ResourceNotificationUpdateOne {
	_u.mutation.SetActorRole(v)
	return _u
}

// SetNillableActorRole sets the "actor_role" field if the given value is not nil.
func (_u *ResourceNotificationUpdateOne) SetNillableActorRole(v *string) *ResourceNotificationUpdateOne {
	if v != nil {
		_u.SetActorRole(*v)
	}
	return _u
}

// SetPostID sets the "post_id" field.
func (_u *ResourceNotificationUpdateOne) SetPostID(v int64) *ResourceNotificationUpdateOne {
	_u.mutation.ResetPostID()
	_u.mutation.SetPostID(v)
	return _u
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (_u *ResourceNotificationUpdateOne) SetNillablePostID(v *int64) *ResourceNotificationUpdateOne {
	if v != nil {
		_u.SetPostID(*v)
	}
	return _u
}

// AddPostID adds value to the "post_id" field.
func (_u *ResourceNotificationUpdateOne) AddPostID(v int64) *ResourceNotificationUpdateOne {
	_u.mutation.AddPostID(v)
	return _u
}

// SetCommentID sets the "comment_id" field.
func (_u *ResourceNotificationUpdateOne) SetCommentID(v int64) *ResourceNotificationUpdateOne {
	_u.mutation.ResetCommentID()
	_u.mutation.SetCommentID(v)
	return _u
}

// SetNillableCommentID sets the "comment_id" field if the given value is not nil.
func (_u *ResourceNotificationUpdateOne) SetNillableCommentID(v *int64) *ResourceNotificationUpdateOne {
	if v != nil {
		_u.SetCommentID(*v)
	}
	return _u
}

// AddCommentID adds value to the "comment_id" field.
func (_u *ResourceNotificationUpdateOne) AddCommentID(v int64) *ResourceNotificationUpdateOne {
	_u.mutation.AddCommentID(v)
	return _u
}

// ClearCommentID clears the value of the "comment_id" field.
func (_u *ResourceNotificationUpdateOne) ClearCommentID() *ResourceNotificationUpdateOne {
	_u.mutation.ClearCommentID()
	return _u
}

// SetKind sets the "kind" field.
func (_u *ResourceNotificationUpdateOne) SetKind(v string) *ResourceNotificationUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ResourceNotificationUpdateOne) SetNillableKind(v *string) *ResourceNotificationUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetRead sets the "read" field.
func (_u *ResourceNotificationUpdateOne) SetRead(v bool) *ResourceNotificationUpdateOne {
	_u.mutation.SetRead(v)
	return _u
}

// SetNillableRead sets the "read" field if the given value is not nil.
func (_u *ResourceNotificationUpdateOne) SetNillableRead(v *bool) *ResourceNotificationUpdateOne {
	if v != nil {
		_u.SetRead(*v)
	}
	return _u
}

// Mutation returns the ResourceNotificationMutation object of the builder.
func (_u *ResourceNotificationUpdateOne) Mutation() *ResourceNotificationMutation {
	return _u.mutation
}

// Where appends a list predicates to the ResourceNotificationUpdate builder.
func (_u *ResourceNotificationUpdateOne) Where(ps ...predicate.ResourceNotification) *ResourceNotificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResourceNotificationUpdateOne) Select(field string, fields ...string) *ResourceNotificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ResourceNotification entity.
func (_u *ResourceNotificationUpdateOne) Save(ctx context.Context) (*ResourceNotification, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceNotificationUpdateOne) SaveX(ctx context.Context) *ResourceNotification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResourceNotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceNotificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourceNotificationUpdateOne) check() error {
	if v, ok := _u.mutation.ActorUsername(); ok {
		if err := resourcenotification.ActorUsernameValidator(v); err != nil {
			return &ValidationError{Name: "actor_username", err: fmt.Errorf(`ent: validator failed for field "ResourceNotification.actor_username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActorRole(); ok {
		if err := resourcenotification.ActorRoleValidator(v); err != nil {
			return &ValidationError{Name: "actor_role", err: fmt.Errorf(`ent: validator failed for field "ResourceNotification.actor_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := resourcenotification.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "ResourceNotification.kind": %w`, err)}
		}
	}
	return nil
}

func (_u *ResourceNotificationUpdateOne) sqlSave(ctx context.Context) (_node *ResourceNotification, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resourcenotification.Table, resourcenotification.Columns, sqlgraph.NewFieldSpec(resourcenotification.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ResourceNotification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resourcenotification.FieldID)
		for _, f := range fields {
			if !resourcenotification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != resourcenotification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(resourcenotification.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(resourcenotification.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(resourcenotification.FieldActorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActorID(); ok {
		_spec.AddField(resourcenotification.FieldActorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ActorUsername(); ok {
		_spec.SetField(resourcenotification.FieldActorUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorRole(); ok {
		_spec.SetField(resourcenotification.FieldActorRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.PostID(); ok {
		_spec.SetField(resourcenotification.FieldPostID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPostID(); ok {
		_spec.AddField(resourcenotification.FieldPostID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CommentID(); ok {
		_spec.SetField(resourcenotification.FieldCommentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCommentID(); ok {
		_spec.AddField(resourcenotification.FieldCommentID, field.TypeInt64, value)
	}
	if _u.mutation.CommentIDCleared() {
		_spec.ClearField(resourcenotification.FieldCommentID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(resourcenotification.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Read(); ok {
		_spec.SetField(resourcenotification.FieldRead, field.TypeBool, value)
	}
	_node = &ResourceNotification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourcenotification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
