// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/resourcecategory"
)

// ResourceCategoryUpdate is the builder for updating ResourceCategory entities.
type ResourceCategoryUpdate struct {
	config
	hooks    []Hook
	mutation *ResourceCategoryMutation
}

// Where appends a list predicates to the ResourceCategoryUpdate builder.
func (_u *ResourceCategoryUpdate) Where(ps ...predicate.ResourceCategory) *ResourceCategoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *ResourceCategoryUpdate) SetSlug(v string) *ResourceCategoryUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *ResourceCategoryUpdate) SetNillableSlug(v *string) *ResourceCategoryUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ResourceCategoryUpdate) SetName(v string) *ResourceCategoryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ResourceCategoryUpdate) SetNillableName(v *string) *ResourceCategoryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ResourceCategoryUpdate) SetDescription(v string) *ResourceCategoryUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ResourceCategoryUpdate) SetNillableDescription(v *string) *ResourceCategoryUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ResourceCategoryUpdate) SetSortOrder(v int) *ResourceCategoryUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ResourceCategoryUpdate) SetNillableSortOrder(v *int) *ResourceCategoryUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ResourceCategoryUpdate) AddSortOrder(v int) *ResourceCategoryUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ResourceCategoryUpdate) SetEnabled(v bool) *ResourceCategoryUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ResourceCategoryUpdate) SetNillableEnabled(v *bool) *ResourceCategoryUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResourceCategoryUpdate) SetUpdatedAt(v time.Time) *ResourceCategoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ResourceCategoryMutation object of the builder.
func (_u *ResourceCategoryUpdate) Mutation() *ResourceCategoryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResourceCategoryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceCategoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResourceCategoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceCategoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResourceCategoryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resourcecategory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourceCategoryUpdate) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := resourcecategory.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "ResourceCategory.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := resourcecategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ResourceCategory.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ResourceCategoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resourcecategory.Table, resourcecategory.Columns, sqlgraph.NewFieldSpec(resourcecategory.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(resourcecategory.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(resourcecategory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(resourcecategory.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(resourcecategory.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(resourcecategory.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(resourcecategory.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resourcecategory.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourcecategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResourceCategoryUpdateOne is the builder for updating a single ResourceCategory entity.
type ResourceCategoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ResourceCategoryMutation
}

// SetSlug sets the "slug" field.
func (_u *ResourceCategoryUpdateOne) SetSlug(v string) *ResourceCategoryUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *ResourceCategoryUpdateOne) SetNillableSlug(v *string) *ResourceCategoryUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ResourceCategoryUpdateOne) SetName(v string) *ResourceCategoryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ResourceCategoryUpdateOne) SetNillableName(v *string) *ResourceCategoryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ResourceCategoryUpdateOne) SetDescription(v string) *ResourceCategoryUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ResourceCategoryUpdateOne) SetNillableDescription(v *string) *ResourceCategoryUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ResourceCategoryUpdateOne) SetSortOrder(v int) *ResourceCategoryUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ResourceCategoryUpdateOne) SetNillableSortOrder(v *int) *ResourceCategoryUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ResourceCategoryUpdateOne) AddSortOrder(v int) *ResourceCategoryUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ResourceCategoryUpdateOne) SetEnabled(v bool) *ResourceCategoryUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ResourceCategoryUpdateOne) SetNillableEnabled(v *bool) *ResourceCategoryUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResourceCategoryUpdateOne) SetUpdatedAt(v time.Time) *ResourceCategoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ResourceCategoryMutation object of the builder.
func (_u *ResourceCategoryUpdateOne) Mutation() *ResourceCategoryMutation {
	return _u.mutation
}

// Where appends a list predicates to the ResourceCategoryUpdate builder.
func (_u *ResourceCategoryUpdateOne) Where(ps ...predicate.ResourceCategory) *ResourceCategoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResourceCategoryUpdateOne) Select(field string, fields ...string) *ResourceCategoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ResourceCategory entity.
func (_u *ResourceCategoryUpdateOne) Save(ctx context.Context) (*ResourceCategory, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceCategoryUpdateOne) SaveX(ctx context.Context) *ResourceCategory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResourceCategoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceCategoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResourceCategoryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resourcecategory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourceCategoryUpdateOne) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := resourcecategory.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "ResourceCategory.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := resourcecategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ResourceCategory.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ResourceCategoryUpdateOne) sqlSave(ctx context.Context) (_node *ResourceCategory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resourcecategory.Table, resourcecategory.Columns, sqlgraph.NewFieldSpec(resourcecategory.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ResourceCategory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resourcecategory.FieldID)
		for _, f := range fields {
			if !resourcecategory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != resourcecategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(resourcecategory.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(resourcecategory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(resourcecategory.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(resourcecategory.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(resourcecategory.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(resourcecategory.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resourcecategory.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ResourceCategory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourcecategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
