// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/resourcecomment"
)

// ResourceCommentUpdate is the builder for updating ResourceComment entities.
type ResourceCommentUpdate struct {
	config
	hooks    []Hook
	mutation *ResourceCommentMutation
}

// Where appends a list predicates to the ResourceCommentUpdate builder.
func (_u *ResourceCommentUpdate) Where(ps ...predicate.ResourceComment) *ResourceCommentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPostID sets the "post_id" field.
func (_u *ResourceCommentUpdate) SetPostID(v int64) *ResourceCommentUpdate {
	_u.mutation.ResetPostID()
	_u.mutation.SetPostID(v)
	return _u
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (_u *ResourceCommentUpdate) SetNillablePostID(v *int64) *ResourceCommentUpdate {
	if v != nil {
		_u.SetPostID(*v)
	}
	return _u
}

// AddPostID adds value to the "post_id" field.
func (_u *ResourceCommentUpdate) AddPostID(v int64) *ResourceCommentUpdate {
	_u.mutation.AddPostID(v)
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *ResourceCommentUpdate) SetParentID(v int64) *ResourceCommentUpdate {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *ResourceCommentUpdate) SetNillableParentID(v *int64) *ResourceCommentUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *ResourceCommentUpdate) AddParentID(v int64) *ResourceCommentUpdate {
	_u.mutation.AddParentID(v)
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *ResourceCommentUpdate) ClearParentID() *ResourceCommentUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *ResourceCommentUpdate) SetAuthorID(v int64) *ResourceCommentUpdate {
	_u.mutation.ResetAuthorID()
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *ResourceCommentUpdate) SetNillableAuthorID(v *int64) *ResourceCommentUpdate {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// AddAuthorID adds value to the "author_id" field.
func (_u *ResourceCommentUpdate) AddAuthorID(v int64) *ResourceCommentUpdate {
	_u.mutation.AddAuthorID(v)
	return _u
}

// SetAuthorUsername sets the "author_username" field.
func (_u *ResourceCommentUpdate) SetAuthorUsername(v string) *ResourceCommentUpdate {
	_u.mutation.SetAuthorUsername(v)
	return _u
}

// SetNillableAuthorUsername sets the "author_username" field if the given value is not nil.
func (_u *ResourceCommentUpdate) SetNillableAuthorUsername(v *string) *ResourceCommentUpdate {
	if v != nil {
		_u.SetAuthorUsername(*v)
	}
	return _u
}

// SetAuthorRole sets the "author_role" field.
func (_u *ResourceCommentUpdate) SetAuthorRole(v string) *ResourceCommentUpdate {
	_u.mutation.SetAuthorRole(v)
	return _u
}

// SetNillableAuthorRole sets the "author_role" field if the given value is not nil.
func (_u *ResourceCommentUpdate) SetNillableAuthorRole(v *string) *ResourceCommentUpdate {
	if v != nil {
		_u.SetAuthorRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ResourceCommentUpdate) SetContent(v string) *ResourceCommentUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ResourceCommentUpdate) SetNillableContent(v *string) *ResourceCommentUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResourceCommentUpdate) SetStatus(v string) *ResourceCommentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ResourceCommentUpdate) SetNillableStatus(v *string) *ResourceCommentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLikeCount sets the "like_count" field.
func (_u *ResourceCommentUpdate) SetLikeCount(v int) *ResourceCommentUpdate {
	_u.mutation.ResetLikeCount()
	_u.mutation.SetLikeCount(v)
	return _u
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_u *ResourceCommentUpdate) SetNillableLikeCount(v *int) *ResourceCommentUpdate {
	if v != nil {
		_u.SetLikeCount(*v)
	}
	return _u
}

// AddLikeCount adds value to the "like_count" field.
func (_u *ResourceCommentUpdate) AddLikeCount(v int) *ResourceCommentUpdate {
	_u.mutation.AddLikeCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResourceCommentUpdate) SetUpdatedAt(v time.Time) *ResourceCommentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ResourceCommentMutation object of the builder.
func (_u *ResourceCommentUpdate) Mutation() *ResourceCommentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResourceCommentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceCommentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResourceCommentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceCommentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResourceCommentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resourcecomment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourceCommentUpdate) check() error {
	if v, ok := _u.mutation.AuthorUsername(); ok {
		if err := resourcecomment.AuthorUsernameValidator(v); err != nil {
			return &ValidationError{Name: "author_username", err: fmt.Errorf(`ent: validator failed for field "ResourceComment.author_username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthorRole(); ok {
		if err := resourcecomment.AuthorRoleValidator(v); err != nil {
			return &ValidationError{Name: "author_role", err: fmt.Errorf(`ent: validator failed for field "ResourceComment.author_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := resourcecomment.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "ResourceComment.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := resourcecomment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ResourceComment.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ResourceCommentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resourcecomment.Table, resourcecomment.Columns, sqlgraph.NewFieldSpec(resourcecomment.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PostID(); ok {
		_spec.SetField(resourcecomment.FieldPostID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPostID(); ok {
		_spec.AddField(resourcecomment.FieldPostID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(resourcecomment.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(resourcecomment.FieldParentID, field.TypeInt64, value)
	}
	if _u.mutation.ParentIDCleared() {
		_spec.ClearField(resourcecomment.FieldParentID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AuthorID(); ok {
		_spec.SetField(resourcecomment.FieldAuthorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAuthorID(); ok {
		_spec.AddField(resourcecomment.FieldAuthorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AuthorUsername(); ok {
		_spec.SetField(resourcecomment.FieldAuthorUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthorRole(); ok {
		_spec.SetField(resourcecomment.FieldAuthorRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(resourcecomment.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(resourcecomment.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LikeCount(); ok {
		_spec.SetField(resourcecomment.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLikeCount(); ok {
		_spec.AddField(resourcecomment.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resourcecomment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourcecomment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResourceCommentUpdateOne is the builder for updating a single ResourceComment entity.
type ResourceCommentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ResourceCommentMutation
}

// SetPostID sets the "post_id" field.
func (_u *ResourceCommentUpdateOne) SetPostID(v int64) *ResourceCommentUpdateOne {
	_u.mutation.ResetPostID()
	_u.mutation.SetPostID(v)
	return _u
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (_u *ResourceCommentUpdateOne) SetNillablePostID(v *int64) *ResourceCommentUpdateOne {
	if v != nil {
		_u.SetPostID(*v)
	}
	return _u
}

// AddPostID adds value to the "post_id" field.
func (_u *ResourceCommentUpdateOne) AddPostID(v int64) *ResourceCommentUpdateOne {
	_u.mutation.AddPostID(v)
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *ResourceCommentUpdateOne) SetParentID(v int64) *ResourceCommentUpdateOne {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *ResourceCommentUpdateOne) SetNillableParentID(v *int64) *ResourceCommentUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *ResourceCommentUpdateOne) AddParentID(v int64) *ResourceCommentUpdateOne {
	_u.mutation.AddParentID(v)
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *ResourceCommentUpdateOne) ClearParentID() *ResourceCommentUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *ResourceCommentUpdateOne) SetAuthorID(v int64) *ResourceCommentUpdateOne {
	_u.mutation.ResetAuthorID()
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *ResourceCommentUpdateOne) SetNillableAuthorID(v *int64) *ResourceCommentUpdateOne {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// AddAuthorID adds value to the "author_id" field.
func (_u *ResourceCommentUpdateOne) AddAuthorID(v int64) *ResourceCommentUpdateOne {
	_u.mutation.AddAuthorID(v)
	return _u
}

// SetAuthorUsername sets the "author_username" field.
func (_u *ResourceCommentUpdateOne) SetAuthorUsername(v string) *ResourceCommentUpdateOne {
	_u.mutation.SetAuthorUsername(v)
	return _u
}

// SetNillableAuthorUsername sets the "author_username" field if the given value is not nil.
func (_u *ResourceCommentUpdateOne) SetNillableAuthorUsername(v *string) *ResourceCommentUpdateOne {
	if v != nil {
		_u.SetAuthorUsername(*v)
	}
	return _u
}

// SetAuthorRole sets the "author_role" field.
func (_u *ResourceCommentUpdateOne) SetAuthorRole(v string) *ResourceCommentUpdateOne {
	_u.mutation.SetAuthorRole(v)
	return _u
}

// SetNillableAuthorRole sets the "author_role" field if the given value is not nil.
func (_u *ResourceCommentUpdateOne) SetNillableAuthorRole(v *string) *ResourceCommentUpdateOne {
	if v != nil {
		_u.SetAuthorRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ResourceCommentUpdateOne) SetContent(v string) *ResourceCommentUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ResourceCommentUpdateOne) SetNillableContent(v *string) *ResourceCommentUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResourceCommentUpdateOne) SetStatus(v string) *ResourceCommentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ResourceCommentUpdateOne) SetNillableStatus(v *string) *ResourceCommentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLikeCount sets the "like_count" field.
func (_u *ResourceCommentUpdateOne) SetLikeCount(v int) *ResourceCommentUpdateOne {
	_u.mutation.ResetLikeCount()
	_u.mutation.SetLikeCount(v)
	return _u
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_u *ResourceCommentUpdateOne) SetNillableLikeCount(v *int) *ResourceCommentUpdateOne {
	if v != nil {
		_u.SetLikeCount(*v)
	}
	return _u
}

// AddLikeCount adds value to the "like_count" field.
func (_u *ResourceCommentUpdateOne) AddLikeCount(v int) *ResourceCommentUpdateOne {
	_u.mutation.AddLikeCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResourceCommentUpdateOne) SetUpdatedAt(v time.Time) *ResourceCommentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ResourceCommentMutation object of the builder.
func (_u *ResourceCommentUpdateOne) Mutation() *ResourceCommentMutation {
	return _u.mutation
}

// Where appends a list predicates to the ResourceCommentUpdate builder.
func (_u *ResourceCommentUpdateOne) Where(ps ...predicate.ResourceComment) *ResourceCommentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResourceCommentUpdateOne) Select(field string, fields ...string) *ResourceCommentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ResourceComment entity.
func (_u *ResourceCommentUpdateOne) Save(ctx context.Context) (*ResourceComment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceCommentUpdateOne) SaveX(ctx context.Context) *ResourceComment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResourceCommentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceCommentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResourceCommentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resourcecomment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourceCommentUpdateOne) check() error {
	if v, ok := _u.mutation.AuthorUsername(); ok {
		if err := resourcecomment.AuthorUsernameValidator(v); err != nil {
			return &ValidationError{Name: "author_username", err: fmt.Errorf(`ent: validator failed for field "ResourceComment.author_username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthorRole(); ok {
		if err := resourcecomment.AuthorRoleValidator(v); err != nil {
			return &ValidationError{Name: "author_role", err: fmt.Errorf(`ent: validator failed for field "ResourceComment.author_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := resourcecomment.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "ResourceComment.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := resourcecomment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ResourceComment.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ResourceCommentUpdateOne) sqlSave(ctx context.Context) (_node *ResourceComment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resourcecomment.Table, resourcecomment.Columns, sqlgraph.NewFieldSpec(resourcecomment.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ResourceComment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resourcecomment.FieldID)
		for _, f := range fields {
			if !resourcecomment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != resourcecomment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PostID(); ok {
		_spec.SetField(resourcecomment.FieldPostID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPostID(); ok {
		_spec.AddField(resourcecomment.FieldPostID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(resourcecomment.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(resourcecomment.FieldParentID, field.TypeInt64, value)
	}
	if _u.mutation.ParentIDCleared() {
		_spec.ClearField(resourcecomment.FieldParentID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AuthorID(); ok {
		_spec.SetField(resourcecomment.FieldAuthorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAuthorID(); ok {
		_spec.AddField(resourcecomment.FieldAuthorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AuthorUsername(); ok {
		_spec.SetField(resourcecomment.FieldAuthorUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthorRole(); ok {
		_spec.SetField(resourcecomment.FieldAuthorRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(resourcecomment.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(resourcecomment.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LikeCount(); ok {
		_spec.SetField(resourcecomment.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLikeCount(); ok {
		_spec.AddField(resourcecomment.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resourcecomment.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ResourceComment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourcecomment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
