// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/resourcenotification"
)

// ResourceNotification is the model entity for the ResourceNotification schema.
type ResourceNotification struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// ActorID holds the value of the "actor_id" field.
	ActorID int64 `json:"actor_id,omitempty"`
	// ActorUsername holds the value of the "actor_username" field.
	ActorUsername string `json:"actor_username,omitempty"`
	// ActorRole holds the value of the "actor_role" field.
	ActorRole string `json:"actor_role,omitempty"`
	// PostID holds the value of the "post_id" field.
	PostID int64 `json:"post_id,omitempty"`
	// CommentID holds the value of the "comment_id" field.
	CommentID *int64 `json:"comment_id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// Read holds the value of the "read" field.
	Read bool `json:"read,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ResourceNotification) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case resourcenotification.FieldRead:
			values[i] = new(sql.NullBool)
		case resourcenotification.FieldID, resourcenotification.FieldUserID, resourcenotification.FieldActorID, resourcenotification.FieldPostID, resourcenotification.FieldCommentID:
			values[i] = new(sql.NullInt64)
		case resourcenotification.FieldActorUsername, resourcenotification.FieldActorRole, resourcenotification.FieldKind:
			values[i] = new(sql.NullString)
		case resourcenotification.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ResourceNotification fields.
func (_m *ResourceNotification) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case resourcenotification.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case resourcenotification.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case resourcenotification.FieldActorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field actor_id", values[i])
			} else if value.Valid {
				_m.ActorID = value.Int64
			}
		case resourcenotification.FieldActorUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_username", values[i])
			} else if value.Valid {
				_m.ActorUsername = value.String
			}
		case resourcenotification.FieldActorRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_role", values[i])
			} else if value.Valid {
				_m.ActorRole = value.String
			}
		case resourcenotification.FieldPostID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field post_id", values[i])
			} else if value.Valid {
				_m.PostID = value.Int64
			}
		case resourcenotification.FieldCommentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field comment_id", values[i])
			} else if value.Valid {
				_m.CommentID = new(int64)
				*_m.CommentID = value.Int64
			}
		case resourcenotification.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case resourcenotification.FieldRead:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field read", values[i])
			} else if value.Valid {
				_m.Read = value.Bool
			}
		case resourcenotification.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ResourceNotification.
// This includes values selected through modifiers, order, etc.
func (_m *ResourceNotification) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ResourceNotification.
// Note that you need to call ResourceNotification.Unwrap() before calling this method if this ResourceNotification
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ResourceNotification) Update() *ResourceNotificationUpdateOne {
	return NewResourceNotificationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ResourceNotification entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ResourceNotification) Unwrap() *ResourceNotification {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ResourceNotification is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ResourceNotification) String() string {
	var builder strings.Builder
	builder.WriteString("ResourceNotification(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("actor_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActorID))
	builder.WriteString(", ")
	builder.WriteString("actor_username=")
	builder.WriteString(_m.ActorUsername)
	builder.WriteString(", ")
	builder.WriteString("actor_role=")
	builder.WriteString(_m.ActorRole)
	builder.WriteString(", ")
	builder.WriteString("post_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PostID))
	builder.WriteString(", ")
	if v := _m.CommentID; v != nil {
		builder.WriteString("comment_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("read=")
	builder.WriteString(fmt.Sprintf("%v", _m.Read))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ResourceNotifications is a parsable slice of ResourceNotification.
type ResourceNotifications []*ResourceNotification
