// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/resourcenotification"
)

// ResourceNotificationCreate is the builder for creating a ResourceNotification entity.
type ResourceNotificationCreate struct {
	config
	mutation *ResourceNotificationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *ResourceNotificationCreate) SetUserID(v int64) *ResourceNotificationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetActorID sets the "actor_id" field.
func (_c *ResourceNotificationCreate) SetActorID(v int64) *ResourceNotificationCreate {
	_c.mutation.SetActorID(v)
	return _c
}

// SetActorUsername sets the "actor_username" field.
func (_c *ResourceNotificationCreate) SetActorUsername(v string) *ResourceNotificationCreate {
	_c.mutation.SetActorUsername(v)
	return _c
}

// SetActorRole sets the "actor_role" field.
func (_c *ResourceNotificationCreate) SetActorRole(v string) *ResourceNotificationCreate {
	_c.mutation.SetActorRole(v)
	return _c
}

// SetPostID sets the "post_id" field.
func (_c *ResourceNotificationCreate) SetPostID(v int64) *ResourceNotificationCreate {
	_c.mutation.SetPostID(v)
	return _c
}

// SetCommentID sets the "comment_id" field.
func (_c *ResourceNotificationCreate) SetCommentID(v int64) *ResourceNotificationCreate {
	_c.mutation.SetCommentID(v)
	return _c
}

// SetNillableCommentID sets the "comment_id" field if the given value is not nil.
func (_c *ResourceNotificationCreate) SetNillableCommentID(v *int64) *ResourceNotificationCreate {
	if v != nil {
		_c.SetCommentID(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *ResourceNotificationCreate) SetKind(v string) *ResourceNotificationCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetRead sets the "read" field.
func (_c *ResourceNotificationCreate) SetRead(v bool) *ResourceNotificationCreate {
	_c.mutation.SetRead(v)
	return _c
}

// SetNillableRead sets the "read" field if the given value is not nil.
func (_c *ResourceNotificationCreate) SetNillableRead(v *bool) *ResourceNotificationCreate {
	if v != nil {
		_c.SetRead(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ResourceNotificationCreate) SetCreatedAt(v time.Time) *ResourceNotificationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ResourceNotificationCreate) SetNillableCreatedAt(v *time.Time) *ResourceNotificationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the ResourceNotificationMutation object of the builder.
func (_c *ResourceNotificationCreate) Mutation() *ResourceNotificationMutation {
	return _c.mutation
}

// Save creates the ResourceNotification in the database.
func (_c *ResourceNotificationCreate) Save(ctx context.Context) (*ResourceNotification, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResourceNotificationCreate) SaveX(ctx context.Context) *ResourceNotification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResourceNotificationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResourceNotificationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResourceNotificationCreate) defaults() {
	if _, ok := _c.mutation.Read(); !ok {
		v := resourcenotification.DefaultRead
		_c.mutation.SetRead(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := resourcenotification.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResourceNotificationCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ResourceNotification.user_id"`)}
	}
	if _, ok := _c.mutation.ActorID(); !ok {
		return &ValidationError{Name: "actor_id", err: errors.New(`ent: missing required field "ResourceNotification.actor_id"`)}
	}
	if _, ok := _c.mutation.ActorUsername(); !ok {
		return &ValidationError{Name: "actor_username", err: errors.New(`ent: missing required field "ResourceNotification.actor_username"`)}
	}
	if v, ok := _c.mutation.ActorUsername(); ok {
		if err := resourcenotification.ActorUsernameValidator(v); err != nil {
			return &ValidationError{Name: "actor_username", err: fmt.Errorf(`ent: validator failed for field "ResourceNotification.actor_username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActorRole(); !ok {
		return &ValidationError{Name: "actor_role", err: errors.New(`ent: missing required field "ResourceNotification.actor_role"`)}
	}
	if v, ok := _c.mutation.ActorRole(); ok {
		if err := resourcenotification.ActorRoleValidator(v); err != nil {
			return &ValidationError{Name: "actor_role", err: fmt.Errorf(`ent: validator failed for field "ResourceNotification.actor_role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PostID(); !ok {
		return &ValidationError{Name: "post_id", err: errors.New(`ent: missing required field "ResourceNotification.post_id"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "ResourceNotification.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := resourcenotification.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "ResourceNotification.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Read(); !ok {
		return &ValidationError{Name: "read", err: errors.New(`ent: missing required field "ResourceNotification.read"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ResourceNotification.created_at"`)}
	}
	return nil
}

func (_c *ResourceNotificationCreate) sqlSave(ctx context.Context) (*ResourceNotification, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResourceNotificationCreate) createSpec() (*ResourceNotification, *sqlgraph.CreateSpec) {
	var (
		_node = &ResourceNotification{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(resourcenotification.Table, sqlgraph.NewFieldSpec(resourcenotification.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(resourcenotification.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.ActorID(); ok {
		_spec.SetField(resourcenotification.FieldActorID, field.TypeInt64, value)
		_node.ActorID = value
	}
	if value, ok := _c.mutation.ActorUsername(); ok {
		_spec.SetField(resourcenotification.FieldActorUsername, field.TypeString, value)
		_node.ActorUsername = value
	}
	if value, ok := _c.mutation.ActorRole(); ok {
		_spec.SetField(resourcenotification.FieldActorRole, field.TypeString, value)
		_node.ActorRole = value
	}
	if value, ok := _c.mutation.PostID(); ok {
		_spec.SetField(resourcenotification.FieldPostID, field.TypeInt64, value)
		_node.PostID = value
	}
	if value, ok := _c.mutation.CommentID(); ok {
		_spec.SetField(resourcenotification.FieldCommentID, field.TypeInt64, value)
		_node.CommentID = &value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(resourcenotification.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Read(); ok {
		_spec.SetField(resourcenotification.FieldRead, field.TypeBool, value)
		_node.Read = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(resourcenotification.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResourceNotification.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResourceNotificationUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *ResourceNotificationCreate) OnConflict(opts ...sql.ConflictOption) *ResourceNotificationUpsertOne {
	_c.conflict = opts
	return &ResourceNotificationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResourceNotification.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResourceNotificationCreate) OnConflictColumns(columns ...string) *ResourceNotificationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResourceNotificationUpsertOne{
		create: _c,
	}
}

type (
	// ResourceNotificationUpsertOne is the builder for "upsert"-ing
	//  one ResourceNotification node.
	ResourceNotificationUpsertOne struct {
		create *ResourceNotificationCreate
	}

	// ResourceNotificationUpsert is the "OnConflict" setter.
	ResourceNotificationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *ResourceNotificationUpsert) SetUserID(v int64) *ResourceNotificationUpsert {
	u.Set(resourcenotification.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ResourceNotificationUpsert) UpdateUserID() *ResourceNotificationUpsert {
	u.SetExcluded(resourcenotification.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *ResourceNotificationUpsert) AddUserID(v int64) *ResourceNotificationUpsert {
	u.Add(resourcenotification.FieldUserID, v)
	return u
}

// SetActorID sets the "actor_id" field.
func (u *ResourceNotificationUpsert) SetActorID(v int64) *ResourceNotificationUpsert {
	u.Set(resourcenotification.FieldActorID, v)
	return u
}

// UpdateActorID sets the "actor_id" field to the value that was provided on create.
func (u *ResourceNotificationUpsert) UpdateActorID() *ResourceNotificationUpsert {
	u.SetExcluded(resourcenotification.FieldActorID)
	return u
}

// AddActorID adds v to the "actor_id" field.
func (u *ResourceNotificationUpsert) AddActorID(v int64) *ResourceNotificationUpsert {
	u.Add(resourcenotification.FieldActorID, v)
	return u
}

// SetActorUsername sets the "actor_username" field.
func (u *ResourceNotificationUpsert) SetActorUsername(v string) *ResourceNotificationUpsert {
	u.Set(resourcenotification.FieldActorUsername, v)
	return u
}

// UpdateActorUsername sets the "actor_username" field to the value that was provided on create.
func (u *ResourceNotificationUpsert) UpdateActorUsername() *ResourceNotificationUpsert {
	u.SetExcluded(resourcenotification.FieldActorUsername)
	return u
}

// SetActorRole sets the "actor_role" field.
func (u *ResourceNotificationUpsert) SetActorRole(v string) *ResourceNotificationUpsert {
	u.Set(resourcenotification.FieldActorRole, v)
	return u
}

// UpdateActorRole sets the "actor_role" field to the value that was provided on create.
func (u *ResourceNotificationUpsert) UpdateActorRole() *ResourceNotificationUpsert {
	u.SetExcluded(resourcenotification.FieldActorRole)
	return u
}

// SetPostID sets the "post_id" field.
func (u *ResourceNotificationUpsert) SetPostID(v int64) *ResourceNotificationUpsert {
	u.Set(resourcenotification.FieldPostID, v)
	return u
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *ResourceNotificationUpsert) UpdatePostID() *ResourceNotificationUpsert {
	u.SetExcluded(resourcenotification.FieldPostID)
	return u
}

// AddPostID adds v to the "post_id" field.
func (u *ResourceNotificationUpsert) AddPostID(v int64) *ResourceNotificationUpsert {
	u.Add(resourcenotification.FieldPostID, v)
	return u
}

// SetCommentID sets the "comment_id" field.
func (u *ResourceNotificationUpsert) SetCommentID(v int64) *ResourceNotificationUpsert {
	u.Set(resourcenotification.FieldCommentID, v)
	return u
}

// UpdateCommentID sets the "comment_id" field to the value that was provided on create.
func (u *ResourceNotificationUpsert) UpdateCommentID() *ResourceNotificationUpsert {
	u.SetExcluded(resourcenotification.FieldCommentID)
	return u
}

// AddCommentID adds v to the "comment_id" field.
func (u *ResourceNotificationUpsert) AddCommentID(v int64) *ResourceNotificationUpsert {
	u.Add(resourcenotification.FieldCommentID, v)
	return u
}

// ClearCommentID clears the value of the "comment_id" field.
func (u *ResourceNotificationUpsert) ClearCommentID() *ResourceNotificationUpsert {
	u.SetNull(resourcenotification.FieldCommentID)
	return u
}

// SetKind sets the "kind" field.
func (u *ResourceNotificationUpsert) SetKind(v string) *ResourceNotificationUpsert {
	u.Set(resourcenotification.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ResourceNotificationUpsert) UpdateKind() *ResourceNotificationUpsert {
	u.SetExcluded(resourcenotification.FieldKind)
	return u
}

// SetRead sets the "read" field.
func (u *ResourceNotificationUpsert) SetRead(v bool) *ResourceNotificationUpsert {
	u.Set(resourcenotification.FieldRead, v)
	return u
}

// UpdateRead sets the "read" field to the value that was provided on create.
func (u *ResourceNotificationUpsert) UpdateRead() *ResourceNotificationUpsert {
	u.SetExcluded(resourcenotification.FieldRead)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ResourceNotification.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResourceNotificationUpsertOne) UpdateNewValues() *ResourceNotificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(resourcenotification.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResourceNotification.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ResourceNotificationUpsertOne) Ignore() *ResourceNotificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResourceNotificationUpsertOne) DoNothing() *ResourceNotificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResourceNotificationCreate.OnConflict
// documentation for more info.
func (u *ResourceNotificationUpsertOne) Update(set func(*ResourceNotificationUpsert)) *ResourceNotificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResourceNotificationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *ResourceNotificationUpsertOne) SetUserID(v int64) *ResourceNotificationUpsertOne {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ResourceNotificationUpsertOne) AddUserID(v int64) *ResourceNotificationUpsertOne {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ResourceNotificationUpsertOne) UpdateUserID() *ResourceNotificationUpsertOne {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.UpdateUserID()
	})
}

// SetActorID sets the "actor_id" field.
func (u *ResourceNotificationUpsertOne) SetActorID(v int64) *ResourceNotificationUpsertOne {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.SetActorID(v)
	})
}

// AddActorID adds v to the "actor_id" field.
func (u *ResourceNotificationUpsertOne) AddActorID(v int64) *ResourceNotificationUpsertOne {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.AddActorID(v)
	})
}

// UpdateActorID sets the "actor_id" field to the value that was provided on create.
func (u *ResourceNotificationUpsertOne) UpdateActorID() *ResourceNotificationUpsertOne {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.UpdateActorID()
	})
}

// SetActorUsername sets the "actor_username" field.
func (u *ResourceNotificationUpsertOne) SetActorUsername(v string) *ResourceNotificationUpsertOne {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.SetActorUsername(v)
	})
}

// UpdateActorUsername sets the "actor_username" field to the value that was provided on create.
func (u *ResourceNotificationUpsertOne) UpdateActorUsername() *ResourceNotificationUpsertOne {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.UpdateActorUsername()
	})
}

// SetActorRole sets the "actor_role" field.
func (u *ResourceNotificationUpsertOne) SetActorRole(v string) *ResourceNotificationUpsertOne {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.SetActorRole(v)
	})
}

// UpdateActorRole sets the "actor_role" field to the value that was provided on create.
func (u *ResourceNotificationUpsertOne) UpdateActorRole() *ResourceNotificationUpsertOne {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.UpdateActorRole()
	})
}

// SetPostID sets the "post_id" field.
func (u *ResourceNotificationUpsertOne) SetPostID(v int64) *ResourceNotificationUpsertOne {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.SetPostID(v)
	})
}

// AddPostID adds v to the "post_id" field.
func (u *ResourceNotificationUpsertOne) AddPostID(v int64) *ResourceNotificationUpsertOne {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.AddPostID(v)
	})
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *ResourceNotificationUpsertOne) UpdatePostID() *ResourceNotificationUpsertOne {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.UpdatePostID()
	})
}

// SetCommentID sets the "comment_id" field.
func (u *ResourceNotificationUpsertOne) SetCommentID(v int64) *ResourceNotificationUpsertOne {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.SetCommentID(v)
	})
}

// AddCommentID adds v to the "comment_id" field.
func (u *ResourceNotificationUpsertOne) AddCommentID(v int64) *ResourceNotificationUpsertOne {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.AddCommentID(v)
	})
}

// UpdateCommentID sets the "comment_id" field to the value that was provided on create.
func (u *ResourceNotificationUpsertOne) UpdateCommentID() *ResourceNotificationUpsertOne {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.UpdateCommentID()
	})
}

// ClearCommentID clears the value of the "comment_id" field.
func (u *ResourceNotificationUpsertOne) ClearCommentID() *ResourceNotificationUpsertOne {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.ClearCommentID()
	})
}

// SetKind sets the "kind" field.
func (u *ResourceNotificationUpsertOne) SetKind(v string) *ResourceNotificationUpsertOne {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ResourceNotificationUpsertOne) UpdateKind() *ResourceNotificationUpsertOne {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.UpdateKind()
	})
}

// SetRead sets the "read" field.
func (u *ResourceNotificationUpsertOne) SetRead(v bool) *ResourceNotificationUpsertOne {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.SetRead(v)
	})
}

// UpdateRead sets the "read" field to the value that was provided on create.
func (u *ResourceNotificationUpsertOne) UpdateRead() *ResourceNotificationUpsertOne {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.UpdateRead()
	})
}

// Exec executes the query.
func (u *ResourceNotificationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResourceNotificationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResourceNotificationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ResourceNotificationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ResourceNotificationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ResourceNotificationCreateBulk is the builder for creating many ResourceNotification entities in bulk.
type ResourceNotificationCreateBulk struct {
	config
	err      error
	builders []*ResourceNotificationCreate
	conflict []sql.ConflictOption
}

// Save creates the ResourceNotification entities in the database.
func (_c *ResourceNotificationCreateBulk) Save(ctx context.Context) ([]*ResourceNotification, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ResourceNotification, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResourceNotificationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResourceNotificationCreateBulk) SaveX(ctx context.Context) []*ResourceNotification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResourceNotificationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResourceNotificationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResourceNotification.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResourceNotificationUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *ResourceNotificationCreateBulk) OnConflict(opts ...sql.ConflictOption) *ResourceNotificationUpsertBulk {
	_c.conflict = opts
	return &ResourceNotificationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResourceNotification.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResourceNotificationCreateBulk) OnConflictColumns(columns ...string) *ResourceNotificationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResourceNotificationUpsertBulk{
		create: _c,
	}
}

// ResourceNotificationUpsertBulk is the builder for "upsert"-ing
// a bulk of ResourceNotification nodes.
type ResourceNotificationUpsertBulk struct {
	create *ResourceNotificationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ResourceNotification.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResourceNotificationUpsertBulk) UpdateNewValues() *ResourceNotificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(resourcenotification.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResourceNotification.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ResourceNotificationUpsertBulk) Ignore() *ResourceNotificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResourceNotificationUpsertBulk) DoNothing() *ResourceNotificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResourceNotificationCreateBulk.OnConflict
// documentation for more info.
func (u *ResourceNotificationUpsertBulk) Update(set func(*ResourceNotificationUpsert)) *ResourceNotificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResourceNotificationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *ResourceNotificationUpsertBulk) SetUserID(v int64) *ResourceNotificationUpsertBulk {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ResourceNotificationUpsertBulk) AddUserID(v int64) *ResourceNotificationUpsertBulk {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ResourceNotificationUpsertBulk) UpdateUserID() *ResourceNotificationUpsertBulk {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.UpdateUserID()
	})
}

// SetActorID sets the "actor_id" field.
func (u *ResourceNotificationUpsertBulk) SetActorID(v int64) *ResourceNotificationUpsertBulk {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.SetActorID(v)
	})
}

// AddActorID adds v to the "actor_id" field.
func (u *ResourceNotificationUpsertBulk) AddActorID(v int64) *ResourceNotificationUpsertBulk {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.AddActorID(v)
	})
}

// UpdateActorID sets the "actor_id" field to the value that was provided on create.
func (u *ResourceNotificationUpsertBulk) UpdateActorID() *ResourceNotificationUpsertBulk {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.UpdateActorID()
	})
}

// SetActorUsername sets the "actor_username" field.
func (u *ResourceNotificationUpsertBulk) SetActorUsername(v string) *ResourceNotificationUpsertBulk {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.SetActorUsername(v)
	})
}

// UpdateActorUsername sets the "actor_username" field to the value that was provided on create.
func (u *ResourceNotificationUpsertBulk) UpdateActorUsername() *ResourceNotificationUpsertBulk {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.UpdateActorUsername()
	})
}

// SetActorRole sets the "actor_role" field.
func (u *ResourceNotificationUpsertBulk) SetActorRole(v string) *ResourceNotificationUpsertBulk {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.SetActorRole(v)
	})
}

// UpdateActorRole sets the "actor_role" field to the value that was provided on create.
func (u *ResourceNotificationUpsertBulk) UpdateActorRole() *ResourceNotificationUpsertBulk {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.UpdateActorRole()
	})
}

// SetPostID sets the "post_id" field.
func (u *ResourceNotificationUpsertBulk) SetPostID(v int64) *ResourceNotificationUpsertBulk {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.SetPostID(v)
	})
}

// AddPostID adds v to the "post_id" field.
func (u *ResourceNotificationUpsertBulk) AddPostID(v int64) *ResourceNotificationUpsertBulk {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.AddPostID(v)
	})
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *ResourceNotificationUpsertBulk) UpdatePostID() *ResourceNotificationUpsertBulk {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.UpdatePostID()
	})
}

// SetCommentID sets the "comment_id" field.
func (u *ResourceNotificationUpsertBulk) SetCommentID(v int64) *ResourceNotificationUpsertBulk {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.SetCommentID(v)
	})
}

// AddCommentID adds v to the "comment_id" field.
func (u *ResourceNotificationUpsertBulk) AddCommentID(v int64) *ResourceNotificationUpsertBulk {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.AddCommentID(v)
	})
}

// UpdateCommentID sets the "comment_id" field to the value that was provided on create.
func (u *ResourceNotificationUpsertBulk) UpdateCommentID() *ResourceNotificationUpsertBulk {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.UpdateCommentID()
	})
}

// ClearCommentID clears the value of the "comment_id" field.
func (u *ResourceNotificationUpsertBulk) ClearCommentID() *ResourceNotificationUpsertBulk {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.ClearCommentID()
	})
}

// SetKind sets the "kind" field.
func (u *ResourceNotificationUpsertBulk) SetKind(v string) *ResourceNotificationUpsertBulk {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ResourceNotificationUpsertBulk) UpdateKind() *ResourceNotificationUpsertBulk {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.UpdateKind()
	})
}

// SetRead sets the "read" field.
func (u *ResourceNotificationUpsertBulk) SetRead(v bool) *ResourceNotificationUpsertBulk {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.SetRead(v)
	})
}

// UpdateRead sets the "read" field to the value that was provided on create.
func (u *ResourceNotificationUpsertBulk) UpdateRead() *ResourceNotificationUpsertBulk {
	return u.Update(func(s *ResourceNotificationUpsert) {
		s.UpdateRead()
	})
}

// Exec executes the query.
func (u *ResourceNotificationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ResourceNotificationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResourceNotificationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResourceNotificationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
