// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/smsorder"
	"github.com/google/uuid"
)

// SmsOrderCreate is the builder for creating a SmsOrder entity.
type SmsOrderCreate struct {
	config
	mutation *SmsOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPublicID sets the "public_id" field.
func (_c *SmsOrderCreate) SetPublicID(v uuid.UUID) *SmsOrderCreate {
	_c.mutation.SetPublicID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SmsOrderCreate) SetUserID(v int64) *SmsOrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *SmsOrderCreate) SetChannelID(v int64) *SmsOrderCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetProviderID sets the "provider_id" field.
func (_c *SmsOrderCreate) SetProviderID(v int64) *SmsOrderCreate {
	_c.mutation.SetProviderID(v)
	return _c
}

// SetServiceID sets the "service_id" field.
func (_c *SmsOrderCreate) SetServiceID(v int64) *SmsOrderCreate {
	_c.mutation.SetServiceID(v)
	return _c
}

// SetCountryID sets the "country_id" field.
func (_c *SmsOrderCreate) SetCountryID(v int64) *SmsOrderCreate {
	_c.mutation.SetCountryID(v)
	return _c
}

// SetProductType sets the "product_type" field.
func (_c *SmsOrderCreate) SetProductType(v string) *SmsOrderCreate {
	_c.mutation.SetProductType(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *SmsOrderCreate) SetStatus(v string) *SmsOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SmsOrderCreate) SetNillableStatus(v *string) *SmsOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetProviderOrderID sets the "provider_order_id" field.
func (_c *SmsOrderCreate) SetProviderOrderID(v string) *SmsOrderCreate {
	_c.mutation.SetProviderOrderID(v)
	return _c
}

// SetNillableProviderOrderID sets the "provider_order_id" field if the given value is not nil.
func (_c *SmsOrderCreate) SetNillableProviderOrderID(v *string) *SmsOrderCreate {
	if v != nil {
		_c.SetProviderOrderID(*v)
	}
	return _c
}

// SetPhoneNumber sets the "phone_number" field.
func (_c *SmsOrderCreate) SetPhoneNumber(v string) *SmsOrderCreate {
	_c.mutation.SetPhoneNumber(v)
	return _c
}

// SetNillablePhoneNumber sets the "phone_number" field if the given value is not nil.
func (_c *SmsOrderCreate) SetNillablePhoneNumber(v *string) *SmsOrderCreate {
	if v != nil {
		_c.SetPhoneNumber(*v)
	}
	return _c
}

// SetProviderCostSnapshot sets the "provider_cost_snapshot" field.
func (_c *SmsOrderCreate) SetProviderCostSnapshot(v float64) *SmsOrderCreate {
	_c.mutation.SetProviderCostSnapshot(v)
	return _c
}

// SetNillableProviderCostSnapshot sets the "provider_cost_snapshot" field if the given value is not nil.
func (_c *SmsOrderCreate) SetNillableProviderCostSnapshot(v *float64) *SmsOrderCreate {
	if v != nil {
		_c.SetProviderCostSnapshot(*v)
	}
	return _c
}

// SetSalePriceSnapshot sets the "sale_price_snapshot" field.
func (_c *SmsOrderCreate) SetSalePriceSnapshot(v float64) *SmsOrderCreate {
	_c.mutation.SetSalePriceSnapshot(v)
	return _c
}

// SetNillableSalePriceSnapshot sets the "sale_price_snapshot" field if the given value is not nil.
func (_c *SmsOrderCreate) SetNillableSalePriceSnapshot(v *float64) *SmsOrderCreate {
	if v != nil {
		_c.SetSalePriceSnapshot(*v)
	}
	return _c
}

// SetSuccessRateSnapshot sets the "success_rate_snapshot" field.
func (_c *SmsOrderCreate) SetSuccessRateSnapshot(v float64) *SmsOrderCreate {
	_c.mutation.SetSuccessRateSnapshot(v)
	return _c
}

// SetNillableSuccessRateSnapshot sets the "success_rate_snapshot" field if the given value is not nil.
func (_c *SmsOrderCreate) SetNillableSuccessRateSnapshot(v *float64) *SmsOrderCreate {
	if v != nil {
		_c.SetSuccessRateSnapshot(*v)
	}
	return _c
}

// SetSuccessRateSourceSnapshot sets the "success_rate_source_snapshot" field.
func (_c *SmsOrderCreate) SetSuccessRateSourceSnapshot(v string) *SmsOrderCreate {
	_c.mutation.SetSuccessRateSourceSnapshot(v)
	return _c
}

// SetNillableSuccessRateSourceSnapshot sets the "success_rate_source_snapshot" field if the given value is not nil.
func (_c *SmsOrderCreate) SetNillableSuccessRateSourceSnapshot(v *string) *SmsOrderCreate {
	if v != nil {
		_c.SetSuccessRateSourceSnapshot(*v)
	}
	return _c
}

// SetSuccessRateGradeSnapshot sets the "success_rate_grade_snapshot" field.
func (_c *SmsOrderCreate) SetSuccessRateGradeSnapshot(v string) *SmsOrderCreate {
	_c.mutation.SetSuccessRateGradeSnapshot(v)
	return _c
}

// SetNillableSuccessRateGradeSnapshot sets the "success_rate_grade_snapshot" field if the given value is not nil.
func (_c *SmsOrderCreate) SetNillableSuccessRateGradeSnapshot(v *string) *SmsOrderCreate {
	if v != nil {
		_c.SetSuccessRateGradeSnapshot(*v)
	}
	return _c
}

// SetSuccessRateMultiplierSnapshot sets the "success_rate_multiplier_snapshot" field.
func (_c *SmsOrderCreate) SetSuccessRateMultiplierSnapshot(v float64) *SmsOrderCreate {
	_c.mutation.SetSuccessRateMultiplierSnapshot(v)
	return _c
}

// SetNillableSuccessRateMultiplierSnapshot sets the "success_rate_multiplier_snapshot" field if the given value is not nil.
func (_c *SmsOrderCreate) SetNillableSuccessRateMultiplierSnapshot(v *float64) *SmsOrderCreate {
	if v != nil {
		_c.SetSuccessRateMultiplierSnapshot(*v)
	}
	return _c
}

// SetCurrencySnapshot sets the "currency_snapshot" field.
func (_c *SmsOrderCreate) SetCurrencySnapshot(v string) *SmsOrderCreate {
	_c.mutation.SetCurrencySnapshot(v)
	return _c
}

// SetNillableCurrencySnapshot sets the "currency_snapshot" field if the given value is not nil.
func (_c *SmsOrderCreate) SetNillableCurrencySnapshot(v *string) *SmsOrderCreate {
	if v != nil {
		_c.SetCurrencySnapshot(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *SmsOrderCreate) SetExpiresAt(v time.Time) *SmsOrderCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *SmsOrderCreate) SetNillableExpiresAt(v *time.Time) *SmsOrderCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *SmsOrderCreate) SetIdempotencyKey(v string) *SmsOrderCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetRefundStatus sets the "refund_status" field.
func (_c *SmsOrderCreate) SetRefundStatus(v string) *SmsOrderCreate {
	_c.mutation.SetRefundStatus(v)
	return _c
}

// SetNillableRefundStatus sets the "refund_status" field if the given value is not nil.
func (_c *SmsOrderCreate) SetNillableRefundStatus(v *string) *SmsOrderCreate {
	if v != nil {
		_c.SetRefundStatus(*v)
	}
	return _c
}

// SetRefundReason sets the "refund_reason" field.
func (_c *SmsOrderCreate) SetRefundReason(v string) *SmsOrderCreate {
	_c.mutation.SetRefundReason(v)
	return _c
}

// SetNillableRefundReason sets the "refund_reason" field if the given value is not nil.
func (_c *SmsOrderCreate) SetNillableRefundReason(v *string) *SmsOrderCreate {
	if v != nil {
		_c.SetRefundReason(*v)
	}
	return _c
}

// SetLastProviderError sets the "last_provider_error" field.
func (_c *SmsOrderCreate) SetLastProviderError(v string) *SmsOrderCreate {
	_c.mutation.SetLastProviderError(v)
	return _c
}

// SetNillableLastProviderError sets the "last_provider_error" field if the given value is not nil.
func (_c *SmsOrderCreate) SetNillableLastProviderError(v *string) *SmsOrderCreate {
	if v != nil {
		_c.SetLastProviderError(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *SmsOrderCreate) SetMetadata(v map[string]interface{}) *SmsOrderCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SmsOrderCreate) SetCreatedAt(v time.Time) *SmsOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SmsOrderCreate) SetUpdatedAt(v time.Time) *SmsOrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// Mutation returns the SmsOrderMutation object of the builder.
func (_c *SmsOrderCreate) Mutation() *SmsOrderMutation {
	return _c.mutation
}

// Save creates the SmsOrder in the database.
func (_c *SmsOrderCreate) Save(ctx context.Context) (*SmsOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SmsOrderCreate) SaveX(ctx context.Context) *SmsOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SmsOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SmsOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SmsOrderCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := smsorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ProviderOrderID(); !ok {
		v := smsorder.DefaultProviderOrderID
		_c.mutation.SetProviderOrderID(v)
	}
	if _, ok := _c.mutation.PhoneNumber(); !ok {
		v := smsorder.DefaultPhoneNumber
		_c.mutation.SetPhoneNumber(v)
	}
	if _, ok := _c.mutation.ProviderCostSnapshot(); !ok {
		v := smsorder.DefaultProviderCostSnapshot
		_c.mutation.SetProviderCostSnapshot(v)
	}
	if _, ok := _c.mutation.SalePriceSnapshot(); !ok {
		v := smsorder.DefaultSalePriceSnapshot
		_c.mutation.SetSalePriceSnapshot(v)
	}
	if _, ok := _c.mutation.SuccessRateSourceSnapshot(); !ok {
		v := smsorder.DefaultSuccessRateSourceSnapshot
		_c.mutation.SetSuccessRateSourceSnapshot(v)
	}
	if _, ok := _c.mutation.SuccessRateGradeSnapshot(); !ok {
		v := smsorder.DefaultSuccessRateGradeSnapshot
		_c.mutation.SetSuccessRateGradeSnapshot(v)
	}
	if _, ok := _c.mutation.SuccessRateMultiplierSnapshot(); !ok {
		v := smsorder.DefaultSuccessRateMultiplierSnapshot
		_c.mutation.SetSuccessRateMultiplierSnapshot(v)
	}
	if _, ok := _c.mutation.CurrencySnapshot(); !ok {
		v := smsorder.DefaultCurrencySnapshot
		_c.mutation.SetCurrencySnapshot(v)
	}
	if _, ok := _c.mutation.RefundStatus(); !ok {
		v := smsorder.DefaultRefundStatus
		_c.mutation.SetRefundStatus(v)
	}
	if _, ok := _c.mutation.RefundReason(); !ok {
		v := smsorder.DefaultRefundReason
		_c.mutation.SetRefundReason(v)
	}
	if _, ok := _c.mutation.LastProviderError(); !ok {
		v := smsorder.DefaultLastProviderError
		_c.mutation.SetLastProviderError(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SmsOrderCreate) check() error {
	if _, ok := _c.mutation.PublicID(); !ok {
		return &ValidationError{Name: "public_id", err: errors.New(`ent: missing required field "SmsOrder.public_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SmsOrder.user_id"`)}
	}
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "SmsOrder.channel_id"`)}
	}
	if _, ok := _c.mutation.ProviderID(); !ok {
		return &ValidationError{Name: "provider_id", err: errors.New(`ent: missing required field "SmsOrder.provider_id"`)}
	}
	if _, ok := _c.mutation.ServiceID(); !ok {
		return &ValidationError{Name: "service_id", err: errors.New(`ent: missing required field "SmsOrder.service_id"`)}
	}
	if _, ok := _c.mutation.CountryID(); !ok {
		return &ValidationError{Name: "country_id", err: errors.New(`ent: missing required field "SmsOrder.country_id"`)}
	}
	if _, ok := _c.mutation.ProductType(); !ok {
		return &ValidationError{Name: "product_type", err: errors.New(`ent: missing required field "SmsOrder.product_type"`)}
	}
	if v, ok := _c.mutation.ProductType(); ok {
		if err := smsorder.ProductTypeValidator(v); err != nil {
			return &ValidationError{Name: "product_type", err: fmt.Errorf(`ent: validator failed for field "SmsOrder.product_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SmsOrder.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := smsorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SmsOrder.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderOrderID(); !ok {
		return &ValidationError{Name: "provider_order_id", err: errors.New(`ent: missing required field "SmsOrder.provider_order_id"`)}
	}
	if v, ok := _c.mutation.ProviderOrderID(); ok {
		if err := smsorder.ProviderOrderIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_order_id", err: fmt.Errorf(`ent: validator failed for field "SmsOrder.provider_order_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PhoneNumber(); !ok {
		return &ValidationError{Name: "phone_number", err: errors.New(`ent: missing required field "SmsOrder.phone_number"`)}
	}
	if v, ok := _c.mutation.PhoneNumber(); ok {
		if err := smsorder.PhoneNumberValidator(v); err != nil {
			return &ValidationError{Name: "phone_number", err: fmt.Errorf(`ent: validator failed for field "SmsOrder.phone_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderCostSnapshot(); !ok {
		return &ValidationError{Name: "provider_cost_snapshot", err: errors.New(`ent: missing required field "SmsOrder.provider_cost_snapshot"`)}
	}
	if _, ok := _c.mutation.SalePriceSnapshot(); !ok {
		return &ValidationError{Name: "sale_price_snapshot", err: errors.New(`ent: missing required field "SmsOrder.sale_price_snapshot"`)}
	}
	if _, ok := _c.mutation.SuccessRateSourceSnapshot(); !ok {
		return &ValidationError{Name: "success_rate_source_snapshot", err: errors.New(`ent: missing required field "SmsOrder.success_rate_source_snapshot"`)}
	}
	if v, ok := _c.mutation.SuccessRateSourceSnapshot(); ok {
		if err := smsorder.SuccessRateSourceSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "success_rate_source_snapshot", err: fmt.Errorf(`ent: validator failed for field "SmsOrder.success_rate_source_snapshot": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SuccessRateGradeSnapshot(); !ok {
		return &ValidationError{Name: "success_rate_grade_snapshot", err: errors.New(`ent: missing required field "SmsOrder.success_rate_grade_snapshot"`)}
	}
	if v, ok := _c.mutation.SuccessRateGradeSnapshot(); ok {
		if err := smsorder.SuccessRateGradeSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "success_rate_grade_snapshot", err: fmt.Errorf(`ent: validator failed for field "SmsOrder.success_rate_grade_snapshot": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SuccessRateMultiplierSnapshot(); !ok {
		return &ValidationError{Name: "success_rate_multiplier_snapshot", err: errors.New(`ent: missing required field "SmsOrder.success_rate_multiplier_snapshot"`)}
	}
	if _, ok := _c.mutation.CurrencySnapshot(); !ok {
		return &ValidationError{Name: "currency_snapshot", err: errors.New(`ent: missing required field "SmsOrder.currency_snapshot"`)}
	}
	if v, ok := _c.mutation.CurrencySnapshot(); ok {
		if err := smsorder.CurrencySnapshotValidator(v); err != nil {
			return &ValidationError{Name: "currency_snapshot", err: fmt.Errorf(`ent: validator failed for field "SmsOrder.currency_snapshot": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "SmsOrder.idempotency_key"`)}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := smsorder.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "SmsOrder.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RefundStatus(); !ok {
		return &ValidationError{Name: "refund_status", err: errors.New(`ent: missing required field "SmsOrder.refund_status"`)}
	}
	if v, ok := _c.mutation.RefundStatus(); ok {
		if err := smsorder.RefundStatusValidator(v); err != nil {
			return &ValidationError{Name: "refund_status", err: fmt.Errorf(`ent: validator failed for field "SmsOrder.refund_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RefundReason(); !ok {
		return &ValidationError{Name: "refund_reason", err: errors.New(`ent: missing required field "SmsOrder.refund_reason"`)}
	}
	if _, ok := _c.mutation.LastProviderError(); !ok {
		return &ValidationError{Name: "last_provider_error", err: errors.New(`ent: missing required field "SmsOrder.last_provider_error"`)}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "SmsOrder.metadata"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SmsOrder.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SmsOrder.updated_at"`)}
	}
	return nil
}

func (_c *SmsOrderCreate) sqlSave(ctx context.Context) (*SmsOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SmsOrderCreate) createSpec() (*SmsOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &SmsOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(smsorder.Table, sqlgraph.NewFieldSpec(smsorder.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.PublicID(); ok {
		_spec.SetField(smsorder.FieldPublicID, field.TypeUUID, value)
		_node.PublicID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(smsorder.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.ChannelID(); ok {
		_spec.SetField(smsorder.FieldChannelID, field.TypeInt64, value)
		_node.ChannelID = value
	}
	if value, ok := _c.mutation.ProviderID(); ok {
		_spec.SetField(smsorder.FieldProviderID, field.TypeInt64, value)
		_node.ProviderID = value
	}
	if value, ok := _c.mutation.ServiceID(); ok {
		_spec.SetField(smsorder.FieldServiceID, field.TypeInt64, value)
		_node.ServiceID = value
	}
	if value, ok := _c.mutation.CountryID(); ok {
		_spec.SetField(smsorder.FieldCountryID, field.TypeInt64, value)
		_node.CountryID = value
	}
	if value, ok := _c.mutation.ProductType(); ok {
		_spec.SetField(smsorder.FieldProductType, field.TypeString, value)
		_node.ProductType = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(smsorder.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ProviderOrderID(); ok {
		_spec.SetField(smsorder.FieldProviderOrderID, field.TypeString, value)
		_node.ProviderOrderID = value
	}
	if value, ok := _c.mutation.PhoneNumber(); ok {
		_spec.SetField(smsorder.FieldPhoneNumber, field.TypeString, value)
		_node.PhoneNumber = value
	}
	if value, ok := _c.mutation.ProviderCostSnapshot(); ok {
		_spec.SetField(smsorder.FieldProviderCostSnapshot, field.TypeFloat64, value)
		_node.ProviderCostSnapshot = value
	}
	if value, ok := _c.mutation.SalePriceSnapshot(); ok {
		_spec.SetField(smsorder.FieldSalePriceSnapshot, field.TypeFloat64, value)
		_node.SalePriceSnapshot = value
	}
	if value, ok := _c.mutation.SuccessRateSnapshot(); ok {
		_spec.SetField(smsorder.FieldSuccessRateSnapshot, field.TypeFloat64, value)
		_node.SuccessRateSnapshot = value
	}
	if value, ok := _c.mutation.SuccessRateSourceSnapshot(); ok {
		_spec.SetField(smsorder.FieldSuccessRateSourceSnapshot, field.TypeString, value)
		_node.SuccessRateSourceSnapshot = value
	}
	if value, ok := _c.mutation.SuccessRateGradeSnapshot(); ok {
		_spec.SetField(smsorder.FieldSuccessRateGradeSnapshot, field.TypeString, value)
		_node.SuccessRateGradeSnapshot = value
	}
	if value, ok := _c.mutation.SuccessRateMultiplierSnapshot(); ok {
		_spec.SetField(smsorder.FieldSuccessRateMultiplierSnapshot, field.TypeFloat64, value)
		_node.SuccessRateMultiplierSnapshot = value
	}
	if value, ok := _c.mutation.CurrencySnapshot(); ok {
		_spec.SetField(smsorder.FieldCurrencySnapshot, field.TypeString, value)
		_node.CurrencySnapshot = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(smsorder.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(smsorder.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.RefundStatus(); ok {
		_spec.SetField(smsorder.FieldRefundStatus, field.TypeString, value)
		_node.RefundStatus = value
	}
	if value, ok := _c.mutation.RefundReason(); ok {
		_spec.SetField(smsorder.FieldRefundReason, field.TypeString, value)
		_node.RefundReason = value
	}
	if value, ok := _c.mutation.LastProviderError(); ok {
		_spec.SetField(smsorder.FieldLastProviderError, field.TypeString, value)
		_node.LastProviderError = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(smsorder.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(smsorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(smsorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SmsOrder.Create().
//		SetPublicID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SmsOrderUpsert) {
//			SetPublicID(v+v).
//		}).
//		Exec(ctx)
func (_c *SmsOrderCreate) OnConflict(opts ...sql.ConflictOption) *SmsOrderUpsertOne {
	_c.conflict = opts
	return &SmsOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SmsOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SmsOrderCreate) OnConflictColumns(columns ...string) *SmsOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SmsOrderUpsertOne{
		create: _c,
	}
}

type (
	// SmsOrderUpsertOne is the builder for "upsert"-ing
	//  one SmsOrder node.
	SmsOrderUpsertOne struct {
		create *SmsOrderCreate
	}

	// SmsOrderUpsert is the "OnConflict" setter.
	SmsOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetPublicID sets the "public_id" field.
func (u *SmsOrderUpsert) SetPublicID(v uuid.UUID) *SmsOrderUpsert {
	u.Set(smsorder.FieldPublicID, v)
	return u
}

// UpdatePublicID sets the "public_id" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdatePublicID() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldPublicID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *SmsOrderUpsert) SetUserID(v int64) *SmsOrderUpsert {
	u.Set(smsorder.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateUserID() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *SmsOrderUpsert) AddUserID(v int64) *SmsOrderUpsert {
	u.Add(smsorder.FieldUserID, v)
	return u
}

// SetChannelID sets the "channel_id" field.
func (u *SmsOrderUpsert) SetChannelID(v int64) *SmsOrderUpsert {
	u.Set(smsorder.FieldChannelID, v)
	return u
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateChannelID() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldChannelID)
	return u
}

// AddChannelID adds v to the "channel_id" field.
func (u *SmsOrderUpsert) AddChannelID(v int64) *SmsOrderUpsert {
	u.Add(smsorder.FieldChannelID, v)
	return u
}

// SetProviderID sets the "provider_id" field.
func (u *SmsOrderUpsert) SetProviderID(v int64) *SmsOrderUpsert {
	u.Set(smsorder.FieldProviderID, v)
	return u
}

// UpdateProviderID sets the "provider_id" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateProviderID() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldProviderID)
	return u
}

// AddProviderID adds v to the "provider_id" field.
func (u *SmsOrderUpsert) AddProviderID(v int64) *SmsOrderUpsert {
	u.Add(smsorder.FieldProviderID, v)
	return u
}

// SetServiceID sets the "service_id" field.
func (u *SmsOrderUpsert) SetServiceID(v int64) *SmsOrderUpsert {
	u.Set(smsorder.FieldServiceID, v)
	return u
}

// UpdateServiceID sets the "service_id" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateServiceID() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldServiceID)
	return u
}

// AddServiceID adds v to the "service_id" field.
func (u *SmsOrderUpsert) AddServiceID(v int64) *SmsOrderUpsert {
	u.Add(smsorder.FieldServiceID, v)
	return u
}

// SetCountryID sets the "country_id" field.
func (u *SmsOrderUpsert) SetCountryID(v int64) *SmsOrderUpsert {
	u.Set(smsorder.FieldCountryID, v)
	return u
}

// UpdateCountryID sets the "country_id" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateCountryID() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldCountryID)
	return u
}

// AddCountryID adds v to the "country_id" field.
func (u *SmsOrderUpsert) AddCountryID(v int64) *SmsOrderUpsert {
	u.Add(smsorder.FieldCountryID, v)
	return u
}

// SetProductType sets the "product_type" field.
func (u *SmsOrderUpsert) SetProductType(v string) *SmsOrderUpsert {
	u.Set(smsorder.FieldProductType, v)
	return u
}

// UpdateProductType sets the "product_type" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateProductType() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldProductType)
	return u
}

// SetStatus sets the "status" field.
func (u *SmsOrderUpsert) SetStatus(v string) *SmsOrderUpsert {
	u.Set(smsorder.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateStatus() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldStatus)
	return u
}

// SetProviderOrderID sets the "provider_order_id" field.
func (u *SmsOrderUpsert) SetProviderOrderID(v string) *SmsOrderUpsert {
	u.Set(smsorder.FieldProviderOrderID, v)
	return u
}

// UpdateProviderOrderID sets the "provider_order_id" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateProviderOrderID() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldProviderOrderID)
	return u
}

// SetPhoneNumber sets the "phone_number" field.
func (u *SmsOrderUpsert) SetPhoneNumber(v string) *SmsOrderUpsert {
	u.Set(smsorder.FieldPhoneNumber, v)
	return u
}

// UpdatePhoneNumber sets the "phone_number" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdatePhoneNumber() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldPhoneNumber)
	return u
}

// SetProviderCostSnapshot sets the "provider_cost_snapshot" field.
func (u *SmsOrderUpsert) SetProviderCostSnapshot(v float64) *SmsOrderUpsert {
	u.Set(smsorder.FieldProviderCostSnapshot, v)
	return u
}

// UpdateProviderCostSnapshot sets the "provider_cost_snapshot" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateProviderCostSnapshot() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldProviderCostSnapshot)
	return u
}

// AddProviderCostSnapshot adds v to the "provider_cost_snapshot" field.
func (u *SmsOrderUpsert) AddProviderCostSnapshot(v float64) *SmsOrderUpsert {
	u.Add(smsorder.FieldProviderCostSnapshot, v)
	return u
}

// SetSalePriceSnapshot sets the "sale_price_snapshot" field.
func (u *SmsOrderUpsert) SetSalePriceSnapshot(v float64) *SmsOrderUpsert {
	u.Set(smsorder.FieldSalePriceSnapshot, v)
	return u
}

// UpdateSalePriceSnapshot sets the "sale_price_snapshot" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateSalePriceSnapshot() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldSalePriceSnapshot)
	return u
}

// AddSalePriceSnapshot adds v to the "sale_price_snapshot" field.
func (u *SmsOrderUpsert) AddSalePriceSnapshot(v float64) *SmsOrderUpsert {
	u.Add(smsorder.FieldSalePriceSnapshot, v)
	return u
}

// SetSuccessRateSnapshot sets the "success_rate_snapshot" field.
func (u *SmsOrderUpsert) SetSuccessRateSnapshot(v float64) *SmsOrderUpsert {
	u.Set(smsorder.FieldSuccessRateSnapshot, v)
	return u
}

// UpdateSuccessRateSnapshot sets the "success_rate_snapshot" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateSuccessRateSnapshot() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldSuccessRateSnapshot)
	return u
}

// AddSuccessRateSnapshot adds v to the "success_rate_snapshot" field.
func (u *SmsOrderUpsert) AddSuccessRateSnapshot(v float64) *SmsOrderUpsert {
	u.Add(smsorder.FieldSuccessRateSnapshot, v)
	return u
}

// ClearSuccessRateSnapshot clears the value of the "success_rate_snapshot" field.
func (u *SmsOrderUpsert) ClearSuccessRateSnapshot() *SmsOrderUpsert {
	u.SetNull(smsorder.FieldSuccessRateSnapshot)
	return u
}

// SetSuccessRateSourceSnapshot sets the "success_rate_source_snapshot" field.
func (u *SmsOrderUpsert) SetSuccessRateSourceSnapshot(v string) *SmsOrderUpsert {
	u.Set(smsorder.FieldSuccessRateSourceSnapshot, v)
	return u
}

// UpdateSuccessRateSourceSnapshot sets the "success_rate_source_snapshot" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateSuccessRateSourceSnapshot() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldSuccessRateSourceSnapshot)
	return u
}

// SetSuccessRateGradeSnapshot sets the "success_rate_grade_snapshot" field.
func (u *SmsOrderUpsert) SetSuccessRateGradeSnapshot(v string) *SmsOrderUpsert {
	u.Set(smsorder.FieldSuccessRateGradeSnapshot, v)
	return u
}

// UpdateSuccessRateGradeSnapshot sets the "success_rate_grade_snapshot" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateSuccessRateGradeSnapshot() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldSuccessRateGradeSnapshot)
	return u
}

// SetSuccessRateMultiplierSnapshot sets the "success_rate_multiplier_snapshot" field.
func (u *SmsOrderUpsert) SetSuccessRateMultiplierSnapshot(v float64) *SmsOrderUpsert {
	u.Set(smsorder.FieldSuccessRateMultiplierSnapshot, v)
	return u
}

// UpdateSuccessRateMultiplierSnapshot sets the "success_rate_multiplier_snapshot" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateSuccessRateMultiplierSnapshot() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldSuccessRateMultiplierSnapshot)
	return u
}

// AddSuccessRateMultiplierSnapshot adds v to the "success_rate_multiplier_snapshot" field.
func (u *SmsOrderUpsert) AddSuccessRateMultiplierSnapshot(v float64) *SmsOrderUpsert {
	u.Add(smsorder.FieldSuccessRateMultiplierSnapshot, v)
	return u
}

// SetCurrencySnapshot sets the "currency_snapshot" field.
func (u *SmsOrderUpsert) SetCurrencySnapshot(v string) *SmsOrderUpsert {
	u.Set(smsorder.FieldCurrencySnapshot, v)
	return u
}

// UpdateCurrencySnapshot sets the "currency_snapshot" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateCurrencySnapshot() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldCurrencySnapshot)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *SmsOrderUpsert) SetExpiresAt(v time.Time) *SmsOrderUpsert {
	u.Set(smsorder.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateExpiresAt() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *SmsOrderUpsert) ClearExpiresAt() *SmsOrderUpsert {
	u.SetNull(smsorder.FieldExpiresAt)
	return u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *SmsOrderUpsert) SetIdempotencyKey(v string) *SmsOrderUpsert {
	u.Set(smsorder.FieldIdempotencyKey, v)
	return u
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateIdempotencyKey() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldIdempotencyKey)
	return u
}

// SetRefundStatus sets the "refund_status" field.
func (u *SmsOrderUpsert) SetRefundStatus(v string) *SmsOrderUpsert {
	u.Set(smsorder.FieldRefundStatus, v)
	return u
}

// UpdateRefundStatus sets the "refund_status" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateRefundStatus() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldRefundStatus)
	return u
}

// SetRefundReason sets the "refund_reason" field.
func (u *SmsOrderUpsert) SetRefundReason(v string) *SmsOrderUpsert {
	u.Set(smsorder.FieldRefundReason, v)
	return u
}

// UpdateRefundReason sets the "refund_reason" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateRefundReason() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldRefundReason)
	return u
}

// SetLastProviderError sets the "last_provider_error" field.
func (u *SmsOrderUpsert) SetLastProviderError(v string) *SmsOrderUpsert {
	u.Set(smsorder.FieldLastProviderError, v)
	return u
}

// UpdateLastProviderError sets the "last_provider_error" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateLastProviderError() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldLastProviderError)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *SmsOrderUpsert) SetMetadata(v map[string]interface{}) *SmsOrderUpsert {
	u.Set(smsorder.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateMetadata() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldMetadata)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *SmsOrderUpsert) SetCreatedAt(v time.Time) *SmsOrderUpsert {
	u.Set(smsorder.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateCreatedAt() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SmsOrderUpsert) SetUpdatedAt(v time.Time) *SmsOrderUpsert {
	u.Set(smsorder.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateUpdatedAt() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SmsOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SmsOrderUpsertOne) UpdateNewValues() *SmsOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SmsOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SmsOrderUpsertOne) Ignore() *SmsOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SmsOrderUpsertOne) DoNothing() *SmsOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SmsOrderCreate.OnConflict
// documentation for more info.
func (u *SmsOrderUpsertOne) Update(set func(*SmsOrderUpsert)) *SmsOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SmsOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetPublicID sets the "public_id" field.
func (u *SmsOrderUpsertOne) SetPublicID(v uuid.UUID) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetPublicID(v)
	})
}

// UpdatePublicID sets the "public_id" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdatePublicID() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdatePublicID()
	})
}

// SetUserID sets the "user_id" field.
func (u *SmsOrderUpsertOne) SetUserID(v int64) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *SmsOrderUpsertOne) AddUserID(v int64) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateUserID() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetChannelID sets the "channel_id" field.
func (u *SmsOrderUpsertOne) SetChannelID(v int64) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetChannelID(v)
	})
}

// AddChannelID adds v to the "channel_id" field.
func (u *SmsOrderUpsertOne) AddChannelID(v int64) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.AddChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateChannelID() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateChannelID()
	})
}

// SetProviderID sets the "provider_id" field.
func (u *SmsOrderUpsertOne) SetProviderID(v int64) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetProviderID(v)
	})
}

// AddProviderID adds v to the "provider_id" field.
func (u *SmsOrderUpsertOne) AddProviderID(v int64) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.AddProviderID(v)
	})
}

// UpdateProviderID sets the "provider_id" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateProviderID() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateProviderID()
	})
}

// SetServiceID sets the "service_id" field.
func (u *SmsOrderUpsertOne) SetServiceID(v int64) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetServiceID(v)
	})
}

// AddServiceID adds v to the "service_id" field.
func (u *SmsOrderUpsertOne) AddServiceID(v int64) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.AddServiceID(v)
	})
}

// UpdateServiceID sets the "service_id" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateServiceID() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateServiceID()
	})
}

// SetCountryID sets the "country_id" field.
func (u *SmsOrderUpsertOne) SetCountryID(v int64) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetCountryID(v)
	})
}

// AddCountryID adds v to the "country_id" field.
func (u *SmsOrderUpsertOne) AddCountryID(v int64) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.AddCountryID(v)
	})
}

// UpdateCountryID sets the "country_id" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateCountryID() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateCountryID()
	})
}

// SetProductType sets the "product_type" field.
func (u *SmsOrderUpsertOne) SetProductType(v string) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetProductType(v)
	})
}

// UpdateProductType sets the "product_type" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateProductType() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateProductType()
	})
}

// SetStatus sets the "status" field.
func (u *SmsOrderUpsertOne) SetStatus(v string) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateStatus() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetProviderOrderID sets the "provider_order_id" field.
func (u *SmsOrderUpsertOne) SetProviderOrderID(v string) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetProviderOrderID(v)
	})
}

// UpdateProviderOrderID sets the "provider_order_id" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateProviderOrderID() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateProviderOrderID()
	})
}

// SetPhoneNumber sets the "phone_number" field.
func (u *SmsOrderUpsertOne) SetPhoneNumber(v string) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetPhoneNumber(v)
	})
}

// UpdatePhoneNumber sets the "phone_number" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdatePhoneNumber() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdatePhoneNumber()
	})
}

// SetProviderCostSnapshot sets the "provider_cost_snapshot" field.
func (u *SmsOrderUpsertOne) SetProviderCostSnapshot(v float64) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetProviderCostSnapshot(v)
	})
}

// AddProviderCostSnapshot adds v to the "provider_cost_snapshot" field.
func (u *SmsOrderUpsertOne) AddProviderCostSnapshot(v float64) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.AddProviderCostSnapshot(v)
	})
}

// UpdateProviderCostSnapshot sets the "provider_cost_snapshot" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateProviderCostSnapshot() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateProviderCostSnapshot()
	})
}

// SetSalePriceSnapshot sets the "sale_price_snapshot" field.
func (u *SmsOrderUpsertOne) SetSalePriceSnapshot(v float64) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetSalePriceSnapshot(v)
	})
}

// AddSalePriceSnapshot adds v to the "sale_price_snapshot" field.
func (u *SmsOrderUpsertOne) AddSalePriceSnapshot(v float64) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.AddSalePriceSnapshot(v)
	})
}

// UpdateSalePriceSnapshot sets the "sale_price_snapshot" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateSalePriceSnapshot() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateSalePriceSnapshot()
	})
}

// SetSuccessRateSnapshot sets the "success_rate_snapshot" field.
func (u *SmsOrderUpsertOne) SetSuccessRateSnapshot(v float64) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetSuccessRateSnapshot(v)
	})
}

// AddSuccessRateSnapshot adds v to the "success_rate_snapshot" field.
func (u *SmsOrderUpsertOne) AddSuccessRateSnapshot(v float64) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.AddSuccessRateSnapshot(v)
	})
}

// UpdateSuccessRateSnapshot sets the "success_rate_snapshot" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateSuccessRateSnapshot() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateSuccessRateSnapshot()
	})
}

// ClearSuccessRateSnapshot clears the value of the "success_rate_snapshot" field.
func (u *SmsOrderUpsertOne) ClearSuccessRateSnapshot() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.ClearSuccessRateSnapshot()
	})
}

// SetSuccessRateSourceSnapshot sets the "success_rate_source_snapshot" field.
func (u *SmsOrderUpsertOne) SetSuccessRateSourceSnapshot(v string) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetSuccessRateSourceSnapshot(v)
	})
}

// UpdateSuccessRateSourceSnapshot sets the "success_rate_source_snapshot" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateSuccessRateSourceSnapshot() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateSuccessRateSourceSnapshot()
	})
}

// SetSuccessRateGradeSnapshot sets the "success_rate_grade_snapshot" field.
func (u *SmsOrderUpsertOne) SetSuccessRateGradeSnapshot(v string) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetSuccessRateGradeSnapshot(v)
	})
}

// UpdateSuccessRateGradeSnapshot sets the "success_rate_grade_snapshot" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateSuccessRateGradeSnapshot() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateSuccessRateGradeSnapshot()
	})
}

// SetSuccessRateMultiplierSnapshot sets the "success_rate_multiplier_snapshot" field.
func (u *SmsOrderUpsertOne) SetSuccessRateMultiplierSnapshot(v float64) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetSuccessRateMultiplierSnapshot(v)
	})
}

// AddSuccessRateMultiplierSnapshot adds v to the "success_rate_multiplier_snapshot" field.
func (u *SmsOrderUpsertOne) AddSuccessRateMultiplierSnapshot(v float64) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.AddSuccessRateMultiplierSnapshot(v)
	})
}

// UpdateSuccessRateMultiplierSnapshot sets the "success_rate_multiplier_snapshot" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateSuccessRateMultiplierSnapshot() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateSuccessRateMultiplierSnapshot()
	})
}

// SetCurrencySnapshot sets the "currency_snapshot" field.
func (u *SmsOrderUpsertOne) SetCurrencySnapshot(v string) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetCurrencySnapshot(v)
	})
}

// UpdateCurrencySnapshot sets the "currency_snapshot" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateCurrencySnapshot() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateCurrencySnapshot()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *SmsOrderUpsertOne) SetExpiresAt(v time.Time) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateExpiresAt() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *SmsOrderUpsertOne) ClearExpiresAt() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.ClearExpiresAt()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *SmsOrderUpsertOne) SetIdempotencyKey(v string) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateIdempotencyKey() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// SetRefundStatus sets the "refund_status" field.
func (u *SmsOrderUpsertOne) SetRefundStatus(v string) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetRefundStatus(v)
	})
}

// UpdateRefundStatus sets the "refund_status" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateRefundStatus() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateRefundStatus()
	})
}

// SetRefundReason sets the "refund_reason" field.
func (u *SmsOrderUpsertOne) SetRefundReason(v string) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetRefundReason(v)
	})
}

// UpdateRefundReason sets the "refund_reason" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateRefundReason() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateRefundReason()
	})
}

// SetLastProviderError sets the "last_provider_error" field.
func (u *SmsOrderUpsertOne) SetLastProviderError(v string) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetLastProviderError(v)
	})
}

// UpdateLastProviderError sets the "last_provider_error" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateLastProviderError() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateLastProviderError()
	})
}

// SetMetadata sets the "metadata" field.
func (u *SmsOrderUpsertOne) SetMetadata(v map[string]interface{}) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateMetadata() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateMetadata()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *SmsOrderUpsertOne) SetCreatedAt(v time.Time) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateCreatedAt() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SmsOrderUpsertOne) SetUpdatedAt(v time.Time) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateUpdatedAt() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SmsOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SmsOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SmsOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SmsOrderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SmsOrderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SmsOrderCreateBulk is the builder for creating many SmsOrder entities in bulk.
type SmsOrderCreateBulk struct {
	config
	err      error
	builders []*SmsOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the SmsOrder entities in the database.
func (_c *SmsOrderCreateBulk) Save(ctx context.Context) ([]*SmsOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SmsOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SmsOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SmsOrderCreateBulk) SaveX(ctx context.Context) []*SmsOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SmsOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SmsOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SmsOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SmsOrderUpsert) {
//			SetPublicID(v+v).
//		}).
//		Exec(ctx)
func (_c *SmsOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *SmsOrderUpsertBulk {
	_c.conflict = opts
	return &SmsOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SmsOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SmsOrderCreateBulk) OnConflictColumns(columns ...string) *SmsOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SmsOrderUpsertBulk{
		create: _c,
	}
}

// SmsOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of SmsOrder nodes.
type SmsOrderUpsertBulk struct {
	create *SmsOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SmsOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SmsOrderUpsertBulk) UpdateNewValues() *SmsOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SmsOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SmsOrderUpsertBulk) Ignore() *SmsOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SmsOrderUpsertBulk) DoNothing() *SmsOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SmsOrderCreateBulk.OnConflict
// documentation for more info.
func (u *SmsOrderUpsertBulk) Update(set func(*SmsOrderUpsert)) *SmsOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SmsOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetPublicID sets the "public_id" field.
func (u *SmsOrderUpsertBulk) SetPublicID(v uuid.UUID) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetPublicID(v)
	})
}

// UpdatePublicID sets the "public_id" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdatePublicID() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdatePublicID()
	})
}

// SetUserID sets the "user_id" field.
func (u *SmsOrderUpsertBulk) SetUserID(v int64) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *SmsOrderUpsertBulk) AddUserID(v int64) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateUserID() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetChannelID sets the "channel_id" field.
func (u *SmsOrderUpsertBulk) SetChannelID(v int64) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetChannelID(v)
	})
}

// AddChannelID adds v to the "channel_id" field.
func (u *SmsOrderUpsertBulk) AddChannelID(v int64) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.AddChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateChannelID() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateChannelID()
	})
}

// SetProviderID sets the "provider_id" field.
func (u *SmsOrderUpsertBulk) SetProviderID(v int64) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetProviderID(v)
	})
}

// AddProviderID adds v to the "provider_id" field.
func (u *SmsOrderUpsertBulk) AddProviderID(v int64) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.AddProviderID(v)
	})
}

// UpdateProviderID sets the "provider_id" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateProviderID() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateProviderID()
	})
}

// SetServiceID sets the "service_id" field.
func (u *SmsOrderUpsertBulk) SetServiceID(v int64) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetServiceID(v)
	})
}

// AddServiceID adds v to the "service_id" field.
func (u *SmsOrderUpsertBulk) AddServiceID(v int64) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.AddServiceID(v)
	})
}

// UpdateServiceID sets the "service_id" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateServiceID() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateServiceID()
	})
}

// SetCountryID sets the "country_id" field.
func (u *SmsOrderUpsertBulk) SetCountryID(v int64) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetCountryID(v)
	})
}

// AddCountryID adds v to the "country_id" field.
func (u *SmsOrderUpsertBulk) AddCountryID(v int64) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.AddCountryID(v)
	})
}

// UpdateCountryID sets the "country_id" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateCountryID() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateCountryID()
	})
}

// SetProductType sets the "product_type" field.
func (u *SmsOrderUpsertBulk) SetProductType(v string) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetProductType(v)
	})
}

// UpdateProductType sets the "product_type" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateProductType() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateProductType()
	})
}

// SetStatus sets the "status" field.
func (u *SmsOrderUpsertBulk) SetStatus(v string) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateStatus() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetProviderOrderID sets the "provider_order_id" field.
func (u *SmsOrderUpsertBulk) SetProviderOrderID(v string) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetProviderOrderID(v)
	})
}

// UpdateProviderOrderID sets the "provider_order_id" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateProviderOrderID() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateProviderOrderID()
	})
}

// SetPhoneNumber sets the "phone_number" field.
func (u *SmsOrderUpsertBulk) SetPhoneNumber(v string) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetPhoneNumber(v)
	})
}

// UpdatePhoneNumber sets the "phone_number" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdatePhoneNumber() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdatePhoneNumber()
	})
}

// SetProviderCostSnapshot sets the "provider_cost_snapshot" field.
func (u *SmsOrderUpsertBulk) SetProviderCostSnapshot(v float64) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetProviderCostSnapshot(v)
	})
}

// AddProviderCostSnapshot adds v to the "provider_cost_snapshot" field.
func (u *SmsOrderUpsertBulk) AddProviderCostSnapshot(v float64) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.AddProviderCostSnapshot(v)
	})
}

// UpdateProviderCostSnapshot sets the "provider_cost_snapshot" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateProviderCostSnapshot() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateProviderCostSnapshot()
	})
}

// SetSalePriceSnapshot sets the "sale_price_snapshot" field.
func (u *SmsOrderUpsertBulk) SetSalePriceSnapshot(v float64) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetSalePriceSnapshot(v)
	})
}

// AddSalePriceSnapshot adds v to the "sale_price_snapshot" field.
func (u *SmsOrderUpsertBulk) AddSalePriceSnapshot(v float64) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.AddSalePriceSnapshot(v)
	})
}

// UpdateSalePriceSnapshot sets the "sale_price_snapshot" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateSalePriceSnapshot() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateSalePriceSnapshot()
	})
}

// SetSuccessRateSnapshot sets the "success_rate_snapshot" field.
func (u *SmsOrderUpsertBulk) SetSuccessRateSnapshot(v float64) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetSuccessRateSnapshot(v)
	})
}

// AddSuccessRateSnapshot adds v to the "success_rate_snapshot" field.
func (u *SmsOrderUpsertBulk) AddSuccessRateSnapshot(v float64) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.AddSuccessRateSnapshot(v)
	})
}

// UpdateSuccessRateSnapshot sets the "success_rate_snapshot" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateSuccessRateSnapshot() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateSuccessRateSnapshot()
	})
}

// ClearSuccessRateSnapshot clears the value of the "success_rate_snapshot" field.
func (u *SmsOrderUpsertBulk) ClearSuccessRateSnapshot() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.ClearSuccessRateSnapshot()
	})
}

// SetSuccessRateSourceSnapshot sets the "success_rate_source_snapshot" field.
func (u *SmsOrderUpsertBulk) SetSuccessRateSourceSnapshot(v string) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetSuccessRateSourceSnapshot(v)
	})
}

// UpdateSuccessRateSourceSnapshot sets the "success_rate_source_snapshot" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateSuccessRateSourceSnapshot() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateSuccessRateSourceSnapshot()
	})
}

// SetSuccessRateGradeSnapshot sets the "success_rate_grade_snapshot" field.
func (u *SmsOrderUpsertBulk) SetSuccessRateGradeSnapshot(v string) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetSuccessRateGradeSnapshot(v)
	})
}

// UpdateSuccessRateGradeSnapshot sets the "success_rate_grade_snapshot" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateSuccessRateGradeSnapshot() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateSuccessRateGradeSnapshot()
	})
}

// SetSuccessRateMultiplierSnapshot sets the "success_rate_multiplier_snapshot" field.
func (u *SmsOrderUpsertBulk) SetSuccessRateMultiplierSnapshot(v float64) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetSuccessRateMultiplierSnapshot(v)
	})
}

// AddSuccessRateMultiplierSnapshot adds v to the "success_rate_multiplier_snapshot" field.
func (u *SmsOrderUpsertBulk) AddSuccessRateMultiplierSnapshot(v float64) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.AddSuccessRateMultiplierSnapshot(v)
	})
}

// UpdateSuccessRateMultiplierSnapshot sets the "success_rate_multiplier_snapshot" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateSuccessRateMultiplierSnapshot() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateSuccessRateMultiplierSnapshot()
	})
}

// SetCurrencySnapshot sets the "currency_snapshot" field.
func (u *SmsOrderUpsertBulk) SetCurrencySnapshot(v string) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetCurrencySnapshot(v)
	})
}

// UpdateCurrencySnapshot sets the "currency_snapshot" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateCurrencySnapshot() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateCurrencySnapshot()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *SmsOrderUpsertBulk) SetExpiresAt(v time.Time) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateExpiresAt() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *SmsOrderUpsertBulk) ClearExpiresAt() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.ClearExpiresAt()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *SmsOrderUpsertBulk) SetIdempotencyKey(v string) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateIdempotencyKey() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// SetRefundStatus sets the "refund_status" field.
func (u *SmsOrderUpsertBulk) SetRefundStatus(v string) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetRefundStatus(v)
	})
}

// UpdateRefundStatus sets the "refund_status" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateRefundStatus() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateRefundStatus()
	})
}

// SetRefundReason sets the "refund_reason" field.
func (u *SmsOrderUpsertBulk) SetRefundReason(v string) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetRefundReason(v)
	})
}

// UpdateRefundReason sets the "refund_reason" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateRefundReason() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateRefundReason()
	})
}

// SetLastProviderError sets the "last_provider_error" field.
func (u *SmsOrderUpsertBulk) SetLastProviderError(v string) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetLastProviderError(v)
	})
}

// UpdateLastProviderError sets the "last_provider_error" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateLastProviderError() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateLastProviderError()
	})
}

// SetMetadata sets the "metadata" field.
func (u *SmsOrderUpsertBulk) SetMetadata(v map[string]interface{}) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateMetadata() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateMetadata()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *SmsOrderUpsertBulk) SetCreatedAt(v time.Time) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateCreatedAt() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SmsOrderUpsertBulk) SetUpdatedAt(v time.Time) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateUpdatedAt() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SmsOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SmsOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SmsOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SmsOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
