// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/smsorder"
	"github.com/google/uuid"
)

// SmsOrder is the model entity for the SmsOrder schema.
type SmsOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// PublicID holds the value of the "public_id" field.
	PublicID uuid.UUID `json:"public_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// ChannelID holds the value of the "channel_id" field.
	ChannelID int64 `json:"channel_id,omitempty"`
	// ProviderID holds the value of the "provider_id" field.
	ProviderID int64 `json:"provider_id,omitempty"`
	// ServiceID holds the value of the "service_id" field.
	ServiceID int64 `json:"service_id,omitempty"`
	// CountryID holds the value of the "country_id" field.
	CountryID int64 `json:"country_id,omitempty"`
	// ProductType holds the value of the "product_type" field.
	ProductType string `json:"product_type,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ProviderOrderID holds the value of the "provider_order_id" field.
	ProviderOrderID string `json:"provider_order_id,omitempty"`
	// PhoneNumber holds the value of the "phone_number" field.
	PhoneNumber string `json:"phone_number,omitempty"`
	// ProviderCostSnapshot holds the value of the "provider_cost_snapshot" field.
	ProviderCostSnapshot float64 `json:"provider_cost_snapshot,omitempty"`
	// SalePriceSnapshot holds the value of the "sale_price_snapshot" field.
	SalePriceSnapshot float64 `json:"sale_price_snapshot,omitempty"`
	// SuccessRateSnapshot holds the value of the "success_rate_snapshot" field.
	SuccessRateSnapshot float64 `json:"success_rate_snapshot,omitempty"`
	// SuccessRateSourceSnapshot holds the value of the "success_rate_source_snapshot" field.
	SuccessRateSourceSnapshot string `json:"success_rate_source_snapshot,omitempty"`
	// SuccessRateGradeSnapshot holds the value of the "success_rate_grade_snapshot" field.
	SuccessRateGradeSnapshot string `json:"success_rate_grade_snapshot,omitempty"`
	// SuccessRateMultiplierSnapshot holds the value of the "success_rate_multiplier_snapshot" field.
	SuccessRateMultiplierSnapshot float64 `json:"success_rate_multiplier_snapshot,omitempty"`
	// CurrencySnapshot holds the value of the "currency_snapshot" field.
	CurrencySnapshot string `json:"currency_snapshot,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// RefundStatus holds the value of the "refund_status" field.
	RefundStatus string `json:"refund_status,omitempty"`
	// RefundReason holds the value of the "refund_reason" field.
	RefundReason string `json:"refund_reason,omitempty"`
	// LastProviderError holds the value of the "last_provider_error" field.
	LastProviderError string `json:"last_provider_error,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SmsOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case smsorder.FieldMetadata:
			values[i] = new([]byte)
		case smsorder.FieldProviderCostSnapshot, smsorder.FieldSalePriceSnapshot, smsorder.FieldSuccessRateSnapshot, smsorder.FieldSuccessRateMultiplierSnapshot:
			values[i] = new(sql.NullFloat64)
		case smsorder.FieldID, smsorder.FieldUserID, smsorder.FieldChannelID, smsorder.FieldProviderID, smsorder.FieldServiceID, smsorder.FieldCountryID:
			values[i] = new(sql.NullInt64)
		case smsorder.FieldProductType, smsorder.FieldStatus, smsorder.FieldProviderOrderID, smsorder.FieldPhoneNumber, smsorder.FieldSuccessRateSourceSnapshot, smsorder.FieldSuccessRateGradeSnapshot, smsorder.FieldCurrencySnapshot, smsorder.FieldIdempotencyKey, smsorder.FieldRefundStatus, smsorder.FieldRefundReason, smsorder.FieldLastProviderError:
			values[i] = new(sql.NullString)
		case smsorder.FieldExpiresAt, smsorder.FieldCreatedAt, smsorder.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case smsorder.FieldPublicID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SmsOrder fields.
func (_m *SmsOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case smsorder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case smsorder.FieldPublicID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field public_id", values[i])
			} else if value != nil {
				_m.PublicID = *value
			}
		case smsorder.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case smsorder.FieldChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = value.Int64
			}
		case smsorder.FieldProviderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_id", values[i])
			} else if value.Valid {
				_m.ProviderID = value.Int64
			}
		case smsorder.FieldServiceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field service_id", values[i])
			} else if value.Valid {
				_m.ServiceID = value.Int64
			}
		case smsorder.FieldCountryID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field country_id", values[i])
			} else if value.Valid {
				_m.CountryID = value.Int64
			}
		case smsorder.FieldProductType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_type", values[i])
			} else if value.Valid {
				_m.ProductType = value.String
			}
		case smsorder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case smsorder.FieldProviderOrderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_order_id", values[i])
			} else if value.Valid {
				_m.ProviderOrderID = value.String
			}
		case smsorder.FieldPhoneNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone_number", values[i])
			} else if value.Valid {
				_m.PhoneNumber = value.String
			}
		case smsorder.FieldProviderCostSnapshot:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_cost_snapshot", values[i])
			} else if value.Valid {
				_m.ProviderCostSnapshot = value.Float64
			}
		case smsorder.FieldSalePriceSnapshot:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field sale_price_snapshot", values[i])
			} else if value.Valid {
				_m.SalePriceSnapshot = value.Float64
			}
		case smsorder.FieldSuccessRateSnapshot:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field success_rate_snapshot", values[i])
			} else if value.Valid {
				_m.SuccessRateSnapshot = value.Float64
			}
		case smsorder.FieldSuccessRateSourceSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field success_rate_source_snapshot", values[i])
			} else if value.Valid {
				_m.SuccessRateSourceSnapshot = value.String
			}
		case smsorder.FieldSuccessRateGradeSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field success_rate_grade_snapshot", values[i])
			} else if value.Valid {
				_m.SuccessRateGradeSnapshot = value.String
			}
		case smsorder.FieldSuccessRateMultiplierSnapshot:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field success_rate_multiplier_snapshot", values[i])
			} else if value.Valid {
				_m.SuccessRateMultiplierSnapshot = value.Float64
			}
		case smsorder.FieldCurrencySnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency_snapshot", values[i])
			} else if value.Valid {
				_m.CurrencySnapshot = value.String
			}
		case smsorder.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case smsorder.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = value.String
			}
		case smsorder.FieldRefundStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_status", values[i])
			} else if value.Valid {
				_m.RefundStatus = value.String
			}
		case smsorder.FieldRefundReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_reason", values[i])
			} else if value.Valid {
				_m.RefundReason = value.String
			}
		case smsorder.FieldLastProviderError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_provider_error", values[i])
			} else if value.Valid {
				_m.LastProviderError = value.String
			}
		case smsorder.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case smsorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case smsorder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SmsOrder.
// This includes values selected through modifiers, order, etc.
func (_m *SmsOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SmsOrder.
// Note that you need to call SmsOrder.Unwrap() before calling this method if this SmsOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SmsOrder) Update() *SmsOrderUpdateOne {
	return NewSmsOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SmsOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SmsOrder) Unwrap() *SmsOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SmsOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SmsOrder) String() string {
	var builder strings.Builder
	builder.WriteString("SmsOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("public_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublicID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("channel_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelID))
	builder.WriteString(", ")
	builder.WriteString("provider_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderID))
	builder.WriteString(", ")
	builder.WriteString("service_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ServiceID))
	builder.WriteString(", ")
	builder.WriteString("country_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CountryID))
	builder.WriteString(", ")
	builder.WriteString("product_type=")
	builder.WriteString(_m.ProductType)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("provider_order_id=")
	builder.WriteString(_m.ProviderOrderID)
	builder.WriteString(", ")
	builder.WriteString("phone_number=")
	builder.WriteString(_m.PhoneNumber)
	builder.WriteString(", ")
	builder.WriteString("provider_cost_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderCostSnapshot))
	builder.WriteString(", ")
	builder.WriteString("sale_price_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.SalePriceSnapshot))
	builder.WriteString(", ")
	builder.WriteString("success_rate_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.SuccessRateSnapshot))
	builder.WriteString(", ")
	builder.WriteString("success_rate_source_snapshot=")
	builder.WriteString(_m.SuccessRateSourceSnapshot)
	builder.WriteString(", ")
	builder.WriteString("success_rate_grade_snapshot=")
	builder.WriteString(_m.SuccessRateGradeSnapshot)
	builder.WriteString(", ")
	builder.WriteString("success_rate_multiplier_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.SuccessRateMultiplierSnapshot))
	builder.WriteString(", ")
	builder.WriteString("currency_snapshot=")
	builder.WriteString(_m.CurrencySnapshot)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(_m.IdempotencyKey)
	builder.WriteString(", ")
	builder.WriteString("refund_status=")
	builder.WriteString(_m.RefundStatus)
	builder.WriteString(", ")
	builder.WriteString("refund_reason=")
	builder.WriteString(_m.RefundReason)
	builder.WriteString(", ")
	builder.WriteString("last_provider_error=")
	builder.WriteString(_m.LastProviderError)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SmsOrders is a parsable slice of SmsOrder.
type SmsOrders []*SmsOrder
