// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/smsprovider"
)

// SmsProviderUpdate is the builder for updating SmsProvider entities.
type SmsProviderUpdate struct {
	config
	hooks    []Hook
	mutation *SmsProviderMutation
}

// Where appends a list predicates to the SmsProviderUpdate builder.
func (_u *SmsProviderUpdate) Where(ps ...predicate.SmsProvider) *SmsProviderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *SmsProviderUpdate) SetCode(v string) *SmsProviderUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *SmsProviderUpdate) SetNillableCode(v *string) *SmsProviderUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SmsProviderUpdate) SetName(v string) *SmsProviderUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SmsProviderUpdate) SetNillableName(v *string) *SmsProviderUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *SmsProviderUpdate) SetBaseURL(v string) *SmsProviderUpdate {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *SmsProviderUpdate) SetNillableBaseURL(v *string) *SmsProviderUpdate {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetCredentialRef sets the "credential_ref" field.
func (_u *SmsProviderUpdate) SetCredentialRef(v string) *SmsProviderUpdate {
	_u.mutation.SetCredentialRef(v)
	return _u
}

// SetNillableCredentialRef sets the "credential_ref" field if the given value is not nil.
func (_u *SmsProviderUpdate) SetNillableCredentialRef(v *string) *SmsProviderUpdate {
	if v != nil {
		_u.SetCredentialRef(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *SmsProviderUpdate) SetEnabled(v bool) *SmsProviderUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *SmsProviderUpdate) SetNillableEnabled(v *bool) *SmsProviderUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetHealthStatus sets the "health_status" field.
func (_u *SmsProviderUpdate) SetHealthStatus(v string) *SmsProviderUpdate {
	_u.mutation.SetHealthStatus(v)
	return _u
}

// SetNillableHealthStatus sets the "health_status" field if the given value is not nil.
func (_u *SmsProviderUpdate) SetNillableHealthStatus(v *string) *SmsProviderUpdate {
	if v != nil {
		_u.SetHealthStatus(*v)
	}
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *SmsProviderUpdate) SetCapabilities(v map[string]interface{}) *SmsProviderUpdate {
	_u.mutation.SetCapabilities(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *SmsProviderUpdate) SetMetadata(v map[string]interface{}) *SmsProviderUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SmsProviderUpdate) SetCreatedAt(v time.Time) *SmsProviderUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SmsProviderUpdate) SetNillableCreatedAt(v *time.Time) *SmsProviderUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SmsProviderUpdate) SetUpdatedAt(v time.Time) *SmsProviderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SmsProviderUpdate) SetNillableUpdatedAt(v *time.Time) *SmsProviderUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the SmsProviderMutation object of the builder.
func (_u *SmsProviderUpdate) Mutation() *SmsProviderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SmsProviderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SmsProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SmsProviderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SmsProviderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SmsProviderUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := smsprovider.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "SmsProvider.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := smsprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SmsProvider.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := smsprovider.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "SmsProvider.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CredentialRef(); ok {
		if err := smsprovider.CredentialRefValidator(v); err != nil {
			return &ValidationError{Name: "credential_ref", err: fmt.Errorf(`ent: validator failed for field "SmsProvider.credential_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HealthStatus(); ok {
		if err := smsprovider.HealthStatusValidator(v); err != nil {
			return &ValidationError{Name: "health_status", err: fmt.Errorf(`ent: validator failed for field "SmsProvider.health_status": %w`, err)}
		}
	}
	return nil
}

func (_u *SmsProviderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(smsprovider.Table, smsprovider.Columns, sqlgraph.NewFieldSpec(smsprovider.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(smsprovider.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(smsprovider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(smsprovider.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialRef(); ok {
		_spec.SetField(smsprovider.FieldCredentialRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(smsprovider.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HealthStatus(); ok {
		_spec.SetField(smsprovider.FieldHealthStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(smsprovider.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(smsprovider.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(smsprovider.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(smsprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{smsprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SmsProviderUpdateOne is the builder for updating a single SmsProvider entity.
type SmsProviderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SmsProviderMutation
}

// SetCode sets the "code" field.
func (_u *SmsProviderUpdateOne) SetCode(v string) *SmsProviderUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *SmsProviderUpdateOne) SetNillableCode(v *string) *SmsProviderUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SmsProviderUpdateOne) SetName(v string) *SmsProviderUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SmsProviderUpdateOne) SetNillableName(v *string) *SmsProviderUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *SmsProviderUpdateOne) SetBaseURL(v string) *SmsProviderUpdateOne {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *SmsProviderUpdateOne) SetNillableBaseURL(v *string) *SmsProviderUpdateOne {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetCredentialRef sets the "credential_ref" field.
func (_u *SmsProviderUpdateOne) SetCredentialRef(v string) *SmsProviderUpdateOne {
	_u.mutation.SetCredentialRef(v)
	return _u
}

// SetNillableCredentialRef sets the "credential_ref" field if the given value is not nil.
func (_u *SmsProviderUpdateOne) SetNillableCredentialRef(v *string) *SmsProviderUpdateOne {
	if v != nil {
		_u.SetCredentialRef(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *SmsProviderUpdateOne) SetEnabled(v bool) *SmsProviderUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *SmsProviderUpdateOne) SetNillableEnabled(v *bool) *SmsProviderUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetHealthStatus sets the "health_status" field.
func (_u *SmsProviderUpdateOne) SetHealthStatus(v string) *SmsProviderUpdateOne {
	_u.mutation.SetHealthStatus(v)
	return _u
}

// SetNillableHealthStatus sets the "health_status" field if the given value is not nil.
func (_u *SmsProviderUpdateOne) SetNillableHealthStatus(v *string) *SmsProviderUpdateOne {
	if v != nil {
		_u.SetHealthStatus(*v)
	}
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *SmsProviderUpdateOne) SetCapabilities(v map[string]interface{}) *SmsProviderUpdateOne {
	_u.mutation.SetCapabilities(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *SmsProviderUpdateOne) SetMetadata(v map[string]interface{}) *SmsProviderUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SmsProviderUpdateOne) SetCreatedAt(v time.Time) *SmsProviderUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SmsProviderUpdateOne) SetNillableCreatedAt(v *time.Time) *SmsProviderUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SmsProviderUpdateOne) SetUpdatedAt(v time.Time) *SmsProviderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SmsProviderUpdateOne) SetNillableUpdatedAt(v *time.Time) *SmsProviderUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the SmsProviderMutation object of the builder.
func (_u *SmsProviderUpdateOne) Mutation() *SmsProviderMutation {
	return _u.mutation
}

// Where appends a list predicates to the SmsProviderUpdate builder.
func (_u *SmsProviderUpdateOne) Where(ps ...predicate.SmsProvider) *SmsProviderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SmsProviderUpdateOne) Select(field string, fields ...string) *SmsProviderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SmsProvider entity.
func (_u *SmsProviderUpdateOne) Save(ctx context.Context) (*SmsProvider, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SmsProviderUpdateOne) SaveX(ctx context.Context) *SmsProvider {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SmsProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SmsProviderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SmsProviderUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := smsprovider.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "SmsProvider.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := smsprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SmsProvider.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := smsprovider.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "SmsProvider.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CredentialRef(); ok {
		if err := smsprovider.CredentialRefValidator(v); err != nil {
			return &ValidationError{Name: "credential_ref", err: fmt.Errorf(`ent: validator failed for field "SmsProvider.credential_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HealthStatus(); ok {
		if err := smsprovider.HealthStatusValidator(v); err != nil {
			return &ValidationError{Name: "health_status", err: fmt.Errorf(`ent: validator failed for field "SmsProvider.health_status": %w`, err)}
		}
	}
	return nil
}

func (_u *SmsProviderUpdateOne) sqlSave(ctx context.Context) (_node *SmsProvider, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(smsprovider.Table, smsprovider.Columns, sqlgraph.NewFieldSpec(smsprovider.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SmsProvider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, smsprovider.FieldID)
		for _, f := range fields {
			if !smsprovider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != smsprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(smsprovider.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(smsprovider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(smsprovider.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialRef(); ok {
		_spec.SetField(smsprovider.FieldCredentialRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(smsprovider.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HealthStatus(); ok {
		_spec.SetField(smsprovider.FieldHealthStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(smsprovider.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(smsprovider.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(smsprovider.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(smsprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SmsProvider{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{smsprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
