export default {
  workspace: {
    lifecycle: {
      title: 'Data lifecycle', description: 'Manage retention, exports, archive and business closure for this workspace.', refresh: 'Refresh', signIn: 'Sign in again',
      retention: 'Retention policy', retentionHint: 'Financial and audit evidence is retained indefinitely. Other categories follow the current effective policy.', category: 'Category', effectiveRetention: 'Effective retention', minimum: 'Minimum retention', actions: 'Actions', indefinite: 'Indefinite', days: '{days} days', protected: 'Protected under current policy', retentionFor: 'Retention days for {category}', retentionFloorHint: '0 retains data indefinitely. A finite value must meet the category minimum.', readOnly: 'Read only',
      archiveRestore: 'Archive and restore', archiveHint: 'Archiving stops new workspace operations and preserves its history. Restore resumes access only after server security checks.', archiveWorkspace: 'Archive workspace', restoreWorkspace: 'Restore workspace', archiveConfirm: 'Archive this workspace and stop new operations?', restoreHint: 'Restore this archived resource? Current membership, billing and authentication requirements will be checked.', restoreProject: 'Restore project', projectLifecycle: 'Project lifecycle', projectArchiveHint: 'Archiving preserves project history and stops new operations. A project can be restored only while its parent workspace is active.',
      exports: 'Export history', exportHint: 'Exports contain an allowlisted data snapshot without credential secrets. They are not a complete backup and cannot restore a workspace.', createExport: 'Create export', exportDisabled: 'Export creation is disabled by platform configuration.', noExports: 'No exports yet.', exportJob: 'Export job', progress: 'Progress', snapshot: 'Snapshot cutoff', artifact: 'Artifact', processed: '{count} records processed', attempts: '{count} attempts', bytes: '{count} bytes', created: 'Created', updated: 'Updated', completed: 'Completed', expires: 'Expires', download: 'Download ZIP', cancelExport: 'Cancel export', exportPagination: 'Export history pages', previous: 'Previous', next: 'Next', page: 'Page {page} of {pages}', downloadExpired: 'The download authorization expired. Request another download.',
      deletion: 'Workspace deletion', deletionHint: 'Deletion closes workspace business after a cooling period of at least 7 days. Protected evidence and tenant identifiers remain retained; this does not promise physical erasure.', retainedConfiguration: 'Configuration that is not eligible under current retention remains retained during business closure.', purgeDisabled: 'Deletion cleanup is disabled by platform configuration.', businessClosure: 'Business closure', businessClosed: 'Business closed', businessNotClosed: 'Business not yet closed', protectedEvidence: 'Protected evidence', evidenceRetained: 'Protected financial and audit evidence is retained', evidenceStatusUnknown: 'Review the server evidence status', phase: 'Current phase', earliestPurge: 'Earliest cleanup', cancelDeletion: 'Cancel deletion', retryDeletion: 'Retry blocked or failed deletion', checkPreflight: 'Check deletion eligibility', requestDeletion: 'Request deletion', eligible: 'Eligible for a deletion request', blocked: 'Deletion is blocked', cappedCounts: 'Some counts are capped and represent a lower bound. The server rechecks blockers before processing.', protectedResource: 'Protected: {resource}', purgeScope: 'Estimated cleanup scope', retainedScope: 'Retained scope', confirmDeletion: 'Confirm workspace deletion', exactName: 'Enter the exact current workspace name: {name}', exactNameHint: 'The name must match exactly, including spaces and letter case.', challengeExpired: 'The deletion confirmation expired. Generate a fresh confirmation before continuing.', confirmationExpires: 'Confirmation expires', refreshChallenge: 'Generate fresh confirmation', operationSuccess: 'The server accepted the operation.', requestError: 'The lifecycle request failed. Refresh and try again.', verificationCancelled: 'Authentication verification was cancelled. The operation has not been retried.',
      categories: { financial: 'Financial evidence', audit: 'Audit evidence', operational: 'Operational data', security: 'Security data', temporary: 'Temporary artifacts' },
      states: { pending: 'Pending', running: 'Running', completed: 'Completed', failed: 'Failed', cancelled: 'Cancelled', expired: 'Expired', blocked: 'Blocked' },
      phases: { credentials: 'Credentials', service_accounts: 'Service accounts', invitations: 'Invitations', access_grants: 'Access grants', project_allocation_configuration: 'Project allocation configuration', key_allocation_configuration: 'Key allocation configuration', machine_allocation_configuration: 'Service account allocation configuration', identity_credentials: 'Identity credentials', scim_credentials: 'SCIM credentials', scim_connectors: 'SCIM connectors', webhook_credentials: 'Webhook credentials', member_access: 'Membership access', teams: 'Teams', projects: 'Projects', grants: 'Access grants', allocation: 'Allocation configuration', members: 'Membership access', descriptions: 'Business descriptions', verify: 'Completion checks', completed: 'Completed' },
      resources: { projects: 'Projects', members: 'Members', service_accounts: 'Service accounts', credentials: 'Credentials', api_keys: 'API keys', invitations: 'Invitations', active_holds: 'Active holds', usage_logs: 'Usage records', reservations: 'Reservations', running_exports: 'Running exports', pending_budget_reservations: 'Pending budget reservations', reserved_budget_counters: 'Reserved budget counters', pending_quota_reservations: 'Pending quota reservations', pending_billing_settlements: 'Pending billing settlements', pending_async_images: 'Pending media tasks', pending_exports: 'Pending exports', pending_webhook_deliveries: 'Pending webhook deliveries', pending_outbox: 'Pending domain events', budget_reservations: 'Budget reservations', allocation_snapshots: 'Usage allocation snapshots', reservation_allocation_snapshots: 'Reservation allocation snapshots', anomaly_evidence: 'Anomaly evidence', audit_logs: 'Audit records' },
      scopes: { credential_values: 'Credential secret values', credentials: 'Credentials', invitations: 'Invitations', project_access_grants: 'Project access grants', allocation_configuration: 'Eligible allocation configuration', non_owner_membership_access: 'Member access other than the owner', business_resource_descriptions: 'Eligible business resource descriptions', global_users_and_wallets: 'Global users and wallets', workspace_project_credential_identifiers: 'Workspace, project and credential identifiers', usage_and_reservations: 'Usage and reservations', settlement_refund_dedup: 'Settlement, refund and deduplication evidence', immutable_allocation_anomaly_evidence: 'Immutable allocation and anomaly evidence', audit_and_policy_protected_metadata: 'Audit and policy-protected metadata', policy_ineligible_business_configuration: 'Business configuration protected by current retention', global_user_owned_canvas_media: 'Canvas media owned by global users', financial_evidence: 'Financial evidence' },
    },
  },
}
