export default {
  workspace: {
    historicalUsageNote: 'Historical usage without a workspace or project remains unassigned and is available on the original Usage page. It is excluded from these totals.',
    dailySpend: 'Daily spend', date: 'Date',
    archive: 'Archive', groupPolicy: 'Group access', modelPolicy: 'Model access', allowedGroupIds: 'Allowed group IDs', allowedModels: 'Allowed models', groupIdsHint: 'One positive group ID per line', modelsHint: 'One exact model ID per line', accessModes: { inherit: 'Inherit access', restricted: 'Allow selected entries', deny: 'Deny all' }, accessPolicyHint: 'Project policies can narrow the billing principal’s group and model access.', invalidAccessPolicy: 'Enter valid group IDs and at least one model for selected-entry policies.',
    inaccessibleWorkspace: 'This workspace is unavailable or you no longer have access.', acceptInvitation: 'Accept invitation', acceptInvitationDescription: 'Enter the invitation token supplied by a workspace administrator.', acceptInvitationError: 'The invitation could not be accepted.', noInvitations: 'No invitations found.', roles: { owner: 'Owner', admin: 'Admin', developer: 'Developer', billing: 'Billing', viewer: 'Viewer' },
    platforms: 'Platforms', models: 'Models', apiKeys: 'API keys', noUsage: 'No usage in this period.', projectBudgetDescription: 'Current budget reservation and spend for this project.', projectBudgetUnavailable: 'Project budget data is unavailable.', projectOverBudget: 'This project is over its configured budget.', projectUsageUnavailable: 'Project usage data is unavailable.', usageDescription: 'Requests and spend within the displayed period.',
    eyebrow: 'Tenant workspace', title: 'Workspace', description: 'Choose a workspace and project to manage access, keys, and spend.', createWorkspace: 'Create workspace', settings: 'Workspace settings', settingsDescription: 'Update workspace identity separately from its billing principal.', billingOwner: 'Billing principal',
    workspace: 'Workspace', project: 'Project', sections: 'Workspace sections', overview: 'Overview', projects: 'Projects', members: 'Members', invitations: 'Invitations', finops: 'FinOps', audit: 'Audit', keys: 'Project keys',
    projectsDescription: 'Projects isolate routing policy, keys, and usage inside this workspace.', createProject: 'Create project', editProject: 'Edit project', noProjects: 'No projects are available in this workspace.', default: 'Default', slug: 'Slug', descriptionLabel: 'Description', saveError: 'The workspace change could not be saved.', archiveConfirm: 'Archive this project?', loadError: 'The workspace could not be loaded.',
    membersDescription: 'Review access and suspend or remove members with the permissions returned by the server.', noMembers: 'No members found.', member: 'Member', role: 'Role', roleFor: 'Role for', invite: 'Invite member', suspend: 'Suspend', activate: 'Activate', remove: 'Remove', removeConfirm: 'Remove this member?', updateMemberError: 'The member change could not be saved.',
    invitationDescription: 'Invitations expire and can be revoked before acceptance.', email: 'Email', expires: 'Expires', pending: 'Pending', revoked: 'Revoked', accepted: 'Accepted', createInvitation: 'Create invitation', invitationToken: 'Invitation token', copyToken: 'Copy token', revoke: 'Revoke', revokeConfirm: 'Revoke this invitation?', invitationError: 'The invitation could not be saved.',
    requests: 'Requests', spend: 'Spend', budget: 'Budget', budgetDescription: 'Current server-reported reservation and spend state for this workspace.', viewFinops: 'View FinOps', spent: 'Spent', reserved: 'Reserved', remaining: 'Remaining', overBudget: 'This workspace is over its configured budget.', policy: 'Budget policy', amount: 'Monthly amount', hardLimit: 'Hard limit', enabled: 'Enabled', timezone: 'Timezone', updateBudget: 'Update budget', budgetUnavailable: 'Budget data is not available for this workspace yet.', usage: 'Usage', usageUnavailable: 'Usage data is not available for this workspace yet.', trend: 'Spend trend', breakdown: 'Breakdown',
    auditDescription: 'Tenant-scoped changes are recorded here for review.', noAudit: 'No audit events found.', action: 'Action', actor: 'Actor', target: 'Target', created: 'Created',
    keyDescription: 'Project keys inherit project restrictions. The secret is shown only once after creation.', createKey: 'Create project key', editKey: 'Edit project key', keyName: 'Key name', keySecret: 'Secret', copySecret: 'Copy secret', maskedSecret: 'Masked after creation', status: 'Status', revokeKey: 'Revoke key', revokeKeyConfirm: 'Revoke this project key?', keyError: 'The project key could not be saved.', noKeys: 'No project keys found.', group: 'Group', noGroup: 'No group', quotaUsage: 'Quota / usage', rateLimits: 'Rate limits', rateLimit5h: '5-hour limit', rateLimit1d: '1-day limit', rateLimit7d: '7-day limit', ipWhitelist: 'IP allowlist', ipBlacklist: 'IP blocklist', ipListHint: 'One address or CIDR per line', unlimited: 'Unlimited',
    adminTitle: 'Workspace administration', adminDescription: 'Inspect and suspend tenant workspaces with the global admin permission.', adminUnavailable: 'Workspace administration is unavailable.', inspect: 'Inspect', suspendWorkspace: 'Suspend workspace', activateWorkspace: 'Activate workspace', statusError: 'The workspace status could not be changed.'
  }
}
