#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def replace_once(rel: str, old: str, new: str) -> None:
    path = ROOT / rel
    text = path.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{rel}: expected one match, found {count}: {old[:120]!r}")
    path.write_text(text.replace(old, new, 1), encoding="utf-8")


# Strict redaction must fail closed on a settings-store error. Missing keys still
# remain backward compatible because an empty value is interpreted as visible.
replace_once(
    "backend/internal/service/setting_public.go",
    '''// GetUsageDetailVisibility reads all three switches in one query. It deliberately
// fails open to the historical behavior so a transient settings-store failure does
// not unexpectedly remove fields from an already-running production deployment.
func (s *SettingService) GetUsageDetailVisibility(ctx context.Context) UsageDetailVisibility {
\tdefaults := defaultUsageDetailVisibility()
\tif s == nil || s.settingRepo == nil {
\t\treturn defaults
\t}
''',
    '''// GetUsageDetailVisibility reads all three switches in one query. Missing keys
// preserve the historical visible behavior, while repository failures fail closed
// so a temporary infrastructure error cannot disclose fields an operator hid.
func (s *SettingService) GetUsageDetailVisibility(ctx context.Context) UsageDetailVisibility {
\tdefaults := defaultUsageDetailVisibility()
\tif s == nil || s.settingRepo == nil {
\t\treturn defaults
\t}
''',
)
replace_once(
    "backend/internal/service/setting_public.go",
    '''\tif err != nil {
\t\tslog.Warn("failed to get user usage detail visibility, defaulting to visible", "error", err)
\t\treturn defaults
\t}
''',
    '''\tif err != nil {
\t\tslog.Error("failed to get user usage detail visibility, redacting all optional billing details", "error", err)
\t\treturn UsageDetailVisibility{}
\t}
''',
)

# Avoid showing a misleading $0 unit price when strict redaction removes
# total_cost. Image/per-request unit prices can reconstruct the original amount,
# so they are only shown while the original-cost switch is also enabled.
replace_once(
    "frontend/src/components/admin/usage/UsageTable.vue",
    'v-if="showUnitPrices || showOriginalCost || (tooltipData && isImageUsage(tooltipData))"',
    'v-if="showUnitPrices || (tooltipData && isImageUsage(tooltipData))"',
)
replace_once(
    "frontend/src/components/admin/usage/UsageTable.vue",
    '<div v-if="showUnitPrices" class="flex items-center justify-between gap-4">\n                <span class="text-gray-400">{{ t(\'usage.imageUnitPrice\') }}</span>',
    '<div v-if="showUnitPrices && showOriginalCost" class="flex items-center justify-between gap-4">\n                <span class="text-gray-400">{{ t(\'usage.imageUnitPrice\') }}</span>',
)
replace_once(
    "frontend/src/components/admin/usage/UsageTable.vue",
    '<div v-else-if="showUnitPrices" class="flex items-center justify-between gap-4">\n              <span class="text-gray-400">{{ t(\'usage.unitPrice\') }}</span>',
    '<div v-else-if="showUnitPrices && showOriginalCost" class="flex items-center justify-between gap-4">\n              <span class="text-gray-400">{{ t(\'usage.unitPrice\') }}</span>',
)
replace_once(
    "frontend/src/views/admin/SettingsView.vue",
    '关闭后，同时隐藏费用拆分、缓存及图片单价，并从普通用户用量 API 响应中移除对应成本字段。',
    '关闭后，同时隐藏费用拆分、缓存及图片单价，并从普通用户用量 API 响应中移除对应成本字段。图片和按次单价同时依赖“显示原始金额”开关，以避免反推出原始金额。',
)
replace_once(
    "frontend/src/views/admin/SettingsView.vue",
    'When disabled, cost breakdown, cache and image unit prices are hidden and the related cost fields are removed from user usage API responses.',
    'When disabled, cost breakdown, cache and image unit prices are hidden and the related cost fields are removed from user usage API responses. Image and per-request unit prices also require original cost to remain enabled so the original amount cannot be reconstructed.',
)

# Upgrade the reviewed vulnerable PostCSS release instead of adding a temporary
# audit exception. The lockfile is regenerated by the verification workflow.
replace_once(
    "frontend/package.json",
    '"postcss": "^8.5.12"',
    '"postcss": "^8.5.18"',
)
replace_once(
    "frontend/package.json",
    '"postcss": "8.5.12"',
    '"postcss": "8.5.18"',
)

# Extend the UI contract test with the mixed-switch case that previously could
# render a misleading zero image unit price after backend redaction.
test_path = ROOT / "frontend/src/components/admin/usage/__tests__/UsageTable.visibility.spec.ts"
test_text = test_path.read_text(encoding="utf-8")
anchor = "\n})\n"
if not test_text.endswith(anchor):
    raise RuntimeError("visibility test: unexpected file ending")
extra = r'''

  it('does not reconstruct image original cost through a unit price when original cost is hidden', async () => {
    vi.spyOn(HTMLElement.prototype, 'getBoundingClientRect').mockReturnValue({
      x: 0,
      y: 0,
      top: 20,
      left: 20,
      right: 120,
      bottom: 40,
      width: 100,
      height: 20,
      toJSON: () => ({}),
    } as DOMRect)

    const wrapper = mount(UsageTable, {
      props: {
        data: [{
          request_id: 'req-user-image-redacted-original',
          model: 'gpt-image-2',
          actual_cost: 0.12,
          rate_multiplier: 0.6,
          account_rate_multiplier: 1,
          service_tier: 'standard',
          input_cost: 0,
          output_cost: 0,
          cache_creation_cost: 0,
          cache_read_cost: 0,
          input_tokens: 0,
          output_tokens: 0,
          cache_creation_tokens: 0,
          cache_read_tokens: 0,
          billing_mode: 'image',
          image_count: 2,
          image_size: '2K',
          image_input_size: null,
          image_output_size: null,
          image_size_source: null,
          image_size_breakdown: null,
        }],
        loading: false,
        columns: [],
        showAccountBilling: false,
        showUnitPrices: true,
        showRateMultiplier: true,
        showOriginalCost: false,
      },
      global: {
        stubs: {
          DataTable: DataTableStub,
          EmptyState: true,
          Icon: true,
          Teleport: true,
        },
      },
    })

    await wrapper.get('.group.relative').trigger('mouseenter')
    await nextTick()

    const text = wrapper.text()
    expect(text).toContain('User billed')
    expect(text).not.toContain('Original')
    expect(text).not.toContain('usage.imageUnitPrice')
    expect(text).not.toContain('$0.000000')
  })
'''
test_path.write_text(test_text[:-len(anchor)] + extra + anchor, encoding="utf-8")

print("usage privacy hardening patch applied")
